skcard . "I and Peter live here" "Ja a Peter tu bývame"
skcard . "I and Peter do not live here" "Ja a Peter tu nebývame"
skcard . "They are not here" "Oni nie sú tu"
skcard . "They are here" "Oni sú tu"
skcard . "I have a suitcase" "Ja mám kufor"
skcard . "You have a suitcase" "Ty máš kufor"
skcard . "Peter has a suitcase" "Peter má kufor"
skcard . "He has a suitcase" "On má kufor"
skcard . "She has a suitcase" "Ona má kufor"
skcard . "It has a suitcase" "To má kufor"
skcard . "We have a suitcase" "My máme kufor"
skcard . "I and Peter have a suitcase" "Ja a Peter máme kufor"
skcard . "Y'all have a suitcase" "Vy máte kufor"
skcard . "You and Peter have a suitcase" "Ty a Peter máte kufor"
skcard . "Igor and Peter have a suitcase" "Igor a Peter majú kufor"
skcard . "They have a suitcase" "Oni majú kufor"
skcard . "I am here" "Ja som tu"
skcard . "You are here" "Ty si tu"
skcard . "Peter is here" "Peter je tu"
skcard . "He is here" "On je tu"
skcard . "She is here" "Ona je tu"
skcard . "It is here" "To je tu"
skcard . "We are here" "My sme tu"
skcard . "I and Peter are here" "Ja a Peter sme tu"
skcard . "Y'all are here" "Vy ste tu"
skcard . "You and Peter are here" "Ty a Peter ste tu"
skcard . "Igor and Peter are here" "Igor a Peter sú tu"
skcard . "I am waiting" "Ja čakám"
skcard . "You are waiting" "Ty čakáš"
skcard . "Peter is waiting" "Peter čaká"
skcard . "He is waiting" "On čaká"
skcard . "She is waiting" "Ona čaká"
skcard . "It is waiting" "To čaká"
skcard . "We are waiting" "My čakáme"
skcard . "I and Peter are waiting" "Ja a Peter čakáme"
skcard . "Y'all are waiting" "Vy čakáte"
skcard . "You and Peter are waiting" "Ty a Peter čakáte"
skcard . "Igor and Peter are waiting" "Igor a Peter čakajú"
skcard . "They are waiting" "Oni čakajú"
skcard . "I live here" "Ja tu bývam"
skcard . "You live here" "Ty tu bývaš"
skcard . "Peter lives here" "Peter tu býva"
skcard . "He lives here" "On tu býva"
skcard . "She lives here" "Ona tu býva"
skcard . "It lives here" "To tu býva"
skcard . "We live here" "My tu bývame"
skcard . "Y'all live here" "Vy tu bývate"
skcard . "You and Peter live here" "Ty a Peter tu bývate"
skcard . "Igor and Peter live here" "Igor a Peter tu bývajú"
skcard . "They live here" "Ony tu bývajú"
skcard . "I do not have a suitcase" "Ja nemám kufor"
skcard . "You do not have a suitcase" "Ty nemáš kufor"
skcard . "Peter does not have a suitcase" "Peter nemá kufor"
skcard . "He does not have a suitcase" "On nemá kufor"
skcard . "She does not have a suitcase" "Ona nemá kufor"
skcard . "It does not have a suitcase" "To nemá kufor"
skcard . "We do not have a suitcase" "My nemáme kufor"
skcard . "I and Peter do not have a suitcase" "Ja a Peter nemáme kufor"
skcard . "Y'all do not have a suitcase" "Vy nemáte kufor"
skcard . "You and Peter do not have a suitcase" "Ty a Peter nemáte kufor"
skcard . "Igor and Peter do not have a suitcase" "Igor a Peter nemajú kufor"
skcard . "They do not have a suitcase" "Oni nemajú kufor"
skcard . "I am not here" "Ja nie som tu"
skcard . "You are not here" "Ty nie si tu"
skcard . "Peter is not here" "Peter nie je tu"
skcard . "He is not here" "On nie je tu"
skcard . "She is not here" "Ona nie je tu"
skcard . "It is not here" "To nie je tu"
skcard . "We are not here" "My nie sme tu"
skcard . "I and Peter are not here" "Ja a Peter nie sme tu"
skcard . "Y'all are not here" "Vy nie ste tu"
skcard . "You and Peter are not here" "Ty a Peter nie ste tu"
skcard . "Igor and Peter are not here" "Igor a Peter nie sú tu"
skcard . "I am not waiting" "Ja nečakám"
skcard . "You are not waiting" "Ty nečakáš"
skcard . "Peter is not waiting" "Peter nečaká"
skcard . "He is not waiting" "On nečaká"
skcard . "She is not waiting" "Ona nečaká"
skcard . "It is not waiting" "To nečaká"
skcard . "We are not waiting" "My nečakáme"
skcard . "I and Peter are not waiting" "Ja a Peter nečakáme"
skcard . "Y'all are not waiting" "Vy nečakáte"
skcard . "You and Peter are not waiting" "Ty a Peter nečakáte"
skcard . "Igor and Peter are not waiting" "Igor a Peter nečakajú"
skcard . "They are not waiting" "Oni nečakajú"
skcard . "I do not live here" "Ja tu nebývam"
skcard . "You do not live here" "Ty tu nebývaš"
skcard . "Peter does not live here" "Peter tu nebýva"
skcard . "He does not live here" "On tu nebýva"
skcard . "She does not live here" "Ona tu nebýva"
skcard . "It does not live here" "To tu nebýva"
skcard . "We do not live here" "My tu nebývame"
skcard . "Y'all do not live here" "Vy tu nebývate"
skcard . "You and Peter do not live here" "Ty a Peter tu nebývate"
skcard . "Igor and Peter do not live here" "Igor a Peter tu nebývajú"
skcard . "They do not live here" "Ony tu nebývajú"
