skcard . "Vladimir is French" "Vladimir je Francúz"
skcard . "Vladimir is from Russia" "Vladimir je z Ruska"
skcard . "I see Greece" "ja vidím Grécko"
skcard . "I see Japan" "ja vidím Japonsko"
skcard . "I have a luxembourgish car" "ja mám luxemburské auto"
skcard . "Sofia and Natália are Belgians" "Sofia a Natália sú Belgičanky"
skcard . "Natália is a Luxembourger" "Natália je Luxemburčanka"
skcard . "Vladimir is from Lithuania" "Vladimir je z Litvy"
skcard . "I have a swiss car" "ja mám švajčiarske auto"
skcard . "I have a portugese car" "ja mám portugalské auto"
skcard . "Vladimir knows swiss" "Vladimir vie po švajčiarsky"
skcard . "Jakub and Vladimir are Swedes" "Jakub a Vladimir sú Švédi"
skcard . "Natália is a Finn" "Natália je Fínka"
skcard . "I have a montenegrin book" "ja mám čiernohorskú knihu"
skcard . "Vladimir speaks irish" "Vladimir hovorí po írsky"
skcard . "Vladimir speaks liechtensteinish" "Vladimir hovorí po lichtenštajnsky"
skcard . "I have a russian shop" "ja mám ruský obchod"
skcard . "Vladimir reads luxembourgish" "Vladimir číta po luxembursky"
skcard . "Natália is a European" "Natália je Európanka"
skcard . "I have a british shop" "ja mám britský obchod"
skcard . "Vladimir is a Greek" "Vladimir je Grék"
skcard . "Vladimir reads italian" "Vladimir číta po taliansky"
skcard . "Vladimir speaks slovakian" "Vladimir hovorí po slovensky"
skcard . "Jakub and Vladimir are Slovaks" "Jakub a Vladimir sú Slováki"
skcard . "I have a chinese shop" "ja mám čínsky obchod"
skcard . "I have a slovakian car" "ja mám slovenské auto"
skcard . "I see Turkey" "ja vidím Turecko"
skcard . "Jakub and Vladimir are Spaniards" "Jakub a Vladimir sú Španieli"
skcard . "I have a polish car" "ja mám poľské auto"
skcard . "I have a hungarian car" "ja mám maďarské auto"
skcard . "Vladimir is a Mexican" "Vladimir je Mexičan"
skcard . "Vladimir knows estonian" "Vladimir vie po estónsky"
skcard . "Vladimir knows swedish" "Vladimir vie po švédsky"
skcard . "Natália is a Ukranian" "Natália je Ukrajinka"
skcard . "Vladimir knows slovakian" "Vladimir vie po slovensky"
skcard . "Sofia and Natália are Estonians" "Sofia a Natália sú Estónky"
skcard . "Jakub and Vladimir are Luxembourgers" "Jakub a Vladimir sú Luxemburčani"
skcard . "Vladimir is a Portugese" "Vladimir je Portugalec"
skcard . "Jakub and Vladimir are Austrians" "Jakub a Vladimir sú Rakúšani"
skcard . "Vladimir reads mexican" "Vladimir číta po mexicky"
skcard . "Estonia is nice" "Estónsko je pekné"
skcard . "Natália is Chinese" "Natália je Číňanka"
skcard . "Vladimir knows finnish" "Vladimir vie po fínsky"
skcard . "Vladimir is a Slovene" "Vladimir je Slovinec"
skcard . "Vladimir is from Poland" "Vladimir je z Poľska"
skcard . "I have a greek car" "ja mám grécke auto"
skcard . "Vladimir reads belarusian" "Vladimir číta po bielorusky"
skcard . "I have a chinese car" "ja mám čínske auto"
skcard . "I have a russian book" "ja mám ruskú knihu"
skcard . "I have a english book" "ja mám anglickú knihu"
skcard . "I have a liechtensteinish book" "ja mám lichtenštajnskú knihu"
skcard . "Vladimir is from Liechtenstein" "Vladimir je z Lichtenštajnska"
skcard . "Jakub and Vladimir are Ukranians" "Jakub a Vladimir sú Ukrajineci"
skcard . "Vladimir reads montenegrin" "Vladimir číta po čiernohorsky"
skcard . "Vladimir reads slovenian" "Vladimir číta po slovinsky"
skcard . "Vladimir is a Norwegian" "Vladimir je Nór"
skcard . "I see Switzerland" "ja vidím Švajčiarsko"
skcard . "Vladimir knows russian" "Vladimir vie po rusky"
skcard . "Poland is nice" "Poľsko je pekné"
skcard . "Vladimir knows spanish" "Vladimir vie po španielsky"
skcard . "Vladimir knows portugese" "Vladimir vie po portugalsky"
skcard . "I have a turkish book" "ja mám tureckú knihu"
skcard . "Vladimir is from Europe" "Vladimir je z Európy"
skcard . "I have a greek shop" "ja mám grécky obchod"
skcard . "Sofia and Natália are Lithuanians" "Sofia a Natália sú Litovčanky"
skcard . "Jakub and Vladimir are Serbians" "Jakub a Vladimir sú Srbi"
skcard . "I have a mexican book" "ja mám mexickú knihu"
skcard . "I see Ireland" "ja vidím Írsko"
skcard . "Vladimir speaks herzegovinian" "Vladimir hovorí po hercegovsky"
skcard . "Sofia and Natália are Italians" "Sofia a Natália sú Talianky"
skcard . "I have a slovakian shop" "ja mám slovenský obchod"
skcard . "I have a german car" "ja mám nemecké auto"
skcard . "Germany is nice" "Nemecko je pekné"
skcard . "Vladimir is from Mexico" "Vladimir je z Mexika"
skcard . "Vladimir reads vatican" "Vladimir číta po vatikánsky"
skcard . "Vladimir reads liechtensteinish" "Vladimir číta po lichtenštajnsky"
skcard . "Luxembourg is nice" "Luxembursko je pekné"
skcard . "Sofia and Natália are Swiss" "Sofia a Natália sú Švajčiarky"
skcard . "Greece is nice" "Grécko je pekné"
skcard . "Natália is French" "Natália je Francúzka"
skcard . "Vladimir knows german" "Vladimir vie po nemecky"
skcard . "Vladimir is from Czechia" "Vladimir je z Česka"
skcard . "Vladimir knows irish" "Vladimir vie po írsky"
skcard . "I have an irish shop" "ja mám írsky obchod"
skcard . "Natália is an Estonian" "Natália je Estónka"
skcard . "I have a turkish car" "ja mám turecké auto"
skcard . "Vladimir reads czech" "Vladimir číta po česky"
skcard . "Vladimir speaks french" "Vladimir hovorí po francúzsky"
skcard . "Natália is a Belgian" "Natália je Belgičanka"
skcard . "Jakub and Vladimir are Italians" "Jakub a Vladimir sú Taliani"
skcard . "I have a polish book" "ja mám poľskú knihu"
skcard . "I have a portugese book" "ja mám portugalskú knihu"
skcard . "Vladimir knows turkish" "Vladimir vie po turecky"
skcard . "Jakub and Vladimir are Scots" "Jakub a Vladimir sú Škóti"
skcard . "Natália is an Italian" "Natália je Talianka"
skcard . "I have a latvian car" "ja mám lotyšské auto"
skcard . "Vladimir reads finnish" "Vladimir číta po fínsky"
skcard . "I see Belgium" "ja vidím Belgicko"
skcard . "Natália is English" "Natália je Angličanka"
skcard . "Vladimir is a Serb" "Vladimir je Srb"
skcard . "Vladimir is from Austria" "Vladimir je z Rakúska"
skcard . "Vladimir reads american" "Vladimir číta po americky"
skcard . "I have a macedonian car" "ja mám macedónske auto"
skcard . "I see Belarus" "ja vidím Bielorusko"
skcard . "Vladimir speaks croatian" "Vladimir hovorí po chorvátsky"
skcard . "Sofia and Natália are brits" "Sofia a Natália sú Britky"
skcard . "Vladimir is a Moldavian" "Vladimir je Moldavčan"
skcard . "Vladimir is from Serbia" "Vladimir je zo Srbska"
skcard . "Vladimir is from Japan" "Vladimir je z Japonska"
skcard . "I have a norwegian car" "ja mám nórske auto"
skcard . "Sofia and Natália are Moldavians" "Sofia a Natália sú Moldavčanky"
skcard . "Vladimir is an Italian" "Vladimir je Talian"
skcard . "I have a japanese shop" "ja mám japonský obchod"
skcard . "Natália is an Austrian" "Natália je Rakúšanka"
skcard . "Vladimir knows english" "Vladimir vie po anglicky"
skcard . "Sofia and Natália are Dutch" "Sofia a Natália sú Holanďanky"
skcard . "Vladimir is from Estonia" "Vladimir je z Estónska"
skcard . "Vladimir knows american" "Vladimir vie po americky"
skcard . "Vladimir is a German" "Vladimir je Nemec"
skcard . "Vladimir knows moldavian" "Vladimir vie po moldavsky"
skcard . "Sofia and Natália are Russians" "Sofia a Natália sú Rusky"
skcard . "I see Slovakia" "ja vidím Slovensko"
skcard . "Montenegro is nice" "Čierna Hora je pekná"
skcard . "Vladimir reads japanese" "Vladimir číta po japonsky"
skcard . "I have an american book" "ja mám americkú knihu"
skcard . "I have a swiss book" "ja mám švajčiarsku knihu"
skcard . "Sofia and Natália are Americans" "Sofia a Natália sú Američanky"
skcard . "Sofia and Natália are Luxembourgers" "Sofia a Natália sú Luxemburčanky"
skcard . "I have a belgian book" "ja mám belgickú knihu"
skcard . "Vladimir is a Croat" "Vladimir je Chorvát"
skcard . "I have a dutch car" "ja mám holandské auto"
skcard . "Vladimir reads scottish" "Vladimir číta po škótsky"
skcard . "I see Holland" "ja vidím Holandsko"
skcard . "I see Austria" "ja vidím Rakúsko"
skcard . "Vladimir reads macedonian" "Vladimir číta po macedónsky"
skcard . "Vladimir speaks american" "Vladimir hovorí po americky"
skcard . "Jakub and Vladimir are Portugese" "Jakub a Vladimir sú Portugaleci"
skcard . "Vladimir reads moldavian" "Vladimir číta po moldavsky"
skcard . "Natália is Japanese" "Natália je Japonka"
skcard . "Vladimir speaks bosnian" "Vladimir hovorí po bosniansky"
skcard . "Sofia and Natália are Montenegrins" "Sofia a Natália sú Čiernohorky"
skcard . "Natália is a Montenegrin" "Natália je Čiernohorka"
skcard . "I have a slovakian book" "ja mám slovenskú knihu"
skcard . "Vladimir knows norwegian" "Vladimir vie po nórsky"
skcard . "Vladimir is a Belgian" "Vladimir je Belgičan"
skcard . "Vladimir is from Slovakia" "Vladimir je zo Slovenska"
skcard . "Vladimir is a Swede" "Vladimir je Švéd"
skcard . "Vladimir speaks czech" "Vladimir hovorí po česky"
skcard . "Natália is a Lithuanian" "Natália je Litovčanka"
skcard . "I see Sweden" "ja vidím Švédsko"
skcard . "I have a belgian shop" "ja mám belgický obchod"
skcard . "Vladimir reads hungarian" "Vladimir číta po maďarsky"
skcard . "Belarus is nice" "Bielorusko je pekné"
skcard . "Vladimir speaks russian" "Vladimir hovorí po rusky"
skcard . "Sofia and Natália are Belarus" "Sofia a Natália sú Bielorusky"
skcard . "Jakub and Vladimir are Russians" "Jakub a Vladimir sú Rusi"
skcard . "I have a hungarian shop" "ja mám maďarský obchod"
skcard . "Natália is Swiss" "Natália je Švajčiarka"
skcard . "I have a bosnian book" "ja mám bosniansku knihu"
skcard . "China is nice" "Čína je pekná"
skcard . "I see Slovenia" "ja vidím Slovinsko"
skcard . "Jakub and Vladimir are Croatians" "Jakub a Vladimir sú Chorváti"
skcard . "I see Ukraine" "ja vidím Ukrajinu"
skcard . "Natália is a Czech" "Natália je Češka"
skcard . "I have a bosnian shop" "ja mám bosniansky obchod"
skcard . "Jakub and Vladimir are Englishmen" "Jakub a Vladimir sú Angličani"
skcard . "I have a spanish car" "ja mám španielske auto"
skcard . "Sofia and Natália are Mexicans" "Sofia a Natália sú Mexičanky"
skcard . "Slovakia is nice" "Slovensko je pekné"
skcard . "Vladimir reads bosnian" "Vladimir číta po bosniansky"
skcard . "Vladimir reads dutch" "Vladimir číta po holandsky"
skcard . "Turkey is nice" "Turecko je pekné"
skcard . "I have a croatian shop" "ja mám chorvátsky obchod"
skcard . "Vladimir is an American" "Vladimir je Američan"
skcard . "Vladimir is from Sweden" "Vladimir je z Švédska"
skcard . "Japan is nice" "Japonsko je pekné"
skcard . "I have a serbian book" "ja mám srbskú knihu"
skcard . "Vladimir is from Holland" "Vladimir je z Holandska"
skcard . "Vladimir is from Italy" "Vladimir je z Talianska"
skcard . "Vladimir is a Belarusian" "Vladimir je Bielorus"
skcard . "I see Spain" "ja vidím Španielsko"
skcard . "I have a lithuanian shop" "ja mám litovský obchod"
skcard . "Natália is a Pole" "Natália je Poľka"
skcard . "I have a french car" "ja mám francúzske auto"
skcard . "Ukraine is nice" "Ukrajina je pekná"
skcard . "Vladimir is Swiss" "Vladimir je Švajčiar"
skcard . "Jakub and Vladimir are Bosnians" "Jakub a Vladimir sú Bosniaki"
skcard . "Jakub and Vladimir are Swiss" "Jakub a Vladimir sú Švajčiari"
skcard . "I have a swiss shop" "ja mám švajčiarsky obchod"
skcard . "Jakub and Vladimir are Greeks" "Jakub a Vladimir sú Gréki"
skcard . "I have a norwegian book" "ja mám nórsku knihu"
skcard . "Russia is nice" "Rusko je pekné"
skcard . "Sofia and Natália are Latvians" "Sofia a Natália sú Lotyšky"
skcard . "Vladimir knows belgian" "Vladimir vie po belgicky"
skcard . "Vladimir speaks vatican" "Vladimir hovorí po vatikánsky"
skcard . "Jakub and Vladimir are Dutch" "Jakub a Vladimir sú Holanďani"
skcard . "Vladimir is from America" "Vladimir je z Ameriky"
skcard . "I see Luxembourg" "ja vidím Luxembursko"
skcard . "Vladimir is a Bosnian" "Vladimir je Bosniak"
skcard . "I have a french shop" "ja mám francúzsky obchod"
skcard . "Vladimir reads latvian" "Vladimir číta po lotyšsky"
skcard . "Jakub and Vladimir are Herzegovinians" "Jakub a Vladimir sú Hercegovineci"
skcard . "Vladimir is from Slovenia" "Vladimir je zo Slovinska"
skcard . "Vladimir is a Lithuanian" "Vladimir je Litovčan"
skcard . "I have an italian book" "ja mám taliansku knihu"
skcard . "I have a mexican car" "ja mám mexické auto"
skcard . "Herzegovina is nice" "Hercegovina je pekná"
skcard . "Vladimir is from Norway" "Vladimir je z Nórska"
skcard . "Bosnia is nice" "Bosna je pekná"
skcard . "Sofia and Natália are Czechs" "Sofia a Natália sú Češky"
skcard . "Vladimir speaks english" "Vladimir hovorí po anglicky"
skcard . "Natália is a Scot" "Natália je Škótka"
skcard . "I see Great Britain" "ja vidím Veľkú Britániu"
skcard . "I have a latvian book" "ja mám lotyšskú knihu"
skcard . "Natália is Dutch" "Natália je Holanďanka"
skcard . "Vladimir knows mexican" "Vladimir vie po mexicky"
skcard . "Vladimir speaks ukranian" "Vladimir hovorí po ukrajinsky"
skcard . "France is nice" "Francúzsko je pekné"
skcard . "Vladimir reads croatian" "Vladimir číta po chorvátsky"
skcard . "I see Poland" "ja vidím Poľsko"
skcard . "Vladimir reads greek" "Vladimir číta po grécky"
skcard . "I have a vatican car" "ja mám vatikánske auto"
skcard . "Natália is a Spaniard" "Natália je Španielka"
skcard . "I have a slovenian car" "ja mám slovinské auto"
skcard . "I have a english car" "ja mám anglické auto"
skcard . "I have a portugese shop" "ja mám portugalský obchod"
skcard . "I have a belgian car" "ja mám belgické auto"
skcard . "Vladimir is from Hungary" "Vladimir je z Maďarska"
skcard . "Vladimir speaks turkish" "Vladimir hovorí po turecky"
skcard . "Vladimir is from England" "Vladimir je z Anglicka"
skcard . "Vladimir reads lithuanian" "Vladimir číta po litovsky"
skcard . "I have a swedish shop" "ja mám švédsky obchod"
skcard . "I have a french book" "ja mám francúzsku knihu"
skcard . "Vladimir speaks norwegian" "Vladimir hovorí po nórsky"
skcard . "I see the Vatican" "ja vidím Vatikán"
skcard . "I have a chinese book" "ja mám čínsku knihu"
skcard . "I have a czech shop" "ja mám český obchod"
skcard . "Natália is a Greek" "Natália je Grékyňa"
skcard . "I see Herzegovina" "ja vidím Hercegovinu"
skcard . "Scotland is nice" "Škótsko je pekné"
skcard . "Vladimir is a Montenegrin" "Vladimir je Čiernohorec"
skcard . "Vladimir is a Ukranian" "Vladimir je Ukrajinec"
skcard . "I see Finland" "ja vidím Fínsko"
skcard . "Moldova is nice" "Moldavsko je pekné"
skcard . "Vladimir reads slovakian" "Vladimir číta po slovensky"
skcard . "Vladimir is from Ireland" "Vladimir je z Írska"
skcard . "Vladimir speaks scottish" "Vladimir hovorí po škótsky"
skcard . "Jakub and Vladimir are Macedonians" "Jakub a Vladimir sú Macedóneci"
skcard . "I have a russian car" "ja mám ruské auto"
skcard . "Natália is a Macedonian" "Natália je Macedónka"
skcard . "I have a macedonian book" "ja mám macedónsku knihu"
skcard . "Vladimir knows japanese" "Vladimir vie po japonsky"
skcard . "I have an austrian book" "ja mám rakúsku knihu"
skcard . "I see Hungary" "ja vidím Maďarsko"
skcard . "Natália is a Herzegovinian" "Natália je Hercegovinka"
skcard . "Vladimir is from Croatia" "Vladimir je z Chorvátska"
skcard . "Vladimir is from Montenegro" "Vladimir je z Čiernej Hory"
skcard . "Vladimir is a Hungarian" "Vladimir je Maďar"
skcard . "I have a lithuanian book" "ja mám litovskú knihu"
skcard . "Vladimir knows lithuanian" "Vladimir vie po litovsky"
skcard . "Natália is a Russian" "Natália je Ruska"
skcard . "Jakub and Vladimir are French" "Jakub a Vladimir sú Francúzi"
skcard . "Vladimir is a Macedonian" "Vladimir je Macedónec"
skcard . "Czechia is nice" "Česko je pekné"
skcard . "I have a czech book" "ja mám českú knihu"
skcard . "I have a serbian shop" "ja mám srbský obchod"
skcard . "Vladimir knows liechtensteinish" "Vladimir vie po lichtenštajnsky"
skcard . "Vladimir knows slovenian" "Vladimir vie po slovinsky"
skcard . "I see Italy" "ja vidím Taliansko"
skcard . "Norway is nice" "Nórsko je pekné"
skcard . "Vladimir speaks lithuanian" "Vladimir hovorí po litovsky"
skcard . "I have a moldavian car" "ja mám moldavské auto"
skcard . "I have a scottish car" "ja mám škótske auto"
skcard . "Austria is nice" "Rakúsko je pekné"
skcard . "I have a norwegian shop" "ja mám nórsky obchod"
skcard . "Vladimir is from France" "Vladimir je z Francúzska"
skcard . "I have an italian shop" "ja mám taliansky obchod"
skcard . "Sofia and Natália are Greeks" "Sofia a Natália sú Grékyňe"
skcard . "Jakub and Vladimir are Norwegians" "Jakub a Vladimir sú Nóri"
skcard . "Jakub and Vladimir are brits" "Jakub a Vladimir sú Briti"
skcard . "I have an austrian car" "ja mám rakúske auto"
skcard . "I see Portugal" "ja vidím Portugalsko"
skcard . "I have a lithuanian car" "ja mám litovské auto"
skcard . "Sofia and Natália are Hungarians" "Sofia a Natália sú Maďarky"
skcard . "Vladimir is an Englishman" "Vladimir je Angličan"
skcard . "I have a czech car" "ja mám české auto"
skcard . "Mexico is nice" "Mexiko je pekné"
skcard . "I see Croatia" "ja vidím Chorvátsko"
skcard . "Jakub and Vladimir are Latvians" "Jakub a Vladimir sú Lotyši"
skcard . "Sofia and Natália are Spaniards" "Sofia a Natália sú Španielky"
skcard . "Jakub and Vladimir are Montenegrins" "Jakub a Vladimir sú Čiernohoreci"
skcard . "Vladimir speaks swiss" "Vladimir hovorí po švajčiarsky"
skcard . "Vladimir knows dutch" "Vladimir vie po holandsky"
skcard . "I see Czechia" "ja vidím Česko"
skcard . "Italy is nice" "Taliansko je pekné"
skcard . "Vladimir is from China" "Vladimir je z Číny"
skcard . "England is nice" "Anglicko je pekné"
skcard . "Vladimir knows macedonian" "Vladimir vie po macedónsky"
skcard . "Vladimir is from Turkey" "Vladimir je z Turecka"
skcard . "I have a finnish car" "ja mám fínske auto"
skcard . "Liechtenstein is nice" "Lichtenštajnsko je pekné"
skcard . "Natália is a German" "Natália je Nemka"
skcard . "Vladimir speaks austrian" "Vladimir hovorí po rakúsky"
skcard . "Vladimir reads norwegian" "Vladimir číta po nórsky"
skcard . "Vladimir reads austrian" "Vladimir číta po rakúsky"
skcard . "Vladimir reads irish" "Vladimir číta po írsky"
skcard . "I have an italian car" "ja mám talianske auto"
skcard . "Jakub and Vladimir are Europeans" "Jakub a Vladimir sú Európani"
skcard . "I see Moldova" "ja vidím Moldavsko"
skcard . "I have an irish book" "ja mám írsku knihu"
skcard . "Vladimir is from Moldova" "Vladimir je z Moldavska"
skcard . "I see Estonia" "ja vidím Estónsko"
skcard . "Jakub and Vladimir are Finns" "Jakub a Vladimir sú Fíni"
skcard . "I have a dutch book" "ja mám holandskú knihu"
skcard . "I have a moldavian shop" "ja mám moldavský obchod"
skcard . "Jakub and Vladimir are Chinese" "Jakub a Vladimir sú Číňani"
skcard . "I see England" "ja vidím Anglicko"
skcard . "Vladimir reads swedish" "Vladimir číta po švédsky"
skcard . "I have a british book" "ja mám britskú knihu"
skcard . "I see Lithuania" "ja vidím Litvu"
skcard . "I have a scottish book" "ja mám škótsku knihu"
skcard . "Vladimir reads herzegovinian" "Vladimir číta po hercegovsky"
skcard . "I have a bosnian car" "ja mám bosnianske auto"
skcard . "I have a latvian shop" "ja mám lotyšský obchod"
skcard . "Jakub and Vladimir are Moldavians" "Jakub a Vladimir sú Moldavčani"
skcard . "Vladimir is from Germany" "Vladimir je z Nemecka"
skcard . "Vladimir is an Estonian" "Vladimir je Estónec"
skcard . "I have a english shop" "ja mám anglický obchod"
skcard . "I see Russia" "ja vidím Rusko"
skcard . "I have an austrian shop" "ja mám rakúsky obchod"
skcard . "I have a german book" "ja mám nemeckú knihu"
skcard . "Vladimir is from Belgium" "Vladimir je z Belgicka"
skcard . "Vladimir speaks luxembourgish" "Vladimir hovorí po luxembursky"
skcard . "Vladimir is from Great Britain" "Vladimir je z Veľkej Británie"
skcard . "Portugal is nice" "Portugalsko je pekné"
skcard . "Vladimir is a Finn" "Vladimir je Fín"
skcard . "I have a greek book" "ja mám grécku knihu"
skcard . "I have a croatian car" "ja mám chorvátske auto"
skcard . "Vladimir speaks greek" "Vladimir hovorí po grécky"
skcard . "I have an american shop" "ja mám americký obchod"
skcard . "Natália is a Slovene" "Natália je Slovinka"
skcard . "I have a ukranian car" "ja mám ukrajinské auto"
skcard . "I have a mexican shop" "ja mám mexický obchod"
skcard . "I see Mexico" "ja vidím Mexiko"
skcard . "Vladimir is a Latvian" "Vladimir je Lotyš"
skcard . "Holland is nice" "Holandsko je pekné"
skcard . "Sofia and Natália are Poles" "Sofia a Natália sú Poľky"
skcard . "Vladimir is a Spaniard" "Vladimir je Španiel"
skcard . "I have a finnish shop" "ja mám fínsky obchod"
skcard . "Vladimir is from Switzerland" "Vladimir je z Švajčiarska"
skcard . "Vladimir reads swiss" "Vladimir číta po švajčiarsky"
skcard . "I have a belarusian car" "ja mám bieloruské auto"
skcard . "Sofia and Natália are Irish" "Sofia a Natália sú Írky"
skcard . "I see China" "ja vidím Čínu"
skcard . "Natália is a Latvian" "Natália je Lotyška"
skcard . "Ireland is nice" "Írsko je pekné"
skcard . "Natália is a Liechtensteiner" "Natália je Lichtenštajnčanka"
skcard . "Sofia and Natália are Liechtensteiners" "Sofia a Natália sú Lichtenštajnčanky"
skcard . "Vladimir is from Scotland" "Vladimir je z Škótska"
skcard . "Switzerland is nice" "Švajčiarsko je pekné"
skcard . "I have a herzegovinian shop" "ja mám hercegovský obchod"
skcard . "I have a spanish book" "ja mám španielsku knihu"
skcard . "I have a vatican book" "ja mám vatikánsku knihu"
skcard . "I have a herzegovinian book" "ja mám hercegovskú knihu"
skcard . "Vladimir is Chinese" "Vladimir je Číňan"
skcard . "I have a japanese car" "ja mám japonské auto"
skcard . "I see Bosnia" "ja vidím Bosnu"
skcard . "Jakub and Vladimir are Liechtensteiners" "Jakub a Vladimir sú Lichtenštajnčani"
skcard . "Natália is a Hungarian" "Natália je Maďarka"
skcard . "Vladimir is a Liechtensteiner" "Vladimir je Lichtenštajnčan"
skcard . "Vladimir speaks hungarian" "Vladimir hovorí po maďarsky"
skcard . "Sofia and Natália are Norwegians" "Sofia a Natália sú Nórky"
skcard . "Vladimir is a Pole" "Vladimir je Poliak"
skcard . "Great Britain is nice" "Veľká Británia je pekná"
skcard . "I have a macedonian shop" "ja mám macedónsky obchod"
skcard . "Natália is a Moldavian" "Natália je Moldavčanka"
skcard . "Sofia and Natália are Japanese" "Sofia a Natália sú Japonky"
skcard . "Sofia and Natália are Herzegovinians" "Sofia a Natália sú Hercegovinky"
skcard . "Vladimir speaks belarusian" "Vladimir hovorí po bielorusky"
skcard . "Sofia and Natália are Finns" "Sofia a Natália sú Fínky"
skcard . "I see America" "ja vidím Ameriku"
skcard . "Vladimir knows vatican" "Vladimir vie po vatikánsky"
skcard . "Vladimir is Japanese" "Vladimir je Japonec"
skcard . "Vladimir speaks serbian" "Vladimir hovorí po srbsky"
skcard . "Vladimir reads german" "Vladimir číta po nemecky"
skcard . "I see Montenegro" "ja vidím Čiernu Horu"
skcard . "Natália is a Portugese" "Natália je Portugalka"
skcard . "Natália is a Serb" "Natália je Srbka"
skcard . "Vladimir speaks german" "Vladimir hovorí po nemecky"
skcard . "Sweden is nice" "Švédsko je pekné"
skcard . "Vladimir speaks dutch" "Vladimir hovorí po holandsky"
skcard . "Jakub and Vladimir are Belarusians" "Jakub a Vladimir sú Bielorusi"
skcard . "Vladimir speaks italian" "Vladimir hovorí po taliansky"
skcard . "Natália is a Slovak" "Natália je Slovenka"
skcard . "Natália is a Croat" "Natália je Chorvátka"
skcard . "Vladimir reads estonian" "Vladimir číta po estónsky"
skcard . "I have a estonian car" "ja mám estónske auto"
skcard . "I have a luxembourgish shop" "ja mám luxemburský obchod"
skcard . "Vladimir is Luxemburčan" "Vladimir je Luxemburčan"
skcard . "Natália is a Swede" "Natália je Švédka"
skcard . "Vladimir is Európan" "Vladimir je Európan"
skcard . "Natália is Belarus" "Natália je Bieloruska"
skcard . "Sofia and Natália are Ukranians" "Sofia a Natália sú Ukrajinky"
skcard . "America is nice" "Amerika je pekná"
skcard . "Vladimir speaks moldavian" "Vladimir hovorí po moldavsky"
skcard . "I have a vatican shop" "ja mám vatikánsky obchod"
skcard . "I have a slovenian book" "ja mám slovinskú knihu"
skcard . "Vladimir reads portugese" "Vladimir číta po portugalsky"
skcard . "Vladimir speaks polish" "Vladimir hovorí po poľsky"
skcard . "Jakub and Vladimir are Poles" "Jakub a Vladimir sú Poliaki"
skcard . "Vladimir speaks latvian" "Vladimir hovorí po lotyšsky"
skcard . "Vladimir is a brit" "Vladimir je Brit"
skcard . "Jakub and Vladimir are Estonians" "Jakub a Vladimir sú Estóneci"
skcard . "Vladimir is from Luxembourg" "Vladimir je z Luxemburska"
skcard . "Vladimir knows chinese" "Vladimir vie po čínsky"
skcard . "I have an irish car" "ja mám írske auto"
skcard . "Vladimir knows polish" "Vladimir vie po poľsky"
skcard . "Vladimir knows hungarian" "Vladimir vie po maďarsky"
skcard . "I have a swedish book" "ja mám švédsku knihu"
skcard . "Sofia and Natália are Scots" "Sofia a Natália sú Škótky"
skcard . "Vladimir is a Slovak" "Vladimir je Slovák"
skcard . "Sofia and Natália are Macedonians" "Sofia a Natália sú Macedónky"
skcard . "Europe is nice" "Európa je pekná"
skcard . "Sofia and Natália are English" "Sofia a Natália sú Angličanky"
skcard . "Jakub and Vladimir are Irish" "Jakub a Vladimir sú Íri"
skcard . "Vladimir is an Irishman" "Vladimir je Ír"
skcard . "Vladimir is a Czech" "Vladimir je Čech"
skcard . "Jakub and Vladimir are Americans" "Jakub a Vladimir sú Američani"
skcard . "Vladimir knows croatian" "Vladimir vie po chorvátsky"
skcard . "Sofia and Natália are Chinese" "Sofia a Natália sú Číňanky"
skcard . "Jakub and Vladimir are Czechs" "Jakub a Vladimir sú Čechi"
skcard . "Jakub and Vladimir are Belgians" "Jakub a Vladimir sú Belgičani"
skcard . "Vladimir knows latvian" "Vladimir vie po lotyšsky"
skcard . "Vladimir is from Portugal" "Vladimir je z Portugalska"
skcard . "Sofia and Natália are Portugese" "Sofia a Natália sú Portugalky"
skcard . "Vladimir knows british" "Vladimir vie po britsky"
skcard . "Vladimir knows czech" "Vladimir vie po česky"
skcard . "I see Europe" "ja vidím Európu"
skcard . "I have a hungarian book" "ja mám maďarskú knihu"
skcard . "Vladimir reads french" "Vladimir číta po francúzsky"
skcard . "I have a finnish book" "ja mám fínsku knihu"
skcard . "Vladimir is a Herzegovinian" "Vladimir je Hercegovinec"
skcard . "I have a montenegrin shop" "ja mám čiernohorský obchod"
skcard . "Vladimir speaks montenegrin" "Vladimir hovorí po čiernohorsky"
skcard . "Sofia and Natália are a German" "Sofia a Natália sú Nemky"
skcard . "Vladimir is from Bosnia" "Vladimir je z Bosny"
skcard . "Natália is a Norwegian" "Natália je Nórka"
skcard . "Vladimir is from Herzegovina" "Vladimir je z Hercegoviny"
skcard . "Vladimir reads serbian" "Vladimir číta po srbsky"
skcard . "Vladimir speaks japanese" "Vladimir hovorí po japonsky"
skcard . "Vladimir is Dutch" "Vladimir je Holanďan"
skcard . "Natália is a Mexican" "Natália je Mexičanka"
skcard . "Vladimir is from Finland" "Vladimir je z Fínska"
skcard . "Vladimir reads english" "Vladimir číta po anglicky"
skcard . "Vladimir is an Austrian" "Vladimir je Rakúšan"
skcard . "Jakub and Vladimir are Japanese" "Jakub a Vladimir sú Japoneci"
skcard . "I have a slovenian shop" "ja mám slovinský obchod"
skcard . "Vladimir reads turkish" "Vladimir číta po turecky"
skcard . "Spain is nice" "Španielsko je pekné"
skcard . "Vladimir knows serbian" "Vladimir vie po srbsky"
skcard . "Vladimir knows scottish" "Vladimir vie po škótsky"
skcard . "I have a estonian shop" "ja mám estónsky obchod"
skcard . "Vladimir reads russian" "Vladimir číta po rusky"
skcard . "Croatia is nice" "Chorvátsko je pekné"
skcard . "Vladimir knows belarusian" "Vladimir vie po bielorusky"
skcard . "Vladimir speaks portugese" "Vladimir hovorí po portugalsky"
skcard . "I have a herzegovinian car" "ja mám hercegovské auto"
skcard . "Vladimir reads british" "Vladimir číta po britsky"
skcard . "Vladimir knows french" "Vladimir vie po francúzsky"
skcard . "Vladimir is from Greece" "Vladimir je z Grécka"
skcard . "Vladimir knows luxembourgish" "Vladimir vie po luxembursky"
skcard . "Natália is an American" "Natália je Američanka"
skcard . "I have a swedish car" "ja mám švédske auto"
skcard . "Vladimir is from Belarus" "Vladimir je z Bieloruska"
skcard . "I see Serbia" "ja vidím Srbsko"
skcard . "Vladimir is from Spain" "Vladimir je z Španielska"
skcard . "Sofia and Natália are Slovaks" "Sofia a Natália sú Slovenky"
skcard . "Jakub and Vladimir are Mexicans" "Jakub a Vladimir sú Mexičani"
skcard . "Lithuania is nice" "Litva je pekná"
skcard . "I have a liechtensteinish shop" "ja mám lichtenštajnský obchod"
skcard . "Vladimir speaks estonian" "Vladimir hovorí po estónsky"
skcard . "Vladimir knows bosnian" "Vladimir vie po bosniansky"
skcard . "Vladimir speaks finnish" "Vladimir hovorí po fínsky"
skcard . "I have a ukranian book" "ja mám ukrajinskú knihu"
skcard . "Sofia and Natália are Swedes" "Sofia a Natália sú Švédky"
skcard . "Vladimir speaks slovenian" "Vladimir hovorí po slovinsky"
skcard . "Sofia and Natália are French" "Sofia a Natália sú Francúzky"
skcard . "Sofia and Natália are Europeans" "Sofia a Natália sú Európanky"
skcard . "Vladimir speaks chinese" "Vladimir hovorí po čínsky"
skcard . "I see Norway" "ja vidím Nórsko"
skcard . "Natália is an Irishwoman" "Natália je Írka"
skcard . "Vladimir knows austrian" "Vladimir vie po rakúsky"
skcard . "I have a estonian book" "ja mám estónsku knihu"
skcard . "I have a moldavian book" "ja mám moldavskú knihu"
skcard . "Jakub and Vladimir are Slovenians" "Jakub a Vladimir sú Slovineci"
skcard . "I have a montenegrin car" "ja mám čiernohorské auto"
skcard . "Hungary is nice" "Maďarsko je pekné"
skcard . "I have a german shop" "ja mám nemecký obchod"
skcard . "Sofia and Natália are Serbians" "Sofia a Natália sú Srbky"
skcard . "I see France" "ja vidím Francúzsko"
skcard . "Vladimir speaks belgian" "Vladimir hovorí po belgicky"
skcard . "Vladimir is a Russian" "Vladimir je Rus"
skcard . "I have a dutch shop" "ja mám holandský obchod"
skcard . "I have a croatian book" "ja mám chorvátsku knihu"
skcard . "I see Latvia" "ja vidím Lotyšsko"
skcard . "Natália is a brit" "Natália je Britka"
skcard . "Vladimir speaks swedish" "Vladimir hovorí po švédsky"
skcard . "Latvia is nice" "Lotyšsko je pekné"
skcard . "I have a polish shop" "ja mám poľský obchod"
skcard . "Sofia and Natália are Slovenians" "Sofia a Natália sú Slovinky"
skcard . "Sofia and Natália are Bosnians" "Sofia a Natália sú Bosniačky"
skcard . "Vladimir is from Ukraine" "Vladimir je z Ukrajiny"
skcard . "I have an american car" "ja mám americké auto"
skcard . "Vladimir reads ukranian" "Vladimir číta po ukrajinsky"
skcard . "I see Scotland" "ja vidím Škótsko"
skcard . "the Vatican is nice" "Vatikán je pekný"
skcard . "I have a turkish shop" "ja mám turecký obchod"
skcard . "I have a spanish shop" "ja mám španielsky obchod"
skcard . "Serbia is nice" "Srbsko je pekné"
skcard . "Belgium is nice" "Belgicko je pekné"
skcard . "I have a belarusian shop" "ja mám bieloruský obchod"
skcard . "Jakub and Vladimir are Lithuanians" "Jakub a Vladimir sú Litovčani"
skcard . "I have a serbian car" "ja mám srbské auto"
skcard . "Vladimir knows ukranian" "Vladimir vie po ukrajinsky"
skcard . "Jakub and Vladimir are Hungarians" "Jakub a Vladimir sú Maďari"
skcard . "Vladimir speaks spanish" "Vladimir hovorí po španielsky"
skcard . "Sofia and Natália are Austrians" "Sofia a Natália sú Rakúšanky"
skcard . "I have a liechtensteinish car" "ja mám lichtenštajnské auto"
skcard . "Sofia and Natália are Croatians" "Sofia a Natália sú Chorvátky"
skcard . "Vladimir knows montenegrin" "Vladimir vie po čiernohorsky"
skcard . "Vladimir is from Latvia" "Vladimir je z Lotyšska"
skcard . "I have a ukranian shop" "ja mám ukrajinský obchod"
skcard . "Vladimir knows greek" "Vladimir vie po grécky"
skcard . "Jakub and Vladimir are Germans" "Jakub a Vladimir sú Nemeci"
skcard . "Vladimir reads polish" "Vladimir číta po poľsky"
skcard . "I have a british car" "ja mám britské auto"
skcard . "Vladimir speaks mexican" "Vladimir hovorí po mexicky"
skcard . "I have a luxembourgish book" "ja mám luxemburskú knihu"
skcard . "Vladimir reads spanish" "Vladimir číta po španielsky"
skcard . "Vladimir reads chinese" "Vladimir číta po čínsky"
skcard . "I have a belarusian book" "ja mám bieloruskú knihu"
skcard . "I see Liechtenstein" "ja vidím Lichtenštajnsko"
skcard . "Vladimir is from the Vatican" "Vladimir je z Vatikána"
skcard . "Natália is a Bosnian" "Natália je Bosniačka"
skcard . "Vladimir reads belgian" "Vladimir číta po belgicky"
skcard . "I have a japanese book" "ja mám japonskú knihu"
skcard . "Slovenia is nice" "Slovinsko je pekné"
skcard . "Finland is nice" "Fínsko je pekné"
skcard . "Vladimir knows herzegovinian" "Vladimir vie po hercegovsky"
skcard . "I have a scottish shop" "ja mám škótsky obchod"
skcard . "Vladimir is a Scot" "Vladimir je Škót"
skcard . "I see Germany" "ja vidím Nemecko"
skcard . "Vladimir speaks macedonian" "Vladimir hovorí po macedónsky"
skcard . "Vladimir speaks british" "Vladimir hovorí po britsky"
skcard . "Vladimir knows italian" "Vladimir vie po taliansky"
skcard . "Vladimir speaks canadian" "Vladimir hovorí po kanadsky"
skcard . "I have a canadian shop" "ja mám kanadský obchod"
skcard . "Sofia and Natália are Canadians" "Sofia a Natália sú Kanaďanky"
skcard . "Vladimir is from Canada" "Vladimir je z Kanady"
skcard . "I have a canadian book" "ja mám kanadskú knihu"
skcard . "Canada is nice" "Kanada je pekná"
skcard . "Natália is a Canadian" "Natália je Kanaďanka"
skcard . "Jakub and Vladimir are Canadians" "Jakub a Vladimir sú Kanaďani"
skcard . "Vladimir is a Canadian" "Vladimir je Kanaďan"
skcard . "I have a canadian car" "ja mám kanadské auto"
skcard . "Vladimir knows canadian" "Vladimir vie po kanadsky"
skcard . "Vladimir reads canadian" "Vladimir číta po kanadsky"
skcard . "I see Canada" "ja vidím Kanadu"
