skcard . "I see a nice book" "ja vidím peknú knihu"
skcard . "that is a large castle" "ten je veľký hrad"
skcard . "I am near the last castles" "ja som pri posledných hradoch"
skcard . "I see a well-known car" "ja vidím známe auto"
skcard . "I am near new men" "ja som pri nových mužoch"
skcard . "that is a good car" "to je dobré auto"
skcard . "those are large cars" "tie sú veľké autá"
skcard . "that is a well-known car" "to je známe auto"
skcard . "I see different books" "ja vidím iné knihy"
skcard . "that is a rich man" "ten je bohatý muž"
skcard . "I am near a main man" "ja som pri hlavnom mužovi"
skcard . "I am near the different castles" "ja som pri iných hradoch"
skcard . "I see a large book" "ja vidím veľkú knihu"
skcard . "I am near the rich castles" "ja som pri bohatom hrade"
skcard . "I see tall men" "ja vidím vysokých mužov"
skcard . "I see a tall car" "ja vidím vysoké auto"
skcard . "I see the tall castles" "ja vidím vysoké hrady"
skcard . "those are well-known books" "tie sú známe knihy"
skcard . "I am near last books" "ja som pri posledných knihách"
skcard . "I see a main man" "ja vidím hlavného muža"
skcard . "I see well-known cars" "ja vidím známe autá"
skcard . "I see a last car" "ja vidím posledné auto"
skcard . "I am near a good man" "ja som pri dobrom mužovi"
skcard . "I see a good car" "ja vidím dobré auto"
skcard . "I see a different car" "ja vidím iné auto"
skcard . "I am near a main car" "ja som pri hlavnom aute"
skcard . "I am near an old book" "ja som pri starej knihe"
skcard . "I am near a large car" "ja som pri veľkom aute"
skcard . "those are different books" "tie sú iné knihy"
skcard . "those are nice men" "tí sú pekní muži"
skcard . "I am near a happy man" "ja som pri šťastnom mužovi"
skcard . "those are rich men" "tí sú bohatí muži"
skcard . "I am near the good castles" "ja som pri dobrých hradoch"
skcard . "I see difficult men" "ja vidím ťažkých mužov"
skcard . "I am near a tall car" "ja som pri vysokom aute"
skcard . "I see the old castles" "ja vidím staré hrady"
skcard . "those are different men" "tí sú iní muži"
skcard . "those are difficult men" "tí sú ťažkí muži"
skcard . "those are happy books" "tie sú šťastné knihy"
skcard . "that is an old man" "ten je starý muž"
skcard . "those are the difficult castles" "tie sú ťažké hrady"
skcard . "I see rich men" "ja vidím bohatých mužov"
skcard . "I see an old castle" "ja vidím starý hrad"
skcard . "I see good men" "ja vidím dobrých mužov"
skcard . "I am near a rich book" "ja som pri bohatej knihe"
skcard . "I see a happy man" "ja vidím šťastného muža"
skcard . "I see a well-known book" "ja vidím známu knihu"
skcard . "I see different cars" "ja vidím iné autá"
skcard . "I am near the rich castles" "ja som pri bohatých hradoch"
skcard . "those are happy cars" "tie sú šťastné autá"
skcard . "I am near a happy book" "ja som pri šťastnej knihe"
skcard . "I am near a sick car" "ja som pri chorom aute"
skcard . "that is a good castle" "ten je dobrý hrad"
skcard . "that is a new man" "ten je nový muž"
skcard . "those are difficult cars" "tie sú ťažké autá"
skcard . "that is a rich book" "tá je bohatá kniha"
skcard . "I see an old car" "ja vidím staré auto"
skcard . "I see a happy castle" "ja vidím šťastný hrad"
skcard . "I see a new castle" "ja vidím nový hrad"
skcard . "I am near an old car" "ja som pri starom aute"
skcard . "I am near the difficult castles" "ja som pri ťažkých hradoch"
skcard . "I am near the large castles" "ja som pri veľkých hradoch"
skcard . "I am near the sick castles" "ja som pri chorom hrade"
skcard . "I am near the well-known castles" "ja som pri známom hrade"
skcard . "I am near the different castles" "ja som pri inom hrade"
skcard . "I see the difficult castles" "ja vidím ťažké hrady"
skcard . "I see happy books" "ja vidím šťastné knihy"
skcard . "I am near a happy car" "ja som pri šťastnom aute"
skcard . "I am near the old castles" "ja som pri starých hradoch"
skcard . "that is a good book" "tá je dobrá kniha"
skcard . "I am near the nice castles" "ja som pri peknom hrade"
skcard . "I am near a difficult man" "ja som pri ťažkom mužovi"
skcard . "those are the different castles" "tie sú iné hrady"
skcard . "I am near the main castles" "ja som pri hlavných hradoch"
skcard . "those are main men" "tí sú hlavní muži"
skcard . "I am near the tall castles" "ja som pri vysokých hradoch"
skcard . "those are the good castles" "tie sú dobré hrady"
skcard . "I am near the new castles" "ja som pri novom hrade"
skcard . "that is a main car" "to je hlavné auto"
skcard . "I am near well-known books" "ja som pri známych knihách"
skcard . "I see tall books" "ja vidím vysoké knihy"
skcard . "I am near the difficult castles" "ja som pri ťažkom hrade"
skcard . "those are the well-known castles" "tie sú známe hrady"
skcard . "I am near nice cars" "ja som pri pekných autách"
skcard . "I see large cars" "ja vidím veľké autá"
skcard . "I see a rich castle" "ja vidím bohatý hrad"
skcard . "I see a rich book" "ja vidím bohatú knihu"
skcard . "I am near good cars" "ja som pri dobrých autách"
skcard . "those are good books" "tie sú dobré knihy"
skcard . "those are happy men" "tí sú šťastní muži"
skcard . "that is a sick car" "to je choré auto"
skcard . "I am near a different book" "ja som pri inej knihe"
skcard . "I see last men" "ja vidím posledných mužov"
skcard . "I am near sick men" "ja som pri chorých mužoch"
skcard . "that is an old book" "tá je stará kniha"
skcard . "those are rich cars" "tie sú bohaté autá"
skcard . "I see difficult cars" "ja vidím ťažké autá"
skcard . "that is a large man" "ten je veľký muž"
skcard . "those are sick books" "tie sú choré knihy"
skcard . "I see a difficult car" "ja vidím ťažké auto"
skcard . "I am near last cars" "ja som pri posledných autách"
skcard . "that is a last car" "to je posledné auto"
skcard . "that is a good man" "ten je dobrý muž"
skcard . "I am near a tall book" "ja som pri vysokej knihe"
skcard . "I see a nice man" "ja vidím pekného muža"
skcard . "I see a happy book" "ja vidím šťastnú knihu"
skcard . "I am near sick books" "ja som pri chorých knihách"
skcard . "that is a happy castle" "ten je šťastný hrad"
skcard . "I see the sick castles" "ja vidím choré hrady"
skcard . "that is a rich car" "to je bohaté auto"
skcard . "those are the tall castles" "tie sú vysoké hrady"
skcard . "I see a good castle" "ja vidím dobrý hrad"
skcard . "I am near main books" "ja som pri hlavných knihách"
skcard . "I see a different castle" "ja vidím iný hrad"
skcard . "I see a difficult man" "ja vidím ťažkého muža"
skcard . "that is a main castle" "ten je hlavný hrad"
skcard . "I am near a well-known car" "ja som pri známom aute"
skcard . "those are old books" "tie sú staré knihy"
skcard . "that is an old castle" "ten je starý hrad"
skcard . "I see a well-known man" "ja vidím známeho muža"
skcard . "I am near tall books" "ja som pri vysokých knihách"
skcard . "those are old cars" "tie sú staré autá"
skcard . "those are good men" "tí sú dobrí muži"
skcard . "I see difficult books" "ja vidím ťažké knihy"
skcard . "that is a different car" "to je iné auto"
skcard . "I am near nice books" "ja som pri pekných knihách"
skcard . "that is a well-known man" "ten je známy muž"
skcard . "I am near sick cars" "ja som pri chorých autách"
skcard . "I see large books" "ja vidím veľké knihy"
skcard . "that is a well-known book" "tá je známa kniha"
skcard . "I am near a tall man" "ja som pri vysokom mužovi"
skcard . "I am near a well-known man" "ja som pri známom mužovi"
skcard . "I see a difficult book" "ja vidím ťažkú knihu"
skcard . "I am near the good castles" "ja som pri dobrom hrade"
skcard . "I see a tall castle" "ja vidím vysoký hrad"
skcard . "I am near nice men" "ja som pri pekných mužoch"
skcard . "those are tall books" "tie sú vysoké knihy"
skcard . "that is a happy book" "tá je šťastná kniha"
skcard . "I see a difficult castle" "ja vidím ťažký hrad"
skcard . "those are sick cars" "tie sú choré autá"
skcard . "that is a difficult castle" "ten je ťažký hrad"
skcard . "that is a large car" "to je veľké auto"
skcard . "I see a new man" "ja vidím nového muža"
skcard . "I see a good book" "ja vidím dobrú knihu"
skcard . "I am near the tall castles" "ja som pri vysokom hrade"
skcard . "I am near a different man" "ja som pri inom mužovi"
skcard . "I am near rich books" "ja som pri bohatých knihách"
skcard . "I am near a nice car" "ja som pri peknom aute"
skcard . "I see new cars" "ja vidím nové autá"
skcard . "I am near a difficult car" "ja som pri ťažkom aute"
skcard . "I see a main castle" "ja vidím hlavný hrad"
skcard . "that is a last book" "tá je posledná kniha"
skcard . "I am near a well-known book" "ja som pri známej knihe"
skcard . "I am near the large castles" "ja som pri veľkom hrade"
skcard . "I see the rich castles" "ja vidím bohaté hrady"
skcard . "I see a tall book" "ja vidím vysokú knihu"
skcard . "that is a different book" "tá je iná kniha"
skcard . "I am near happy cars" "ja som pri šťastných autách"
skcard . "I see a last castle" "ja vidím posledný hrad"
skcard . "I am near tall men" "ja som pri vysokých mužoch"
skcard . "I see different men" "ja vidím iných mužov"
skcard . "I see rich books" "ja vidím bohaté knihy"
skcard . "I see a rich car" "ja vidím bohaté auto"
skcard . "I see the main castles" "ja vidím hlavné hrady"
skcard . "I see a large castle" "ja vidím veľký hrad"
skcard . "that is an old car" "to je staré auto"
skcard . "I see the well-known castles" "ja vidím známe hrady"
skcard . "those are main cars" "tie sú hlavné autá"
skcard . "I see nice books" "ja vidím pekné knihy"
skcard . "that is a difficult man" "ten je ťažký muž"
skcard . "those are new men" "tí sú noví muži"
skcard . "I see a large car" "ja vidím veľké auto"
skcard . "I am near different men" "ja som pri iných mužoch"
skcard . "I am near a different car" "ja som pri inom aute"
skcard . "I am near a main book" "ja som pri hlavnej knihe"
skcard . "I see the good castles" "ja vidím dobré hrady"
skcard . "I am near main men" "ja som pri hlavných mužoch"
skcard . "I see a sick man" "ja vidím chorého muža"
skcard . "that is a happy car" "to je šťastné auto"
skcard . "I see rich cars" "ja vidím bohaté autá"
skcard . "those are the rich castles" "tie sú bohaté hrady"
skcard . "I am near old men" "ja som pri starých mužoch"
skcard . "those are the large castles" "tie sú veľké hrady"
skcard . "I see the last castles" "ja vidím posledné hrady"
skcard . "those are tall cars" "tie sú vysoké autá"
skcard . "I see a last book" "ja vidím poslednú knihu"
skcard . "I see a different book" "ja vidím inú knihu"
skcard . "those are the happy castles" "tie sú šťastné hrady"
skcard . "I am near rich men" "ja som pri bohatých mužoch"
skcard . "I see well-known men" "ja vidím známych mužov"
skcard . "that is a different castle" "ten je iný hrad"
skcard . "I see happy cars" "ja vidím šťastné autá"
skcard . "I am near a sick book" "ja som pri chorej knihe"
skcard . "that is a tall man" "ten je vysoký muž"
skcard . "I am near old cars" "ja som pri starých autách"
skcard . "those are nice cars" "tie sú pekné autá"
skcard . "I see the different castles" "ja vidím iné hrady"
skcard . "that is a nice car" "to je pekné auto"
skcard . "I am near last men" "ja som pri posledných mužoch"
skcard . "I am near well-known cars" "ja som pri známych autách"
skcard . "I am near a new car" "ja som pri novom aute"
skcard . "those are the last castles" "tie sú posledné hrady"
skcard . "I am near a sick man" "ja som pri chorom mužovi"
skcard . "I see a nice car" "ja vidím pekné auto"
skcard . "that is a tall castle" "ten je vysoký hrad"
skcard . "I see main cars" "ja vidím hlavné autá"
skcard . "I am near a difficult book" "ja som pri ťažkej knihe"
skcard . "I see well-known books" "ja vidím známe knihy"
skcard . "that is a new castle" "ten je nový hrad"
skcard . "I am near new books" "ja som pri nových knihách"
skcard . "that is a main book" "tá je hlavná kniha"
skcard . "I am near well-known men" "ja som pri známych mužoch"
skcard . "I am near large books" "ja som pri veľkých knihách"
skcard . "I am near the sick castles" "ja som pri chorých hradoch"
skcard . "I am near the well-known castles" "ja som pri známych hradoch"
skcard . "I see a nice castle" "ja vidím pekný hrad"
skcard . "I see happy men" "ja vidím šťastných mužov"
skcard . "those are the new castles" "tie sú nové hrady"
skcard . "I am near a nice man" "ja som pri peknom mužovi"
skcard . "that is a happy man" "ten je šťastný muž"
skcard . "those are sick men" "tí sú chorí muži"
skcard . "I see a happy car" "ja vidím šťastné auto"
skcard . "that is a sick man" "ten je chorý muž"
skcard . "I am near a large man" "ja som pri veľkom mužovi"
skcard . "I am near a rich man" "ja som pri bohatom mužovi"
skcard . "those are new books" "tie sú nové knihy"
skcard . "I see a sick castle" "ja vidím chorý hrad"
skcard . "I see a sick book" "ja vidím chorú knihu"
skcard . "I am near old books" "ja som pri starých knihách"
skcard . "I am near happy men" "ja som pri šťastných mužoch"
skcard . "those are last books" "tie sú posledné knihy"
skcard . "I am near different cars" "ja som pri iných autách"
skcard . "those are nice books" "tie sú pekné knihy"
skcard . "I see large men" "ja vidím veľkých mužov"
skcard . "I am near new cars" "ja som pri nových autách"
skcard . "I am near rich cars" "ja som pri bohatých autách"
skcard . "I see a main book" "ja vidím hlavnú knihu"
skcard . "I am near good books" "ja som pri dobrých knihách"
skcard . "those are large men" "tí sú veľkí muži"
skcard . "I am near the happy castles" "ja som pri šťastných hradoch"
skcard . "I see last books" "ja vidím posledné knihy"
skcard . "I am near a last book" "ja som pri poslednej knihe"
skcard . "that is a last man" "ten je posledný muž"
skcard . "that is a difficult car" "to je ťažké auto"
skcard . "those are last men" "tí sú poslední muži"
skcard . "that is a sick book" "tá je chorá kniha"
skcard . "I am near large men" "ja som pri veľkých mužoch"
skcard . "I see nice men" "ja vidím pekných mužov"
skcard . "I see an old man" "ja vidím starého muža"
skcard . "I am near a nice book" "ja som pri peknej knihe"
skcard . "those are the nice castles" "tie sú pekné hrady"
skcard . "I see a rich man" "ja vidím bohatého muža"
skcard . "that is a new car" "to je nové auto"
skcard . "I am near difficult cars" "ja som pri ťažkých autách"
skcard . "I see a well-known castle" "ja vidím známy hrad"
skcard . "that is a sick castle" "ten je chorý hrad"
skcard . "I am near large cars" "ja som pri veľkých autách"
skcard . "that is a tall book" "tá je vysoká kniha"
skcard . "those are the sick castles" "tie sú choré hrady"
skcard . "I am near the last castles" "ja som pri poslednom hrade"
skcard . "those are the main castles" "tie sú hlavné hrady"
skcard . "I see sick cars" "ja vidím choré autá"
skcard . "I see last cars" "ja vidím posledné autá"
skcard . "I am near a large book" "ja som pri veľkej knihe"
skcard . "I see a good man" "ja vidím dobrého muža"
skcard . "I see the new castles" "ja vidím nové hrady"
skcard . "I am near different books" "ja som pri iných knihách"
skcard . "I am near difficult men" "ja som pri ťažkých mužoch"
skcard . "those are good cars" "tie sú dobré autá"
skcard . "I am near the nice castles" "ja som pri pekných hradoch"
skcard . "that is a difficult book" "tá je ťažká kniha"
skcard . "I am near the old castles" "ja som pri starom hrade"
skcard . "I see a large man" "ja vidím veľkého muža"
skcard . "I am near tall cars" "ja som pri vysokých autách"
skcard . "those are large books" "tie sú veľké knihy"
skcard . "those are new cars" "tie sú nové autá"
skcard . "I see a new car" "ja vidím nové auto"
skcard . "that is a large book" "tá je veľká kniha"
skcard . "that is a well-known castle" "ten je známy hrad"
skcard . "I see old men" "ja vidím starých mužov"
skcard . "those are old men" "tí sú starí muži"
skcard . "I see nice cars" "ja vidím pekné autá"
skcard . "I see the nice castles" "ja vidím pekné hrady"
skcard . "I am near a rich car" "ja som pri bohatom aute"
skcard . "I see main men" "ja vidím hlavných mužov"
skcard . "that is a nice book" "tá je pekná kniha"
skcard . "that is a last castle" "ten je posledný hrad"
skcard . "I am near the main castles" "ja som pri hlavnom hrade"
skcard . "I am near good men" "ja som pri dobrých mužoch"
skcard . "I see an old book" "ja vidím starú knihu"
skcard . "that is a new book" "tá je nová kniha"
skcard . "that is a nice man" "ten je pekný muž"
skcard . "I see old books" "ja vidím staré knihy"
skcard . "I see a new book" "ja vidím novú knihu"
skcard . "those are the old castles" "tie sú staré hrady"
skcard . "that is a main man" "ten je hlavný muž"
skcard . "I am near a good book" "ja som pri dobrej knihe"
skcard . "I am near main cars" "ja som pri hlavných autách"
skcard . "I see new men" "ja vidím nových mužov"
skcard . "that is a rich castle" "ten je bohatý hrad"
skcard . "I see the happy castles" "ja vidím šťastné hrady"
skcard . "I see the large castles" "ja vidím veľké hrady"
skcard . "I see good books" "ja vidím dobré knihy"
skcard . "I see old cars" "ja vidím staré autá"
skcard . "I am near the happy castles" "ja som pri šťastnom hrade"
skcard . "I see a main car" "ja vidím hlavné auto"
skcard . "that is a different man" "ten je iný muž"
skcard . "I am near a last car" "ja som pri poslednom aute"
skcard . "I am near a new book" "ja som pri novej knihe"
skcard . "I see a tall man" "ja vidím vysokého muža"
skcard . "I see sick men" "ja vidím chorých mužov"
skcard . "I see new books" "ja vidím nové knihy"
skcard . "those are last cars" "tie sú posledné autá"
skcard . "I see sick books" "ja vidím choré knihy"
skcard . "I am near happy books" "ja som pri šťastných knihách"
skcard . "I see a last man" "ja vidím posledného muža"
skcard . "I see main books" "ja vidím hlavné knihy"
skcard . "I see tall cars" "ja vidím vysoké autá"
skcard . "I am near a last man" "ja som pri poslednom mužovi"
skcard . "that is a tall car" "to je vysoké auto"
skcard . "I am near a new man" "ja som pri novom mužovi"
skcard . "those are main books" "tie sú hlavné knihy"
skcard . "those are rich books" "tie sú bohaté knihy"
skcard . "I see a sick car" "ja vidím choré auto"
skcard . "I see good cars" "ja vidím dobré autá"
skcard . "I am near the new castles" "ja som pri nových hradoch"
skcard . "those are difficult books" "tie sú ťažké knihy"
skcard . "those are different cars" "tie sú iné autá"
skcard . "that is a nice castle" "ten je pekný hrad"
skcard . "I am near difficult books" "ja som pri ťažkých knihách"
skcard . "I see a different man" "ja vidím iného muža"
skcard . "I am near a good car" "ja som pri dobrom aute"
skcard . "I am near an old man" "ja som pri starom mužovi"
skcard . "those are tall men" "tí sú vysokí muži"
skcard . "those are well-known men" "tí sú známi muži"
skcard . "those are well-known cars" "tie sú známe autá"
