#skcard . "they are near the family" "oni sú pri rodine"
#skcard . "we are near winter" "my sme pri zime"
#skcard . "they are near the schools" "ony sú pri školách"
#skcard . "Peter and you are near the fathers" "Peter a ty ste pri otcoch"
#skcard . "y'all are in the autumns" "vy ste v jeseniach"
#skcard . "y'all are in the fellow " "vy ste v chlapovi"
#skcard . "Peter is in the mothers" "Peter je v matkách"
#skcard . "she is near the woman" "ona je pri žene"
#skcard . "Igor and Peter are near the jobs" "Igor a Peter sú pri prácach"
#skcard . "they are in the family" "ony sú v rodine"
#skcard . "he is near the fellow " "on je pri chlapovi"
#skcard . "you are in the family" "ty si v rodine"
#skcard . "they are in a job" "oni sú v práci"
#skcard . "they are in the schools" "ony sú v školách"
#skcard . "I am in the jobs" "ja som v prácach"
#skcard . "we are near a friend" "my sme pri priateľovi"
#skcard . "Peter and you are near the team" "Peter a ty ste pri družstve"
#skcard . "Peter and you are in the schools" "Peter a ty ste v školách"
#skcard . "Peter and I are in school" "Peter a ja sme v škole"
#skcard . "they are near the towns" "ony sú pri mestách"
#skcard . "Peter and you are near the streets" "Peter a ty ste pri uliciach"
#skcard . "I am near the family" "ja som pri rodine"
#skcard . "you are near a friend" "ty si pri priateľovi"
#skcard . "he is near the fellows " "on je pri chlapoch"
#skcard . "Peter is near families" "Peter je pri rodinách"
#skcard . "they are near autumn" "oni sú pri jeseni"
#skcard . "you are near the town" "ty si pri meste"
#skcard . "we are near the summer " "my sme pri lete"
#skcard . "you are in the summer " "ty si v lete"
#skcard . "y'all are in the team" "vy ste v družstve"
#skcard . "Peter is in the schools" "Peter je v školách"
#skcard . "Peter is in winter" "Peter je v zime"
#skcard . "they are near the teams" "ony sú pri družstvách"
#skcard . "Igor is near the teams" "Igor je pri družstvách"
#skcard . "they are near the fathers" "oni sú pri otcoch"
#skcard . "they are in winter" "ony sú v zime"
#skcard . "y'all are in autumn" "vy ste v jeseni"
#skcard . "they are near a friend" "oni sú pri priateľovi"
#skcard . "they are near the fellow " "oni sú pri chlapovi"
#skcard . "we are in the family" "my sme v rodine"
#skcard . "I am near the summer " "ja som pri lete"
#skcard . "they are in the women" "ony sú v ženách"
#skcard . "Peter is near winter" "Peter je pri zime"
#skcard . "y'all are near have" "vy ste pri matke"
#skcard . "Igor and Peter are near the fellow " "Igor a Peter sú pri chlapovi"
#skcard . "Peter and you are in the teams" "Peter a ty ste v družstvách"
#skcard . "Peter and I are in the town" "Peter a ja sme v meste"
#skcard . "we are in the streets" "my sme v uliciach"
#skcard . "he is in the woman" "on je v žene"
#skcard . "she is near the street" "ona je pri ulici"
#skcard . "Peter and you are near the fellow " "Peter a ty ste pri chlapovi"
#skcard . "Peter and I are in the woman" "Peter a ja sme v žene"
#skcard . "they are near the autumns" "oni sú pri jeseniach"
#skcard . "Peter and I are near the street" "Peter a ja sme pri ulici"
#skcard . "they are in the team" "ony sú v družstve"
#skcard . "Igor and Peter are in the team" "Igor a Peter sú v družstve"
#skcard . "Peter and I are near the teams" "Peter a ja sme pri družstvách"
#skcard . "you are in winter" "ty si v zime"
#skcard . "they are in friends" "oni sú v priateľoch"
#skcard . "y'all are near the fathers" "vy ste pri otcoch"
#skcard . "we are in father" "my sme v otcovi"
#skcard . "you are in father" "ty si v otcovi"
#skcard . "they are in the autumns" "ony sú v jeseniach"
#skcard . "Peter is in the streets" "Peter je v uliciach"
#skcard . "we are near the family" "my sme pri rodine"
#skcard . "y'all are near the autumns" "vy ste pri jeseniach"
#skcard . "Peter and I are near the family" "Peter a ja sme pri rodine"
#skcard . "I am near the town" "ja som pri meste"
#skcard . "we are in winters" "my sme v zimách"
#skcard . "y'all are in father" "vy ste v otcovi"
#skcard . "they are near a job" "ony sú pri práci"
#skcard . "they are in the town" "ony sú v meste"
#skcard . "he is in the streets" "on je v uliciach"
#skcard . "they are near the woman" "oni sú pri žene"
#skcard . "she is in the town" "ona je v meste"
#skcard . "we are in the town" "my sme v meste"
#skcard . "he is near the team" "on je pri družstve"
#skcard . "we are in the teams" "my sme v družstvách"
#skcard . "he is in the summer " "on je v lete"
#skcard . "Peter and you are near the fellows " "Peter a ty ste pri chlapoch"
#skcard . "he is near the woman" "on je pri žene"
#skcard . "I am near summers " "ja som pri letách"
#skcard . "you are in families" "ty si v rodinách"
#skcard . "they are in winter" "oni sú v zime"
#skcard . "she is near father" "ona je pri otcovi"
#skcard . "she is in the fellows " "ona je v chlapoch"
#skcard . "y'all are in the family" "vy ste v rodine"
#skcard . "Peter is near the streets" "Peter je pri uliciach"
#skcard . "Igor is in the fathers" "Igor je v otcoch"
#skcard . "we are in the team" "my sme v družstve"
#skcard . "Igor is in a job" "Igor je v práci"
#skcard . "y'all are near the woman" "vy ste pri žene"
#skcard . "they are near summers " "oni sú pri letách"
#skcard . "Peter and I are in summers " "Peter a ja sme v letách"
#skcard . "he is in the autumns" "on je v jeseniach"
#skcard . "Igor and Peter are near the schools" "Igor a Peter sú pri školách"
#skcard . "she is in a job" "ona je v práci"
#skcard . "you are near the schools" "ty si pri školách"
#skcard . "she is in the woman" "ona je v žene"
#skcard . "she is near the fathers" "ona je pri otcoch"
#skcard . "y'all are in friends" "vy ste v priateľoch"
#skcard . "he is in the fellow " "on je v chlapovi"
#skcard . "Igor and Peter are in the schools" "Igor a Peter sú v školách"
#skcard . "we are near the streets" "my sme pri uliciach"
#skcard . "Peter is near the jobs" "Peter je pri prácach"
#skcard . "Peter and I are near the women" "Peter a ja sme pri ženách"
#skcard . "he is in a friend" "on je v priateľovi"
#skcard . "they are near a job" "oni sú pri práci"
#skcard . "he is in the team" "on je v družstve"
#skcard . "y'all are in the mothers" "vy ste v matkách"
#skcard . "Peter and you are in the jobs" "Peter a ty ste v prácach"
#skcard . "Peter and you are in a friend" "Peter a ty ste v priateľovi"
#skcard . "we are in the street" "my sme v ulici"
#skcard . "I am near the woman" "ja som pri žene"
#skcard . "Peter and I are in families" "Peter a ja sme v rodinách"
#skcard . "Igor and Peter are near the fellows " "Igor a Peter sú pri chlapoch"
#skcard . "they are near the team" "ony sú pri družstve"
#skcard . "they are near the jobs" "oni sú pri prácach"
#skcard . "you are near the woman" "ty si pri žene"
#skcard . "Peter and you are in the towns" "Peter a ty ste v mestách"
#skcard . "she is near the women" "ona je pri ženách"
#skcard . "he is near summers " "on je pri letách"
#skcard . "she is near a job" "ona je pri práci"
#skcard . "Peter and you are near the mothers" "Peter a ty ste pri matkách"
#skcard . "y'all are near the fellow " "vy ste pri chlapovi"
#skcard . "I am near the streets" "ja som pri uliciach"
#skcard . "Igor is in the street" "Igor je v ulici"
#skcard . "I am near the fellows " "ja som pri chlapoch"
#skcard . "I am in families" "ja som v rodinách"
#skcard . "I am in the town" "ja som v meste"
#skcard . "y'all are in a friend" "vy ste v priateľovi"
#skcard . "Igor and Peter are in the jobs" "Igor a Peter sú v prácach"
#skcard . "Peter and I are in autumn" "Peter a ja sme v jeseni"
#skcard . "Peter and you are near a friend" "Peter a ty ste pri priateľovi"
#skcard . "she is near the fellow " "ona je pri chlapovi"
#skcard . "they are near winter" "ony sú pri zime"
#skcard . "Igor is near the woman" "Igor je pri žene"
#skcard . "I am near school" "ja som pri škole"
#skcard . "Igor and Peter are in the town" "Igor a Peter sú v meste"
#skcard . "Igor and Peter are near the family" "Igor a Peter sú pri rodine"
#skcard . "you are near the summer " "ty si pri lete"
#skcard . "Igor and Peter are in winters" "Igor a Peter sú v zimách"
#skcard . "Peter is in the woman" "Peter je v žene"
#skcard . "we are in the summer " "my sme v lete"
#skcard . "y'all are near a job" "vy ste pri práci"
#skcard . "Igor and Peter are near a friend" "Igor a Peter sú pri priateľovi"
#skcard . "he is in the women" "on je v ženách"
#skcard . "Peter is in the women" "Peter je v ženách"
#skcard . "Igor and Peter are near families" "Igor a Peter sú pri rodinách"
#skcard . "I am near the women" "ja som pri ženách"
#skcard . "Peter is near the mothers" "Peter je pri matkách"
#skcard . "Peter is in autumn" "Peter je v jeseni"
#skcard . "Peter and you are in autumn" "Peter a ty ste v jeseni"
#skcard . "he is in the town" "on je v meste"
#skcard . "Peter is near autumn" "Peter je pri jeseni"
#skcard . "Peter is in the towns" "Peter je v mestách"
#skcard . "Peter and I are near the fellow " "Peter a ja sme pri chlapovi"
#skcard . "Peter is in the teams" "Peter je v družstvách"
#skcard . "I am in the towns" "ja som v mestách"
#skcard . "you are near father" "ty si pri otcovi"
#skcard . "Igor is near the jobs" "Igor je pri prácach"
#skcard . "I am near autumn" "ja som pri jeseni"
#skcard . "Igor and Peter are in the fellows " "Igor a Peter sú v chlapoch"
#skcard . "I am in the woman" "ja som v žene"
#skcard . "I am in have" "ja som v matke"
#skcard . "Peter is near the towns" "Peter je pri mestách"
#skcard . "he is in winters" "on je v zimách"
#skcard . "Peter and you are in summers " "Peter a ty ste v letách"
#skcard . "she is in school" "ona je v škole"
#skcard . "Peter is in the fellows " "Peter je v chlapoch"
#skcard . "Igor is in the family" "Igor je v rodine"
#skcard . "Peter is near a job" "Peter je pri práci"
#skcard . "Igor is in autumn" "Igor je v jeseni"
#skcard . "Igor is near the mothers" "Igor je pri matkách"
#skcard . "Igor is in the towns" "Igor je v mestách"
#skcard . "Igor and Peter are in the towns" "Igor a Peter sú v mestách"
#skcard . "y'all are near school" "vy ste pri škole"
#skcard . "Peter is in the street" "Peter je v ulici"
#skcard . "he is near the towns" "on je pri mestách"
#skcard . "they are near school" "ony sú pri škole"
#skcard . "Igor and Peter are near the street" "Igor a Peter sú pri ulici"
#skcard . "he is in the street" "on je v ulici"
#skcard . "y'all are near the jobs" "vy ste pri prácach"
#skcard . "y'all are near the town" "vy ste pri meste"
#skcard . "they are in the town" "oni sú v meste"
#skcard . "she is in the fathers" "ona je v otcoch"
#skcard . "you are in the fellows " "ty si v chlapoch"
#skcard . "they are in the summer " "ony sú v lete"
#skcard . "she is near the summer " "ona je pri lete"
#skcard . "Igor is near families" "Igor je pri rodinách"
#skcard . "Peter is in the fathers" "Peter je v otcoch"
#skcard . "Peter and you are near a job" "Peter a ty ste pri práci"
#skcard . "they are near the streets" "oni sú pri uliciach"
#skcard . "they are near the jobs" "ony sú pri prácach"
#skcard . "they are near the fathers" "ony sú pri otcoch"
#skcard . "they are near winters" "oni sú pri zimách"
#skcard . "he is in the towns" "on je v mestách"
#skcard . "we are near winters" "my sme pri zimách"
#skcard . "Igor and Peter are in a job" "Igor a Peter sú v práci"
#skcard . "you are near a job" "ty si pri práci"
#skcard . "Peter and I are near the streets" "Peter a ja sme pri uliciach"
#skcard . "we are near families" "my sme pri rodinách"
#skcard . "you are in summers " "ty si v letách"
#skcard . "Peter and I are in the teams" "Peter a ja sme v družstvách"
#skcard . "Igor and Peter are near the towns" "Igor a Peter sú pri mestách"
#skcard . "Peter and I are in the fellows " "Peter a ja sme v chlapoch"
#skcard . "Igor is in summers " "Igor je v letách"
#skcard . "Igor is in the mothers" "Igor je v matkách"
#skcard . "y'all are in the towns" "vy ste v mestách"
#skcard . "Peter is in a friend" "Peter je v priateľovi"
#skcard . "Igor and Peter are near the autumns" "Igor a Peter sú pri jeseniach"
#skcard . "they are in the towns" "oni sú v mestách"
#skcard . "I am in the family" "ja som v rodine"
#skcard . "we are in the mothers" "my sme v matkách"
#skcard . "they are in a friend" "oni sú v priateľovi"
#skcard . "she is near families" "ona je pri rodinách"
#skcard . "we are in the schools" "my sme v školách"
skcard . "Peter and you are in the team" "Peter a ty ste v družstve"
#skcard . "y'all are in winters" "vy ste v zimách"
#skcard . "y'all are near the women" "vy ste pri ženách"
skcard . "y'all are near winters" "vy ste pri zimách"
skcard . "Igor is in the jobs" "Igor je v prácach"
skcard . "you are in the schools" "ty si v školách"
#skcard . "Igor is near the women" "Igor je pri ženách"
#skcard . "they are in the jobs" "oni sú v prácach"
#skcard . "they are in school" "oni sú v škole"
#skcard . "Peter is in the fellow " "Peter je v chlapovi"
#skcard . "y'all are in the streets" "vy ste v uliciach"
#skcard . "you are near the mothers" "ty si pri matkách"
#skcard . "Peter and I are in winter" "Peter a ja sme v zime"
#skcard . "y'all are near a friend" "vy ste pri priateľovi"
#skcard . "Peter and you are in the street" "Peter a ty ste v ulici"
#skcard . "she is near the mothers" "ona je pri matkách"
#skcard . "he is in autumn" "on je v jeseni"
#skcard . "we are near father" "my sme pri otcovi"
#skcard . "Igor and Peter are in the autumns" "Igor a Peter sú v jeseniach"
#skcard . "Peter and you are in the woman" "Peter a ty ste v žene"
#skcard . "y'all are in the teams" "vy ste v družstvách"
#skcard . "she is near friends" "ona je pri priateľoch"
#skcard . "Igor is in school" "Igor je v škole"
#skcard . "Peter and I are in the summer " "Peter a ja sme v lete"
#skcard . "she is in the summer " "ona je v lete"
#skcard . "I am in the fellow " "ja som v chlapovi"
#skcard . "he is near the autumns" "on je pri jeseniach"
#skcard . "they are near have" "ony sú pri matke"
#skcard . "they are near the fellows " "ony sú pri chlapoch"
#skcard . "Peter is near the fellow " "Peter je pri chlapovi"
#skcard . "they are near autumn" "ony sú pri jeseni"
#skcard . "Peter and you are in the town" "Peter a ty ste v meste"
#skcard . "Igor and Peter are in autumn" "Igor a Peter sú v jeseni"
#skcard . "they are in have" "ony sú v matke"
#skcard . "y'all are near summers " "vy ste pri letách"
#skcard . "you are in the woman" "ty si v žene"
#skcard . "they are near the street" "oni sú pri ulici"
#skcard . "Igor is near a friend" "Igor je pri priateľovi"
#skcard . "we are near autumn" "my sme pri jeseni"
#skcard . "you are in autumn" "ty si v jeseni"
#skcard . "she is near the schools" "ona je pri školách"
#skcard . "Peter and you are near school" "Peter a ty ste pri škole"
#skcard . "he is near a job" "on je pri práci"
#skcard . "Peter and you are in the fellow " "Peter a ty ste v chlapovi"
#skcard . "Peter is near the team" "Peter je pri družstve"
#skcard . "they are in winters" "oni sú v zimách"
#skcard . "Peter is in the autumns" "Peter je v jeseniach"
#skcard . "Peter and I are in friends" "Peter a ja sme v priateľoch"
#skcard . "they are in the schools" "oni sú v školách"
#skcard . "they are near the autumns" "ony sú pri jeseniach"
#skcard . "Igor is near the towns" "Igor je pri mestách"
#skcard . "they are in a job" "ony sú v práci"
#skcard . "Peter and you are near the jobs" "Peter a ty ste pri prácach"
#skcard . "y'all are near the summer " "vy ste pri lete"
#skcard . "Peter and I are near the team" "Peter a ja sme pri družstve"
#skcard . "I am in the autumns" "ja som v jeseniach"
#skcard . "Igor and Peter are in the women" "Igor a Peter sú v ženách"
#skcard . "Peter and you are near the woman" "Peter a ty ste pri žene"
#skcard . "Igor and Peter are in the family" "Igor a Peter sú v rodine"
#skcard . "they are in summers " "oni sú v letách"
#skcard . "Peter and I are near friends" "Peter a ja sme pri priateľoch"
#skcard . "y'all are near friends" "vy ste pri priateľoch"
#skcard . "Igor is in the teams" "Igor je v družstvách"
#skcard . "you are near have" "ty si pri matke"
#skcard . "you are in friends" "ty si v priateľoch"
#skcard . "I am in winters" "ja som v zimách"
#skcard . "she is near the teams" "ona je pri družstvách"
#skcard . "Peter and you are in winters" "Peter a ty ste v zimách"
#skcard . "they are in the fathers" "ony sú v otcoch"
#skcard . "he is in the fellows " "on je v chlapoch"
#skcard . "Peter is in families" "Peter je v rodinách"
#skcard . "you are near friends" "ty si pri priateľoch"
#skcard . "he is in father" "on je v otcovi"
#skcard . "y'all are in the women" "vy ste v ženách"
#skcard . "he is near the street" "on je pri ulici"
#skcard . "you are in a friend" "ty si v priateľovi"
#skcard . "Peter and you are near the towns" "Peter a ty ste pri mestách"
#skcard . "we are in summers " "my sme v letách"
#skcard . "she is near the autumns" "ona je pri jeseniach"
#skcard . "they are in the fathers" "oni sú v otcoch"
#skcard . "Peter and you are near the summer " "Peter a ty ste pri lete"
#skcard . "Igor and Peter are near have" "Igor a Peter sú pri matke"
#skcard . "we are near the street" "my sme pri ulici"
#skcard . "Peter and I are in the jobs" "Peter a ja sme v prácach"
#skcard . "Peter is in the town" "Peter je v meste"
#skcard . "she is near the jobs" "ona je pri prácach"
#skcard . "Peter is near a friend" "Peter je pri priateľovi"
#skcard . "they are in the women" "oni sú v ženách"
#skcard . "she is in autumn" "ona je v jeseni"
#skcard . "Igor is near have" "Igor je pri matke"
#skcard . "Igor and Peter are in winter" "Igor a Peter sú v zime"
#skcard . "I am in friends" "ja som v priateľoch"
#skcard . "Igor and Peter are in father" "Igor a Peter sú v otcovi"
#skcard . "Igor is in winters" "Igor je v zimách"
#skcard . "Igor and Peter are near the woman" "Igor a Peter sú pri žene"
#skcard . "Peter and you are near autumn" "Peter a ty ste pri jeseni"
#skcard . "we are near the autumns" "my sme pri jeseniach"
#skcard . "you are near autumn" "ty si pri jeseni"
#skcard . "Igor is in the town" "Igor je v meste"
#skcard . "you are near school" "ty si pri škole"
#skcard . "they are in school" "ony sú v škole"
#skcard . "we are near have" "my sme pri matke"
#skcard . "he is near have" "on je pri matke"
#skcard . "Igor is near the street" "Igor je pri ulici"
#skcard . "we are near summers " "my sme pri letách"
#skcard . "Peter and I are near a friend" "Peter a ja sme pri priateľovi"
#skcard . "they are near families" "oni sú pri rodinách"
#skcard . "Peter and you are near families" "Peter a ty ste pri rodinách"
#skcard . "he is near the fathers" "on je pri otcoch"
#skcard . "I am in the teams" "ja som v družstvách"
#skcard . "you are in the team" "ty si v družstve"
#skcard . "Peter and you are near friends" "Peter a ty ste pri priateľoch"
#skcard . "y'all are in summers " "vy ste v letách"
#skcard . "he is in have" "on je v matke"
#skcard . "Igor is in families" "Igor je v rodinách"
#skcard . "they are in the teams" "ony sú v družstvách"
#skcard . "you are in the town" "ty si v meste"
skcard . "she is in summers " "ona je v letách"
#skcard . "we are in the autumns" "my sme v jeseniach"
#skcard . "Igor and Peter are in the mothers" "Igor a Peter sú v matkách"
#skcard . "Peter is near friends" "Peter je pri priateľoch"
#skcard . "y'all are near the family" "vy ste pri rodine"
#skcard . "she is in the family" "ona je v rodine"
#skcard . "y'all are near the schools" "vy ste pri školách"
#skcard . "they are in the jobs" "ony sú v prácach"
#skcard . "y'all are near winter" "vy ste pri zime"
#skcard . "she is near autumn" "ona je pri jeseni"
#skcard . "Peter is in the summer " "Peter je v lete"
#skcard . "I am in school" "ja som v škole"
#skcard . "we are in the woman" "my sme v žene"
#skcard . "I am near the schools" "ja som pri školách"
#skcard . "Igor and Peter are in the street" "Igor a Peter sú v ulici"
#skcard . "Peter and I are near the mothers" "Peter a ja sme pri matkách"
#skcard . "he is in the family" "on je v rodine"
#skcard . "they are in the streets" "oni sú v uliciach"
#skcard . "they are near a friend" "ony sú pri priateľovi"
#skcard . "they are near the team" "oni sú pri družstve"
#skcard . "they are near the streets" "ony sú pri uliciach"
#skcard . "she is near the family" "ona je pri rodine"
#skcard . "you are in the towns" "ty si v mestách"
#skcard . "Peter and you are in families" "Peter a ty ste v rodinách"
#skcard . "they are near winters" "ony sú pri zimách"
#skcard . "I am in father" "ja som v otcovi"
#skcard . "you are near winters" "ty si pri zimách"
#skcard . "she is near winter" "ona je pri zime"
#skcard . "I am near the mothers" "ja som pri matkách"
#skcard . "she is near have" "ona je pri matke"
#skcard . "Peter and I are near the summer " "Peter a ja sme pri lete"
#skcard . "Igor and Peter are near the team" "Igor a Peter sú pri družstve"
#skcard . "I am in the women" "ja som v ženách"
#skcard . "they are in the fellow " "ony sú v chlapovi"
#skcard . "he is near the jobs" "on je pri prácach"
#skcard . "they are near the fellow " "ony sú pri chlapovi"
#skcard . "I am in a friend" "ja som v priateľovi"
#skcard . "he is near the schools" "on je pri školách"
#skcard . "they are in friends" "ony sú v priateľoch"
#skcard . "they are in father" "ony sú v otcovi"
#skcard . "Igor is in the autumns" "Igor je v jeseniach"
#skcard . "Igor and Peter are near the women" "Igor a Peter sú pri ženách"
#skcard . "I am in summers " "ja som v letách"
#skcard . "you are near the women" "ty si pri ženách"
#skcard . "she is in have" "ona je v matke"
#skcard . "he is near the streets" "on je pri uliciach"
#skcard . "Peter and I are near a job" "Peter a ja sme pri práci"
#skcard . "he is near the women" "on je pri ženách"
#skcard . "Igor is in the team" "Igor je v družstve"
#skcard . "Peter and I are near the town" "Peter a ja sme pri meste"
#skcard . "they are near the street" "ony sú pri ulici"
#skcard . "I am in the mothers" "ja som v matkách"
#skcard . "Peter and I are in the autumns" "Peter a ja sme v jeseniach"
#skcard . "you are near the teams" "ty si pri družstvách"
#skcard . "I am in the summer " "ja som v lete"
#skcard . "we are in a job" "my sme v práci"
#skcard . "Peter is near summers " "Peter je pri letách"
#skcard . "she is in the autumns" "ona je v jeseniach"
#skcard . "they are in winters" "ony sú v zimách"
#skcard . "they are in the fellows " "oni sú v chlapoch"
#skcard . "Igor and Peter are in friends" "Igor a Peter sú v priateľoch"
#skcard . "Peter and I are in have" "Peter a ja sme v matke"
#skcard . "you are near summers " "ty si pri letách"
#skcard . "Peter and you are in school" "Peter a ty ste v škole"
#skcard . "Peter and I are in winters" "Peter a ja sme v zimách"
#skcard . "she is near the fellows " "ona je pri chlapoch"
#skcard . "Igor is in the streets" "Igor je v uliciach"
#skcard . "you are in the fathers" "ty si v otcoch"
#skcard . "they are in the towns" "ony sú v mestách"
#skcard . "he is near friends" "on je pri priateľoch"
#skcard . "Peter and you are in the summer " "Peter a ty ste v lete"
#skcard . "Peter and I are in the mothers" "Peter a ja sme v matkách"
#skcard . "you are in have" "ty si v matke"
#skcard . "they are near father" "ony sú pri otcovi"
#skcard . "Igor is near summers " "Igor je pri letách"
#skcard . "Igor is near the town" "Igor je pri meste"
#skcard . "he is near the teams" "on je pri družstvách"
#skcard . "they are in families" "ony sú v rodinách"
#skcard . "Peter is in father" "Peter je v otcovi"
#skcard . "we are in a friend" "my sme v priateľovi"
#skcard . "they are near the women" "ony sú pri ženách"
#skcard . "Peter and you are near the street" "Peter a ty ste pri ulici"
#skcard . "Peter and you are near father" "Peter a ty ste pri otcovi"
#skcard . "I am near a job" "ja som pri práci"
#skcard . "Igor is near father" "Igor je pri otcovi"
#skcard . "y'all are near the teams" "vy ste pri družstvách"
#skcard . "he is in school" "on je v škole"
#skcard . "y'all are in the fathers" "vy ste v otcoch"
#skcard . "y'all are in the schools" "vy ste v školách"
#skcard . "Igor is near the summer " "Igor je pri lete"
#skcard . "we are in school" "my sme v škole"
#skcard . "I am near friends" "ja som pri priateľoch"
#skcard . "Peter and I are near the towns" "Peter a ja sme pri mestách"
#skcard . "they are near friends" "ony sú pri priateľoch"
#skcard . "you are near the fellow " "ty si pri chlapovi"
#skcard . "Peter and you are in the streets" "Peter a ty ste v uliciach"
#skcard . "Peter is in friends" "Peter je v priateľoch"
#skcard . "we are in autumn" "my sme v jeseni"
#skcard . "I am in winter" "ja som v zime"
#skcard . "they are near the family" "ony sú pri rodine"
#skcard . "she is in friends" "ona je v priateľoch"
#skcard . "Igor is in a friend" "Igor je v priateľovi"
#skcard . "Peter and I are in father" "Peter a ja sme v otcovi"
#skcard . "she is near winters" "ona je pri zimách"
#skcard . "Igor and Peter are near a job" "Igor a Peter sú pri práci"
#skcard . "I am near the autumns" "ja som pri jeseniach"
#skcard . "they are near the summer " "oni sú pri lete"
#skcard . "Igor is in the fellows " "Igor je v chlapoch"
#skcard . "we are near the fellow " "my sme pri chlapovi"
#skcard . "they are near summers " "ony sú pri letách"
#skcard . "they are near friends" "oni sú pri priateľoch"
#skcard . "Peter and I are in the fellow " "Peter a ja sme v chlapovi"
#skcard . "Peter and you are in have" "Peter a ty ste v matke"
#skcard . "Peter and you are in the fathers" "Peter a ty ste v otcoch"
#skcard . "Peter and you are near the town" "Peter a ty ste pri meste"
#skcard . "we are near the mothers" "my sme pri matkách"
#skcard . "Igor and Peter are near the streets" "Igor a Peter sú pri uliciach"
#skcard . "you are in the streets" "ty si v uliciach"
#skcard . "Igor and Peter are in school" "Igor a Peter sú v škole"
#skcard . "he is in a job" "on je v práci"
#skcard . "he is near autumn" "on je pri jeseni"
#skcard . "they are near school" "oni sú pri škole"
#skcard . "I am near the fellow " "ja som pri chlapovi"
#skcard . "Igor and Peter are in families" "Igor a Peter sú v rodinách"
#skcard . "Peter and you are near the family" "Peter a ty ste pri rodine"
#skcard . "y'all are near the team" "vy ste pri družstve"
#skcard . "Peter and you are in the fellows " "Peter a ty ste v chlapoch"
#skcard . "Igor and Peter are near father" "Igor a Peter sú pri otcovi"
#skcard . "Peter and I are near winter" "Peter a ja sme pri zime"
#skcard . "Peter is in winters" "Peter je v zimách"
#skcard . "Peter and I are near the fathers" "Peter a ja sme pri otcoch"
#skcard . "she is in winter" "ona je v zime"
#skcard . "Igor and Peter are near winters" "Igor a Peter sú pri zimách"
#skcard . "you are near families" "ty si pri rodinách"
#skcard . "he is near the town" "on je pri meste"
#skcard . "Igor is near the schools" "Igor je pri školách"
#skcard . "Peter and you are in the autumns" "Peter a ty ste v jeseniach"
#skcard . "Peter is in summers " "Peter je v letách"
#skcard . "Peter and I are near the schools" "Peter a ja sme pri školách"
#skcard . "they are near the schools" "oni sú pri školách"
#skcard . "we are in the fathers" "my sme v otcoch"
#skcard . "she is near the town" "ona je pri meste"
#skcard . "y'all are in winter" "vy ste v zime"
#skcard . "Peter is in the team" "Peter je v družstve"
#skcard . "she is in the street" "ona je v ulici"
#skcard . "they are in summers " "ony sú v letách"
#skcard . "y'all are in the town" "vy ste v meste"
#skcard . "I am in the fathers" "ja som v otcoch"
#skcard . "Igor is in the fellow " "Igor je v chlapovi"
#skcard . "they are in the autumns" "oni sú v jeseniach"
#skcard . "they are near the town" "ony sú pri meste"
#skcard . "Peter and you are near the autumns" "Peter a ty ste pri jeseniach"
#skcard . "y'all are near the street" "vy ste pri ulici"
#skcard . "we are near the women" "my sme pri ženách"
#skcard . "we are in the fellows " "my sme v chlapoch"
#skcard . "you are near the towns" "ty si pri mestách"
#skcard . "Peter is near the women" "Peter je pri ženách"
#skcard . "Igor and Peter are near friends" "Igor a Peter sú pri priateľoch"
#skcard . "Peter is near the fathers" "Peter je pri otcoch"
#skcard . "she is in a friend" "ona je v priateľovi"
#skcard . "he is near the family" "on je pri rodine"
#skcard . "Peter and you are near the teams" "Peter a ty ste pri družstvách"
#skcard . "you are near the autumns" "ty si pri jeseniach"
#skcard . "we are near the fellows " "my sme pri chlapoch"
#skcard . "you are near the team" "ty si pri družstve"
#skcard . "she is in the mothers" "ona je v matkách"
#skcard . "they are in autumn" "ony sú v jeseni"
#skcard . "y'all are in the summer " "vy ste v lete"
#skcard . "Peter is near winters" "Peter je pri zimách"
#skcard . "they are in the mothers" "ony sú v matkách"
#skcard . "they are near the mothers" "ony sú pri matkách"
#skcard . "he is near the summer " "on je pri lete"
#skcard . "we are near the teams" "my sme pri družstvách"
#skcard . "Peter and you are in the mothers" "Peter a ty ste v matkách"
#skcard . "y'all are near the fellows " "vy ste pri chlapoch"
#skcard . "Igor and Peter are near the summer " "Igor a Peter sú pri lete"
#skcard . "he is in the teams" "on je v družstvách"
#skcard . "Peter and I are near autumn" "Peter a ja sme pri jeseni"
#skcard . "she is in the team" "ona je v družstve"
#skcard . "he is near father" "on je pri otcovi"
#skcard . "Igor is near a job" "Igor je pri práci"
#skcard . "Igor is in the summer " "Igor je v lete"
#skcard . "they are near the woman" "ony sú pri žene"
#skcard . "we are in the fellow " "my sme v chlapovi"
#skcard . "Igor and Peter are near the fathers" "Igor a Peter sú pri otcoch"
#skcard . "Peter and I are near summers " "Peter a ja sme pri letách"
#skcard . "Igor is near the fellow " "Igor je pri chlapovi"
#skcard . "we are in the jobs" "my sme v prácach"
#skcard . "he is near a friend" "on je pri priateľovi"
#skcard . "they are near the teams" "oni sú pri družstvách"
#skcard . "y'all are near the towns" "vy ste pri mestách"
#skcard . "we are in have" "my sme v matke"
#skcard . "they are near have" "oni sú pri matke"
#skcard . "Igor is near winter" "Igor je pri zime"
#skcard . "Igor is in the women" "Igor je v ženách"
#skcard . "they are in the team" "oni sú v družstve"
#skcard . "Igor and Peter are near autumn" "Igor a Peter sú pri jeseni"
#skcard . "he is in the jobs" "on je v prácach"
#skcard . "they are in the teams" "oni sú v družstvách"
#skcard . "y'all are near families" "vy ste pri rodinách"
#skcard . "she is in the jobs" "ona je v prácach"
#skcard . "Peter and I are in the streets" "Peter a ja sme v uliciach"
#skcard . "you are in winters" "ty si v zimách"
#skcard . "Peter and you are near winter" "Peter a ty ste pri zime"
#skcard . "you are in the women" "ty si v ženách"
#skcard . "you are near the family" "ty si pri rodine"
#skcard . "they are near the town" "oni sú pri meste"
#skcard . "y'all are in families" "vy ste v rodinách"
#skcard . "Peter and I are near the fellows " "Peter a ja sme pri chlapoch"
#skcard . "Igor is near the team" "Igor je pri družstve"
#skcard . "Igor and Peter are near the mothers" "Igor a Peter sú pri matkách"
#skcard . "Peter and I are in the schools" "Peter a ja sme v školách"
#skcard . "Peter is in have" "Peter je v matke"
skcard . "you are in school" "ty si v škole"
#skcard . "I am near a friend" "ja som pri priateľovi"
#skcard . "y'all are in school" "vy ste v škole"
#skcard . "she is near school" "ona je pri škole"
#skcard . "Peter is near the town" "Peter je pri meste"
#skcard . "you are near the streets" "ty si pri uliciach"
#skcard . "I am near the jobs" "ja som pri prácach"
#skcard . "I am in the street" "ja som v ulici"
#skcard . "he is in the fathers" "on je v otcoch"
#skcard . "y'all are in the woman" "vy ste v žene"
#skcard . "he is in the mothers" "on je v matkách"
#skcard . "Igor is in the woman" "Igor je v žene"
#skcard . "Igor is near autumn" "Igor je pri jeseni"
#skcard . "y'all are in have" "vy ste v matke"
#skcard . "Peter is near the fellows " "Peter je pri chlapoch"
#skcard . "we are near the towns" "my sme pri mestách"
#skcard . "Igor and Peter are near winter" "Igor a Peter sú pri zime"
#skcard . "they are in the summer " "oni sú v lete"
#skcard . "y'all are near father" "vy ste pri otcovi"
#skcard . "we are in the women" "my sme v ženách"
#skcard . "they are in the family" "oni sú v rodine"
#skcard . "Peter and you are in father" "Peter a ty ste v otcovi"
#skcard . "we are near friends" "my sme pri priateľoch"
#skcard . "Peter and I are in the team" "Peter a ja sme v družstve"
#skcard . "they are near the summer " "ony sú pri lete"
#skcard . "she is in the fellow " "ona je v chlapovi"
#skcard . "Igor is near the fathers" "Igor je pri otcoch"
#skcard . "you are near the fellows " "ty si pri chlapoch"
#skcard . "Peter is near school" "Peter je pri škole"
#skcard . "Igor and Peter are in have" "Igor a Peter sú v matke"
#skcard . "we are near the schools" "my sme pri školách"
#skcard . "Igor is near school" "Igor je pri škole"
#skcard . "Peter and I are in the street" "Peter a ja sme v ulici"
#skcard . "Igor and Peter are in the summer " "Igor a Peter sú v lete"
#skcard . "Peter is in the jobs" "Peter je v prácach"
#skcard . "she is in winters" "ona je v zimách"
#skcard . "Peter is near the teams" "Peter je pri družstvách"
#skcard . "they are in have" "oni sú v matke"
#skcard . "they are in the mothers" "oni sú v matkách"
#skcard . "we are in friends" "my sme v priateľoch"
#skcard . "she is near summers " "ona je pri letách"
#skcard . "Peter and I are near the autumns" "Peter a ja sme pri jeseniach"
#skcard . "Peter and you are near winters" "Peter a ty ste pri zimách"
#skcard . "Peter is near father" "Peter je pri otcovi"
#skcard . "Igor is in have" "Igor je v matke"
#skcard . "he is in the schools" "on je v školách"
#skcard . "Igor is in father" "Igor je v otcovi"
#skcard . "Igor and Peter are in the streets" "Igor a Peter sú v uliciach"
#skcard . "Igor and Peter are in the fellow " "Igor a Peter sú v chlapovi"
#skcard . "I am in the fellows " "ja som v chlapoch"
#skcard . "they are in a friend" "ony sú v priateľovi"
#skcard . "Peter is near the family" "Peter je pri rodine"
#skcard . "Igor and Peter are near school" "Igor a Peter sú pri škole"
#skcard . "we are near the town" "my sme pri meste"
#skcard . "I am in a job" "ja som v práci"
#skcard . "Peter and you are in the family" "Peter a ty ste v rodine"
#skcard . "Peter and you are in the women" "Peter a ty ste v ženách"
#skcard . "she is near the streets" "ona je pri uliciach"
#skcard . "we are in the towns" "my sme v mestách"
#skcard . "Peter is near the schools" "Peter je pri školách"
#skcard . "they are in father" "oni sú v otcovi"
#skcard . "they are in families" "oni sú v rodinách"
#skcard . "she is in the women" "ona je v ženách"
#skcard . "we are near school" "my sme pri škole"
#skcard . "Peter and I are near father" "Peter a ja sme pri otcovi"
#skcard . "y'all are in a job" "vy ste v práci"
#skcard . "y'all are near the streets" "vy ste pri uliciach"
#skcard . "Peter and you are near summers " "Peter a ty ste pri letách"
#skcard . "he is near winters" "on je pri zimách"
#skcard . "she is in the teams" "ona je v družstvách"
#skcard . "Peter and I are near have" "Peter a ja sme pri matke"
#skcard . "I am near father" "ja som pri otcovi"
#skcard . "he is near winter" "on je pri zime"
#skcard . "we are in families" "my sme v rodinách"
#skcard . "I am in autumn" "ja som v jeseni"
#skcard . "Peter and you are near have" "Peter a ty ste pri matke"
#skcard . "Peter is near the autumns" "Peter je pri jeseniach"
skcard . "I am near winters" "ja som pri zimách"
skcard . "I am near the towns" "ja som pri mestách"
skcard . "Igor is in the schools" "Igor je v školách"
skcard . "I am in the streets" "ja som v uliciach"
skcard . "I am near the street" "ja som pri ulici"
skcard . "Peter and you are in friends" "Peter a ty ste v priateľoch"
skcard . "Peter and I are in the fathers" "Peter a ja sme v otcoch"
skcard . "Peter is in the family" "Peter je v rodine"
skcard . "Peter and you are in a job" "Peter a ty ste v práci"
skcard . "Igor and Peter are near the town" "Igor a Peter sú pri meste"
skcard . "I am in the team" "ja som v družstve"
skcard . "they are near father" "oni sú pri otcovi"
skcard . "Peter and you are near the schools" "Peter a ty ste pri školách"
skcard . "Peter and you are near the women" "Peter a ty ste pri ženách"
skcard . "they are in the fellows " "ony sú v chlapoch"
skcard . "they are in the streets" "ony sú v uliciach"
skcard . "y'all are in the jobs" "vy ste v prácach"
skcard . "Peter and I are near school" "Peter a ja sme pri škole"
skcard . "Igor and Peter are in the teams" "Igor a Peter sú v družstvách"
skcard . "Igor is near friends" "Igor je pri priateľoch"
skcard . "they are near the fellows " "oni sú pri chlapoch"
skcard . "Igor is near the family" "Igor je pri rodine"
skcard . "Igor and Peter are in a friend" "Igor a Peter sú v priateľovi"
skcard . "he is near families" "on je pri rodinách"
skcard . "they are in autumn" "oni sú v jeseni"
skcard . "Peter and I are near families" "Peter a ja sme pri rodinách"
skcard . "Peter and I are in the women" "Peter a ja sme v ženách"
skcard . "they are in the fellow " "oni sú v chlapovi"
skcard . "we are near the jobs" "my sme pri prácach"
skcard . "you are in the autumns" "ty si v jeseniach"
skcard . "she is in father" "ona je v otcovi"
skcard . "she is in the schools" "ona je v školách"
skcard . "he is near school" "on je pri škole"
skcard . "he is in summers " "on je v letách"
skcard . "they are in the street" "oni sú v ulici"
skcard . "Peter is in school" "Peter je v škole"
skcard . "Peter is near the street" "Peter je pri ulici"
skcard . "I am near winter" "ja som pri zime"
skcard . "Peter and you are in winter" "Peter a ty ste v zime"
skcard . "you are in a job" "ty si v práci"
skcard . "Igor is near winters" "Igor je pri zimách"
skcard . "Peter and I are in the family" "Peter a ja sme v rodine"
skcard . "we are near the fathers" "my sme pri otcoch"
skcard . "Igor is in friends" "Igor je v priateľoch"
skcard . "you are in the jobs" "ty si v prácach"
skcard . "they are near families" "ony sú pri rodinách"
skcard . "y'all are near autumn" "vy ste pri jeseni"
skcard . "he is in friends" "on je v priateľoch"
skcard . "she is near the towns" "ona je pri mestách"
skcard . "Igor and Peter are in summers " "Igor a Peter sú v letách"
skcard . "Peter and I are in a job" "Peter a ja sme v práci"
skcard . "I am in the schools" "ja som v školách"
skcard . "Igor and Peter are in the fathers" "Igor a Peter sú v otcoch"
skcard . "Igor and Peter are in the woman" "Igor a Peter sú v žene"
skcard . "we are in winter" "my sme v zime"
skcard . "you are near the street" "ty si pri ulici"
skcard . "Igor is near the autumns" "Igor je pri jeseniach"
skcard . "you are in the teams" "ty si v družstvách"
skcard . "y'all are in the fellows " "vy ste v chlapoch"
skcard . "you are near the jobs" "ty si pri prácach"
skcard . "you are in the street" "ty si v ulici"
skcard . "she is in the towns" "ona je v mestách"
skcard . "Igor and Peter are near summers " "Igor a Peter sú pri letách"
skcard . "I am near the fathers" "ja som pri otcoch"
skcard . "they are near winter" "oni sú pri zime"
skcard . "she is near a friend" "ona je pri priateľovi"
skcard . "I am near have" "ja som pri matke"
skcard . "you are in the fellow " "ty si v chlapovi"
skcard . "he is near the mothers" "on je pri matkách"
skcard . "Igor is in winter" "Igor je v zime"
skcard . "Peter is in a job" "Peter je v práci"
skcard . "they are in the street" "ony sú v ulici"
skcard . "I am near families" "ja som pri rodinách"
skcard . "we are near a job" "my sme pri práci"
skcard . "y'all are in the street" "vy ste v ulici"
skcard . "she is near the team" "ona je pri družstve"
skcard . "she is in families" "ona je v rodinách"
skcard . "Igor and Peter are near the teams" "Igor a Peter sú pri družstvách"
skcard . "she is in the streets" "ona je v uliciach"
skcard . "you are in the mothers" "ty si v matkách"
skcard . "Peter is near the summer " "Peter je pri lete"
skcard . "Igor is near the fellows " "Igor je pri chlapoch"
skcard . "Peter and I are near the woman" "Peter a ja sme pri žene"
skcard . "we are near the woman" "my sme pri žene"
skcard . "Peter is near have" "Peter je pri matke"
skcard . "y'all are near the mothers" "vy ste pri matkách"
skcard . "Peter and I are in the towns" "Peter a ja sme v mestách"
skcard . "you are near winter" "ty si pri zime"
skcard . "I am near the teams" "ja som pri družstvách"
skcard . "they are in the woman" "ony sú v žene"
skcard . "I am near the team" "ja som pri družstve"
skcard . "Igor is near the streets" "Igor je pri uliciach"
skcard . "Peter and I are near winters" "Peter a ja sme pri zimách"
skcard . "he is in winter" "on je v zime"
skcard . "they are near the mothers" "oni sú pri matkách"
skcard . "they are near the women" "oni sú pri ženách"
skcard . "Peter and I are near the jobs" "Peter a ja sme pri prácach"
skcard . "Peter is near the woman" "Peter je pri žene"
skcard . "Peter and I are in a friend" "Peter a ja sme v priateľovi"
skcard . "we are near the team" "my sme pri družstve"
skcard . "they are near the towns" "oni sú pri mestách"
skcard . "he is in families" "on je v rodinách"
skcard . "you are near the fathers" "ty si pri otcoch"
skcard . "they are in the woman" "oni sú v žene"
skcard . "you are in springtime" "ty si v jari"
skcard . "we are in springtime" "my sme v jari"
skcard . "she is in springtime" "ona je v jari"
skcard . "y'all are in springtime" "vy ste v jari"
skcard . "they are in springtime" "oni sú v jari"
skcard . "y'all are near the springtimes" "vy ste pri jariach"
skcard . "Igor is near springtime" "Igor je pri jari"
skcard . "Igor and Peter are in springtime" "Igor a Peter sú v jari"
skcard . "Peter and I are near the springtimes" "Peter a ja sme pri jariach"
skcard . "she is near the springtimes" "ona je pri jariach"
skcard . "I am near the springtimes" "ja som pri jariach"
skcard . "he is near the springtimes" "on je pri jariach"
skcard . "I am near springtime" "ja som pri jari"
skcard . "you are in the springtimes" "ty si v jariach"
skcard . "y'all are in the springtimes" "vy ste v jariach"
skcard . "she is near springtime" "ona je pri jari"
skcard . "Peter is near the springtimes" "Peter je pri jariach"
skcard . "Peter is near springtime" "Peter je pri jari"
skcard . "Peter and I are in springtime" "Peter a ja sme v jari"
skcard . "she is in the springtimes" "ona je v jariach"
skcard . "he is in the springtimes" "on je v jariach"
skcard . "you are near springtime" "ty si pri jari"
skcard . "I am in the springtimes" "ja som v jariach"
skcard . "they are in the springtimes" "oni sú v jariach"
skcard . "Peter and I are in the springtimes" "Peter a ja sme v jariach"
skcard . "y'all are near springtime" "vy ste pri jari"
skcard . "I am in springtime" "ja som v jari"
skcard . "they are near springtime" "ony sú pri jari"
skcard . "Igor is in springtime" "Igor je v jari"
skcard . "Igor is near the springtimes" "Igor je pri jariach"
skcard . "they are near the springtimes" "oni sú pri jariach"
skcard . "Igor is in the springtimes" "Igor je v jariach"
skcard . "Peter is in the springtimes" "Peter je v jariach"
skcard . "he is in springtime" "on je v jari"
skcard . "Peter and you are near the springtimes" "Peter a ty ste pri jariach"
skcard . "Igor and Peter are in the springtimes" "Igor a Peter sú v jariach"
skcard . "they are in the springtimes" "ony sú v jariach"
skcard . "we are near the springtimes" "my sme pri jariach"
skcard . "Igor and Peter are near the springtimes" "Igor a Peter sú pri jariach"
skcard . "he is near springtime" "on je pri jari"
skcard . "they are near the springtimes" "ony sú pri jariach"
skcard . "Peter and you are in the springtimes" "Peter a ty ste v jariach"
skcard . "we are in the springtimes" "my sme v jariach"
skcard . "Peter is in springtime" "Peter je v jari"
skcard . "you are near the springtimes" "ty si pri jariach"
skcard . "Peter and you are in springtime" "Peter a ty ste v jari"
skcard . "they are in springtime" "ony sú v jari"
skcard . "Peter and you are near springtime" "Peter a ty ste pri jari"
skcard . "Peter and I are near springtime" "Peter a ja sme pri jari"
skcard . "they are near springtime" "oni sú pri jari"
skcard . "we are near springtime" "my sme pri jari"
skcard . "Igor and Peter are near springtime" "Igor a Peter sú pri jari"
