skcard . "I do not ask" "ja nežiadám"
skcard . "you are not" "ty nie si"
skcard . "Igor and Peter do not sleep" "Igor a Peter nespajú"
skcard . "Igor does not ask" "Igor nežiadá"
skcard . "Peter does not go out" "Peter nevychádza"
skcard . "Peter does not act" "Peter nekoná"
skcard . "I do not arrive" "ja neprichádzam"
skcard . "they do not arrive" "ony neprichádzajú"
skcard . "she is not" "ona nie je"
skcard . "you do not reside" "ty nebývaš"
skcard . "you and Peter do not have" "ty a Peter nemáte"
skcard . "I do not sleep" "ja nespám"
skcard . "she does not act" "ona nekoná"
skcard . "Igor and Peter do not mean" "Igor a Peter neznamenajú"
skcard . "she does not mean" "ona neznamená"
skcard . "you and Peter do not speak" "ty a Peter nerozprávate"
skcard . "Igor and Peter know not" "Igor a Peter nepoznajú"
skcard . "we do not speak" "my nerozprávame"
skcard . "I do not reside" "ja nebývam"
skcard . "Igor does not speak" "Igor nerozpráva"
skcard . "you do not begin" "ty nezačináš"
skcard . "we do not reside" "my nebývame"
skcard . "they do not speak" "oni nerozprávajú"
skcard . "you do not remember" "ty nepamätáš"
skcard . "she does not reside" "ona nebýva"
skcard . "Igor and Peter do not go out" "Igor a Peter nevychádzajú"
skcard . "y'all are not" "vy nie ste"
skcard . "Igor does not mean" "Igor neznamená"
skcard . "she does not go out" "ona nevychádza"
skcard . "she does not ask" "ona nežiadá"
skcard . "you and Peter do not arrive" "ty a Peter neprichádzate"
skcard . "he does not speak" "on nerozpráva"
skcard . "Peter does not remember" "Peter nepamätá"
skcard . "you do not mean" "ty neznamenáš"
skcard . "you do not arrive" "ty neprichádzaš"
skcard . "you do not go out" "ty nevychádzaš"
skcard . "she does not arrive" "ona neprichádza"
skcard . "y'all do not go out" "vy nevychádzate"
skcard . "Igor is not" "Igor nie je"
skcard . "y'all do not ask" "vy nežiadáte"
skcard . "you and Peter are not" "ty a Peter nie ste"
skcard . "he does not begin" "on nezačiná"
skcard . "they do not have" "ony nemajú"
skcard . "I do not begin" "ja nezačinám"
skcard . "he does not act" "on nekoná"
skcard . "y'all do not get up" "vy nevstávate"
skcard . "I do not remember" "ja nepamätám"
skcard . "they know not" "ony nepoznajú"
skcard . "we are not" "my nie sme"
skcard . "Peter does not sleep" "Peter nespá"
skcard . "I am not" "ja nie som"
skcard . "they do not remember" "ony nepamätajú"
skcard . "y'all do not have" "vy nemáte"
skcard . "Peter does not have" "Peter nemá"
skcard . "y'all do not speak" "vy nerozprávate"
skcard . "I know not" "ja nepoznám"
skcard . "Igor does not remember" "Igor nepamätá"
skcard . "he does not arrive" "on neprichádza"
skcard . "she knows not" "ona nepozná"
skcard . "he does not remember" "on nepamätá"
skcard . "Igor and Peter do not ask" "Igor a Peter nežiadajú"
skcard . "you do not get up" "ty nevstávaš"
skcard . "Igor and Peter do not reside" "Igor a Peter nebývajú"
skcard . "they do not speak" "ony nerozprávajú"
skcard . "she does not remember" "ona nepamätá"
skcard . "I do not speak" "ja nerozprávam"
skcard . "you and Peter do not mean" "ty a Peter neznamenáte"
skcard . "you know not" "ty nepoznáš"
skcard . "Igor and Peter do not have" "Igor a Peter nemajú"
skcard . "he does not go out" "on nevychádza"
skcard . "we do not arrive" "my neprichádzame"
skcard . "Peter is not" "Peter nie je"
skcard . "you do not have" "ty nemáš"
skcard . "y'all do not act" "vy nekonáte"
skcard . "he knows not" "on nepozná"
skcard . "Peter does not ask" "Peter nežiadá"
skcard . "she does not begin" "ona nezačiná"
skcard . "Peter does not speak" "Peter nerozpráva"
skcard . "they do not mean" "ony neznamenajú"
skcard . "Igor and Peter do not arrive" "Igor a Peter neprichádzajú"
skcard . "we do not have" "my nemáme"
skcard . "they are not" "ony nie sú"
skcard . "Igor does not sleep" "Igor nespá"
skcard . "you and Peter do not get up" "ty a Peter nevstávate"
skcard . "Igor does not arrive" "Igor neprichádza"
skcard . "they do not get up" "ony nevstávajú"
skcard . "you do not speak" "ty nerozprávaš"
skcard . "they do not get up" "oni nevstávajú"
skcard . "y'all do not begin" "vy nezačináte"
skcard . "he does not ask" "on nežiadá"
skcard . "they do not go out" "oni nevychádzajú"
skcard . "she does not speak" "ona nerozpráva"
skcard . "you and Peter know not" "ty a Peter nepoznáte"
skcard . "you and Peter do not act" "ty a Peter nekonáte"
skcard . "he is not" "on nie je"
skcard . "we do not go out" "my nevychádzame"
skcard . "we do not remember" "my nepamätáme"
skcard . "y'all do not mean" "vy neznamenáte"
skcard . "they know not" "oni nepoznajú"
skcard . "y'all do not reside" "vy nebývate"
skcard . "they do not sleep" "oni nespajú"
skcard . "Igor and Peter do not remember" "Igor a Peter nepamätajú"
skcard . "y'all know not" "vy nepoznáte"
skcard . "they do not go out" "ony nevychádzajú"
skcard . "Igor and Peter do not act" "Igor a Peter nekonajú"
skcard . "he does not sleep" "on nespá"
skcard . "I do not get up" "ja nevstávam"
skcard . "Igor does not have" "Igor nemá"
skcard . "Igor does not begin" "Igor nezačiná"
skcard . "y'all do not sleep" "vy nespáte"
skcard . "Peter does not begin" "Peter nezačiná"
skcard . "we know not" "my nepoznáme"
skcard . "you and Peter do not go out" "ty a Peter nevychádzate"
skcard . "you do not ask" "ty nežiadáš"
skcard . "you and Peter do not remember" "ty a Peter nepamätáte"
skcard . "they do not sleep" "ony nespajú"
skcard . "he does not mean" "on neznamená"
skcard . "they are not" "oni nie sú"
skcard . "they do not reside" "oni nebývajú"
skcard . "Igor and Peter do not get up" "Igor a Peter nevstávajú"
skcard . "they do not ask" "oni nežiadajú"
skcard . "you and Peter do not ask" "ty a Peter nežiadáte"
skcard . "they do not begin" "ony nezačinajú"
skcard . "Igor and Peter do not speak" "Igor a Peter nerozprávajú"
skcard . "they do not act" "oni nekonajú"
skcard . "you and Peter do not begin" "ty a Peter nezačináte"
skcard . "I do not mean" "ja neznamenám"
skcard . "she does not sleep" "ona nespá"
skcard . "Peter does not mean" "Peter neznamená"
skcard . "they do not begin" "oni nezačinajú"
skcard . "we do not ask" "my nežiadáme"
skcard . "you do not sleep" "ty nespáš"
skcard . "they do not remember" "oni nepamätajú"
skcard . "they do not reside" "ony nebývajú"
skcard . "Igor does not reside" "Igor nebýva"
skcard . "Peter does not get up" "Peter nevstáva"
skcard . "Igor does not get up" "Igor nevstáva"
skcard . "they do not ask" "ony nežiadajú"
skcard . "y'all do not arrive" "vy neprichádzate"
skcard . "she does not have" "ona nemá"
skcard . "I do not go out" "ja nevychádzam"
skcard . "Peter does not reside" "Peter nebýva"
skcard . "you and Peter do not reside" "ty a Peter nebývate"
skcard . "he does not get up" "on nevstáva"
skcard . "they do not mean" "oni neznamenajú"
skcard . "he does not reside" "on nebýva"
skcard . "he does not have" "on nemá"
skcard . "we do not mean" "my neznamenáme"
skcard . "they do not act" "ony nekonajú"
skcard . "Igor knows not" "Igor nepozná"
skcard . "you do not act" "ty nekonáš"
skcard . "y'all do not remember" "vy nepamätáte"
skcard . "Igor and Peter are not" "Igor a Peter nie sú"
skcard . "Peter does not arrive" "Peter neprichádza"
skcard . "I do not have" "ja nemám"
skcard . "they do not have" "oni nemajú"
skcard . "we do not get up" "my nevstávame"
skcard . "Igor and Peter do not begin" "Igor a Peter nezačinajú"
skcard . "Igor does not go out" "Igor nevychádza"
skcard . "Peter knows not" "Peter nepozná"
skcard . "we do not begin" "my nezačináme"
skcard . "they do not arrive" "oni neprichádzajú"
skcard . "I do not act" "ja nekonám"
skcard . "we do not act" "my nekonáme"
skcard . "we do not sleep" "my nespáme"
skcard . "she does not get up" "ona nevstáva"
skcard . "you and Peter do not sleep" "ty a Peter nespáte"
skcard . "Igor does not act" "Igor nekoná"
skcard . "Peter acts" "Peter koná"
skcard . "she remembers" "ona pamätá"
skcard . "Peter goes out" "Peter vychádza"
skcard . "you and Peter begin" "ty a Peter začináte"
skcard . "I begin" "ja začinám"
skcard . "you go out" "ty vychádzaš"
skcard . "you begin" "ty začináš"
skcard . "I speak" "ja rozprávam"
skcard . "she knows" "ona pozná"
skcard . "you and Peter have" "ty a Peter máte"
skcard . "y'all reside" "vy bývate"
skcard . "Igor and Peter begin" "Igor a Peter začinajú"
skcard . "you and Peter reside" "ty a Peter bývate"
skcard . "you and Peter ask" "ty a Peter žiadáte"
skcard . "you and Peter sleep" "ty a Peter spáte"
skcard . "I know" "ja poznám"
skcard . "we speak" "my rozprávame"
skcard . "you remember" "ty pamätáš"
skcard . "Peter gets up" "Peter vstáva"
skcard . "you sleep" "ty spáš"
skcard . "Igor and Peter act" "Igor a Peter konajú"
skcard . "Igor goes out" "Igor vychádza"
skcard . "you ask" "ty žiadáš"
skcard . "Igor and Peter remember" "Igor a Peter pamätajú"
skcard . "she means" "ona znamená"
skcard . "you and Peter arrive" "ty a Peter prichádzate"
skcard . "he sleeps" "on spá"
skcard . "they mean" "oni znamenajú"
skcard . "they act" "oni konajú"
skcard . "Igor has" "Igor má"
skcard . "they get up" "ony vstávajú"
skcard . "Igor asks" "Igor žiadá"
skcard . "Peter begins" "Peter začiná"
skcard . "they are" "ony sú"
skcard . "they know" "oni poznajú"
skcard . "she speaks" "ona rozpráva"
skcard . "we remember" "my pamätáme"
skcard . "Igor and Peter reside" "Igor a Peter bývajú"
skcard . "Peter resides" "Peter býva"
skcard . "Igor and Peter have" "Igor a Peter majú"
skcard . "he means" "on znamená"
skcard . "Igor and Peter arrive" "Igor a Peter prichádzajú"
skcard . "we arrive" "my prichádzame"
skcard . "y'all sleep" "vy spáte"
skcard . "Peter is" "Peter je"
skcard . "he resides" "on býva"
skcard . "you arrive" "ty prichádzaš"
skcard . "they have" "ony majú"
skcard . "Igor and Peter know" "Igor a Peter poznajú"
skcard . "she sleeps" "ona spá"
skcard . "they get up" "oni vstávajú"
skcard . "we go out" "my vychádzame"
skcard . "he asks" "on žiadá"
skcard . "y'all mean" "vy znamenáte"
skcard . "Igor and Peter get up" "Igor a Peter vstávajú"
skcard . "they sleep" "ony spajú"
skcard . "they begin" "ony začinajú"
skcard . "he has" "on má"
skcard . "I sleep" "ja spám"
skcard . "they mean" "ony znamenajú"
skcard . "you and Peter go out" "ty a Peter vychádzate"
skcard . "they reside" "ony bývajú"
skcard . "you and Peter get up" "ty a Peter vstávate"
skcard . "Peter has" "Peter má"
skcard . "you and Peter act" "ty a Peter konáte"
skcard . "they begin" "oni začinajú"
skcard . "he goes out" "on vychádza"
skcard . "you know" "ty poznáš"
skcard . "Igor and Peter sleep" "Igor a Peter spajú"
skcard . "they speak" "oni rozprávajú"
skcard . "she has" "ona má"
skcard . "Igor means" "Igor znamená"
skcard . "Igor resides" "Igor býva"
skcard . "I am" "ja som"
skcard . "I get up" "ja vstávam"
skcard . "they have" "oni majú"
skcard . "we reside" "my bývame"
skcard . "we get up" "my vstávame"
skcard . "he knows" "on pozná"
skcard . "he gets up" "on vstáva"
skcard . "they go out" "ony vychádzajú"
skcard . "Igor is" "Igor je"
skcard . "I ask" "ja žiadám"
skcard . "you reside" "ty bývaš"
skcard . "he remembers" "on pamätá"
skcard . "I reside" "ja bývam"
skcard . "Igor and Peter are" "Igor a Peter sú"
skcard . "they go out" "oni vychádzajú"
skcard . "they act" "ony konajú"
skcard . "they speak" "ony rozprávajú"
skcard . "we know" "my poznáme"
skcard . "Peter arrives" "Peter prichádza"
skcard . "he arrives" "on prichádza"
skcard . "they remember" "ony pamätajú"
skcard . "Peter knows" "Peter pozná"
skcard . "they sleep" "oni spajú"
skcard . "y'all begin" "vy začináte"
skcard . "she gets up" "ona vstáva"
skcard . "they ask" "oni žiadajú"
skcard . "I mean" "ja znamenám"
skcard . "Igor sleeps" "Igor spá"
skcard . "you mean" "ty znamenáš"
skcard . "he is" "on je"
skcard . "Igor begins" "Igor začiná"
skcard . "Peter remembers" "Peter pamätá"
skcard . "y'all arrive" "vy prichádzate"
skcard . "y'all act" "vy konáte"
skcard . "I remember" "ja pamätám"
skcard . "we act" "my konáme"
skcard . "they reside" "oni bývajú"
skcard . "Igor arrives" "Igor prichádza"
skcard . "you act" "ty konáš"
skcard . "we are" "my sme"
skcard . "Peter sleeps" "Peter spá"
skcard . "I go out" "ja vychádzam"
skcard . "she is" "ona je"
skcard . "you and Peter are" "ty a Peter ste"
skcard . "Igor and Peter ask" "Igor a Peter žiadajú"
skcard . "we have" "my máme"
skcard . "she begins" "ona začiná"
skcard . "I have" "ja mám"
skcard . "they arrive" "oni prichádzajú"
skcard . "we sleep" "my spáme"
skcard . "Igor gets up" "Igor vstáva"
skcard . "Igor remembers" "Igor pamätá"
skcard . "y'all know" "vy poznáte"
skcard . "Igor knows" "Igor pozná"
skcard . "I act" "ja konám"
skcard . "you are" "ty si"
skcard . "we mean" "my znamenáme"
skcard . "Igor and Peter go out" "Igor a Peter vychádzajú"
skcard . "you speak" "ty rozprávaš"
skcard . "y'all remember" "vy pamätáte"
skcard . "Peter asks" "Peter žiadá"
skcard . "you and Peter speak" "ty a Peter rozprávate"
skcard . "they are" "oni sú"
skcard . "Peter means" "Peter znamená"
skcard . "you and Peter know" "ty a Peter poznáte"
skcard . "Igor speaks" "Igor rozpráva"
skcard . "y'all are" "vy ste"
skcard . "she resides" "ona býva"
skcard . "y'all have" "vy máte"
skcard . "y'all speak" "vy rozprávate"
skcard . "Igor and Peter mean" "Igor a Peter znamenajú"
skcard . "she arrives" "ona prichádza"
skcard . "y'all get up" "vy vstávate"
skcard . "y'all go out" "vy vychádzate"
skcard . "you have" "ty máš"
skcard . "we ask" "my žiadáme"
skcard . "he begins" "on začiná"
skcard . "Igor acts" "Igor koná"
skcard . "he acts" "on koná"
skcard . "they remember" "oni pamätajú"
skcard . "they arrive" "ony prichádzajú"
skcard . "Igor and Peter speak" "Igor a Peter rozprávajú"
skcard . "you and Peter remember" "ty a Peter pamätáte"
skcard . "you get up" "ty vstávaš"
skcard . "they know" "ony poznajú"
skcard . "they ask" "ony žiadajú"
skcard . "I arrive" "ja prichádzam"
skcard . "she goes out" "ona vychádza"
skcard . "you and Peter mean" "ty a Peter znamenáte"
skcard . "she asks" "ona žiadá"
skcard . "y'all ask" "vy žiadáte"
skcard . "she acts" "ona koná"
skcard . "Peter speaks" "Peter rozpráva"
skcard . "he speaks" "on rozpráva"
skcard . "we begin" "my začináme"
skcard . "Peter and I do not act" "Peter a ja nekonáme"
skcard . "Peter and I do not go out" "Peter a ja nevychádzame"
skcard . "Peter and I do not sleep" "Peter a ja nespáme"
skcard . "Peter and I do not reside" "Peter a ja nebývame"
skcard . "Peter and I do not get up" "Peter a ja nevstávame"
skcard . "Peter and I do not remember" "Peter a ja nepamätáme"
skcard . "Peter and I know not" "Peter a ja nepoznáme"
skcard . "Peter and I do not ask" "Peter a ja nežiadáme"
skcard . "Peter and I do not have" "Peter a ja nemáme"
skcard . "Peter and I do not speak" "Peter a ja nerozprávame"
skcard . "Peter and I do not mean" "Peter a ja neznamenáme"
skcard . "Peter and I do not arrive" "Peter a ja neprichádzame"
skcard . "Peter and I are not" "Peter a ja nie sme"
skcard . "Peter and I do not begin" "Peter a ja nezačináme"
skcard . "Peter and I mean" "Peter a ja znamenáme"
skcard . "Peter and I have" "Peter a ja máme"
skcard . "Peter and I arrive" "Peter a ja prichádzame"
skcard . "Peter and I speak" "Peter a ja rozprávame"
skcard . "Peter and I are" "Peter a ja sme"
skcard . "Peter and I reside" "Peter a ja bývame"
skcard . "Peter and I begin" "Peter a ja začináme"
skcard . "Peter and I go out" "Peter a ja vychádzame"
skcard . "Peter and I know" "Peter a ja poznáme"
skcard . "Peter and I get up" "Peter a ja vstávame"
skcard . "Peter and I act" "Peter a ja konáme"
skcard . "Peter and I remember" "Peter a ja pamätáme"
skcard . "Peter and I sleep" "Peter a ja spáme"
skcard . "Peter and I ask" "Peter a ja žiadáme"
skcard . "you do not go" "ty nechodievaš"
skcard . "she does not go" "ona nechodieva"
skcard . "Peter and you do not go" "Peter a ty nechodievate"
skcard . "Igor does not go" "Igor nechodieva"
skcard . "they do not go" "oni nechodievajú"
skcard . "I do not go" "ja nechodievam"
skcard . "they do not go" "ony nechodievajú"
skcard . "we do not go" "my nechodievame"
skcard . "Igor and Peter do not go" "Igor a Peter nechodievajú"
skcard . "Peter and I do not go" "Peter a ja nechodievame"
skcard . "he does not go" "on nechodieva"
skcard . "y'all do not go" "vy nechodievate"
skcard . "Peter does not go" "Peter nechodieva"
skcard . "Igor goes" "Igor chodieva"
skcard . "I go" "ja chodievam"
skcard . "Igor and Peter go" "Igor a Peter chodievajú"
skcard . "Peter goes" "Peter chodieva"
skcard . "he goes" "on chodieva"
skcard . "Peter and you go" "Peter a ty chodievate"
skcard . "Peter and I go" "Peter a ja chodievame"
skcard . "we go" "my chodievame"
skcard . "you go" "ty chodievaš"
skcard . "she goes" "ona chodieva"
skcard . "they go" "ony chodievajú"
skcard . "y'all go" "vy chodievate"
skcard . "they go" "oni chodievajú"
