skcard . "The milk is not green" "mlieko nie je zelené"
skcard . "The milk is not bad" "mlieko nie je zlé"
skcard . "The milk is not clean" "mlieko nie je čisté"
skcard . "The milk is not good" "mlieko nie je dobré"
skcard . "The milk is not nice" "mlieko nie je pekné"
skcard . "The milk is not large" "mlieko nie je veľké"
skcard . "The milk is not tall" "mlieko nie je vysoké"
skcard . "The milk is not new" "mlieko nie je nové"
skcard . "The milk is not small" "mlieko nie je malé"
skcard . "The meadow is not nice" "lúka nie je pekná"
skcard . "The meadow is not small" "lúka nie je malá"
skcard . "The meadow is not green" "lúka nie je zelená"
skcard . "The meadow is not tall" "lúka nie je vysoká"
skcard . "The meadow is not clean" "lúka nie je čistá"
skcard . "The meadow is not new" "lúka nie je nová"
skcard . "The meadow is not bad" "lúka nie je zlá"
skcard . "The meadow is not good" "lúka nie je dobrá"
skcard . "The meadow is not large" "lúka nie je veľká"
skcard . "The shoulder is not small" "rameno nie je malé"
skcard . "The picture is not green" "obraz nie je zelený"
skcard . "The picture is not clean" "obraz nie je čistý"
skcard . "The eye is not tall" "oko nie je vysoké"
skcard . "The morning is not good" "ráno nie je dobré"
skcard . "The book is not good" "kniha nie je dobrá"
skcard . "The village is not green" "dedina nie je zelená"
skcard . "The horse is not clean" "kôň nie je čistý"
skcard . "The classroom is not good" "trieda nie je dobrá"
skcard . "The classroom is not large" "trieda nie je veľká"
skcard . "The evening is not green" "večer nie je zelený"
skcard . "The water is not bad" "voda nie je zlá"
skcard . "The glass is not new" "sklo nie je nové"
skcard . "The gentleman is not new" "pán nie je nový"
skcard . "The foot is not large" "noha nie je veľká"
skcard . "The shoulder is not nice" "rameno nie je pekné"
skcard . "The tree is not clean" "strom nie je čistý"
skcard . "The morning is not new" "ráno nie je nové"
skcard . "The head is not green" "hlava nie je zelená"
skcard . "The village is not new" "dedina nie je nová"
skcard . "The tree is not good" "strom nie je dobrý"
skcard . "The horse is not green" "kôň nie je zelený"
skcard . "The eye is not green" "oko nie je zelené"
skcard . "The day is not tall" "deň nie je vysoký"
skcard . "The garden is not large" "záhrada nie je veľká"
skcard . "The book is not nice" "kniha nie je pekná"
skcard . "The child is not tall" "dieťa nie je vysoké"
skcard . "The water is not good" "voda nie je dobrá"
skcard . "The school is not tall" "škola nie je vysoká"
skcard . "The eye is not small" "oko nie je malé"
skcard . "The wall is not good" "stena nie je dobrá"
skcard . "The boy is not tall" "chlapec nie je vysoký"
skcard . "The gentleman is not good" "pán nie je dobrý"
skcard . "The forehead is not small" "čelo nie je malé"
skcard . "The village is not clean" "dedina nie je čistá"
skcard . "The eye is not clean" "oko nie je čisté"
skcard . "The finger is not green" "prst nie je zelený"
skcard . "The face is not small" "tvár nie je malá"
skcard . "The street is not tall" "ulica nie je vysoká"
skcard . "The day is not small" "deň nie je malý"
skcard . "The water is not small" "voda nie je malá"
skcard . "The palm is not nice" "dlaň nie je pekná"
skcard . "The palm is not bad" "dlaň nie je zlá"
skcard . "The foot is not bad" "noha nie je zlá"
skcard . "The face is not green" "tvár nie je zelená"
skcard . "The hand is not clean" "ruka nie je čistá"
skcard . "The evening is not small" "večer nie je malý"
skcard . "The school is not green" "škola nie je zelená"
skcard . "The horse is not nice" "kôň nie je pekný"
skcard . "The forest is not good" "les nie je dobrý"
skcard . "The man is not nice" "muž nie je pekný"
skcard . "The finger is not tall" "prst nie je vysoký"
skcard . "The house is not large" "dom nie je veľký"
skcard . "The school is not good" "škola nie je dobrá"
skcard . "The boy is not green" "chlapec nie je zelený"
skcard . "The tree is not tall" "strom nie je vysoký"
skcard . "The tree is not green" "strom nie je zelený"
skcard . "The tree is not new" "strom nie je nový"
skcard . "The tree is not bad" "strom nie je zlý"
skcard . "The garden is not new" "záhrada nie je nová"
skcard . "The forehead is not clean" "čelo nie je čisté"
skcard . "The eye is not new" "oko nie je nové"
skcard . "The finger is not bad" "prst nie je zlý"
skcard . "The head is not good" "hlava nie je dobrá"
skcard . "The hand is not nice" "ruka nie je pekná"
skcard . "The evening is not good" "večer nie je dobrý"
skcard . "The town is not good" "mesto nie je dobré"
skcard . "The town is not bad" "mesto nie je zlé"
skcard . "The glass is not tall" "sklo nie je vysoké"
skcard . "The gentleman is not clean" "pán nie je čistý"
skcard . "The day is not green" "deň nie je zelený"
skcard . "The child is not small" "dieťa nie je malé"
skcard . "The town is not clean" "mesto nie je čisté"
skcard . "The town is not small" "mesto nie je malé"
skcard . "The house is not nice" "dom nie je pekný"
skcard . "The gentleman is not small" "pán nie je malý"
skcard . "The picture is not bad" "obraz nie je zlý"
skcard . "The glass is not nice" "sklo nie je pekné"
skcard . "The village is not large" "dedina nie je veľká"
skcard . "The glass is not green" "sklo nie je zelené"
skcard . "The finger is not clean" "prst nie je čistý"
skcard . "The lady is not nice" "pani nie je pekná"
skcard . "The gentleman is not nice" "pán nie je pekný"
skcard . "The day is not bad" "deň nie je zlý"
skcard . "The head is not bad" "hlava nie je zlá"
skcard . "The child is not green" "dieťa nie je zelené"
skcard . "The child is not bad" "dieťa nie je zlé"
skcard . "The shoulder is not tall" "rameno nie je vysoké"
skcard . "The village is not good" "dedina nie je dobrá"
skcard . "The child is not clean" "dieťa nie je čisté"
skcard . "The child is not nice" "dieťa nie je pekné"
skcard . "The head is not tall" "hlava nie je vysoká"
skcard . "The horse is not large" "kôň nie je veľký"
skcard . "The street is not nice" "ulica nie je pekná"
skcard . "The tree is not small" "strom nie je malý"
skcard . "The head is not nice" "hlava nie je pekná"
skcard . "The garden is not clean" "záhrada nie je čistá"
skcard . "The picture is not new" "obraz nie je nový"
skcard . "The hand is not small" "ruka nie je malá"
skcard . "The hand is not good" "ruka nie je dobrá"
skcard . "The morning is not large" "ráno nie je veľké"
skcard . "The morning is not bad" "ráno nie je zlé"
skcard . "The foot is not new" "noha nie je nová"
skcard . "The hand is not bad" "ruka nie je zlá"
skcard . "The morning is not nice" "ráno nie je pekné"
skcard . "The hand is not large" "ruka nie je veľká"
skcard . "The eye is not good" "oko nie je dobré"
skcard . "The lady is not clean" "pani nie je čistá"
skcard . "The face is not bad" "tvár nie je zlá"
skcard . "The wall is not new" "stena nie je nová"
skcard . "The house is not good" "dom nie je dobrý"
skcard . "The tree is not nice" "strom nie je pekný"
skcard . "The water is not tall" "voda nie je vysoká"
skcard . "The picture is not good" "obraz nie je dobrý"
skcard . "The horse is not small" "kôň nie je malý"
skcard . "The street is not green" "ulica nie je zelená"
skcard . "The school is not clean" "škola nie je čistá"
skcard . "The street is not bad" "ulica nie je zlá"
skcard . "The forest is not tall" "les nie je vysoký"
skcard . "The horse is not new" "kôň nie je nový"
skcard . "The head is not new" "hlava nie je nová"
skcard . "The house is not tall" "dom nie je vysoký"
skcard . "The forehead is not tall" "čelo nie je vysoké"
skcard . "The boy is not small" "chlapec nie je malý"
skcard . "The forehead is not new" "čelo nie je nové"
skcard . "The gentleman is not green" "pán nie je zelený"
skcard . "The classroom is not new" "trieda nie je nová"
skcard . "The street is not good" "ulica nie je dobrá"
skcard . "The shoulder is not new" "rameno nie je nové"
skcard . "The classroom is not bad" "trieda nie je zlá"
skcard . "The forest is not small" "les nie je malý"
skcard . "The school is not bad" "škola nie je zlá"
skcard . "The boy is not bad" "chlapec nie je zlý"
skcard . "The wall is not tall" "stena nie je vysoká"
skcard . "The school is not new" "škola nie je nová"
skcard . "The forehead is not green" "čelo nie je zelené"
skcard . "The classroom is not clean" "trieda nie je čistá"
skcard . "The water is not clean" "voda nie je čistá"
skcard . "The palm is not tall" "dlaň nie je vysoká"
skcard . "The morning is not clean" "ráno nie je čisté"
skcard . "The boy is not large" "chlapec nie je veľký"
skcard . "The morning is not small" "ráno nie je malé"
skcard . "The evening is not bad" "večer nie je zlý"
skcard . "The village is not nice" "dedina nie je pekná"
skcard . "The face is not new" "tvár nie je nová"
skcard . "The house is not green" "dom nie je zelený"
skcard . "The book is not tall" "kniha nie je vysoká"
skcard . "The garden is not bad" "záhrada nie je zlá"
skcard . "The morning is not tall" "ráno nie je vysoké"
skcard . "The day is not nice" "deň nie je pekný"
skcard . "The head is not clean" "hlava nie je čistá"
skcard . "The town is not new" "mesto nie je nové"
skcard . "The evening is not clean" "večer nie je čistý"
skcard . "The picture is not small" "obraz nie je malý"
skcard . "The evening is not new" "večer nie je nový"
skcard . "The horse is not tall" "kôň nie je vysoký"
skcard . "The finger is not large" "prst nie je veľký"
skcard . "The street is not large" "ulica nie je veľká"
skcard . "The child is not good" "dieťa nie je dobré"
skcard . "The book is not small" "kniha nie je malá"
skcard . "The book is not bad" "kniha nie je zlá"
skcard . "The garden is not good" "záhrada nie je dobrá"
skcard . "The forest is not new" "les nie je nový"
skcard . "The gentleman is not tall" "pán nie je vysoký"
skcard . "The forest is not nice" "les nie je pekný"
skcard . "The picture is not tall" "obraz nie je vysoký"
skcard . "The boy is not clean" "chlapec nie je čistý"
skcard . "The evening is not large" "večer nie je veľký"
skcard . "The hand is not new" "ruka nie je nová"
skcard . "The classroom is not small" "trieda nie je malá"
skcard . "The lady is not tall" "pani nie je vysoká"
skcard . "The lady is not green" "pani nie je zelená"
skcard . "The street is not clean" "ulica nie je čistá"
skcard . "The gentleman is not bad" "pán nie je zlý"
skcard . "The lady is not small" "pani nie je malá"
skcard . "The forest is not large" "les nie je veľký"
skcard . "The wall is not clean" "stena nie je čistá"
skcard . "The wall is not bad" "stena nie je zlá"
skcard . "The forehead is not good" "čelo nie je dobré"
skcard . "The lady is not bad" "pani nie je zlá"
skcard . "The foot is not small" "noha nie je malá"
skcard . "The forest is not clean" "les nie je čistý"
skcard . "The palm is not clean" "dlaň nie je čistá"
skcard . "The foot is not clean" "noha nie je čistá"
skcard . "The school is not nice" "škola nie je pekná"
skcard . "The water is not green" "voda nie je zelená"
skcard . "The day is not good" "deň nie je dobrý"
skcard . "The village is not tall" "dedina nie je vysoká"
skcard . "The finger is not good" "prst nie je dobrý"
skcard . "The foot is not nice" "noha nie je pekná"
skcard . "The gentleman is not large" "pán nie je veľký"
skcard . "The day is not large" "deň nie je veľký"
skcard . "The child is not large" "dieťa nie je veľké"
skcard . "The palm is not large" "dlaň nie je veľká"
skcard . "The shoulder is not bad" "rameno nie je zlé"
skcard . "The wall is not green" "stena nie je zelená"
skcard . "The eye is not large" "oko nie je veľké"
skcard . "The forest is not bad" "les nie je zlý"
skcard . "The boy is not new" "chlapec nie je nový"
skcard . "The street is not small" "ulica nie je malá"
skcard . "The palm is not new" "dlaň nie je nová"
skcard . "The house is not bad" "dom nie je zlý"
skcard . "The house is not small" "dom nie je malý"
skcard . "The garden is not tall" "záhrada nie je vysoká"
skcard . "The man is not bad" "muž nie je zlý"
skcard . "The garden is not green" "záhrada nie je zelená"
skcard . "The man is not large" "muž nie je veľký"
skcard . "The day is not new" "deň nie je nový"
skcard . "The face is not good" "tvár nie je dobrá"
skcard . "The boy is not good" "chlapec nie je dobrý"
skcard . "The classroom is not green" "trieda nie je zelená"
skcard . "The glass is not bad" "sklo nie je zlé"
skcard . "The lady is not large" "pani nie je veľká"
skcard . "The hand is not green" "ruka nie je zelená"
skcard . "The face is not tall" "tvár nie je vysoká"
skcard . "The glass is not good" "sklo nie je dobré"
skcard . "The finger is not small" "prst nie je malý"
skcard . "The school is not small" "škola nie je malá"
skcard . "The book is not new" "kniha nie je nová"
skcard . "The classroom is not nice" "trieda nie je pekná"
skcard . "The garden is not nice" "záhrada nie je pekná"
skcard . "The glass is not large" "sklo nie je veľké"
skcard . "The shoulder is not clean" "rameno nie je čisté"
skcard . "The wall is not nice" "stena nie je pekná"
skcard . "The evening is not tall" "večer nie je vysoký"
skcard . "The face is not nice" "tvár nie je pekná"
skcard . "The face is not large" "tvár nie je veľká"
skcard . "The picture is not large" "obraz nie je veľký"
skcard . "The eye is not nice" "oko nie je pekné"
skcard . "The forehead is not bad" "čelo nie je zlé"
skcard . "The day is not clean" "deň nie je čistý"
skcard . "The face is not clean" "tvár nie je čistá"
skcard . "The finger is not nice" "prst nie je pekný"
skcard . "The man is not clean" "muž nie je čistý"
skcard . "The town is not tall" "mesto nie je vysoké"
skcard . "The book is not clean" "kniha nie je čistá"
skcard . "The town is not large" "mesto nie je veľké"
skcard . "The wall is not large" "stena nie je veľká"
skcard . "The book is not large" "kniha nie je veľká"
skcard . "The house is not new" "dom nie je nový"
skcard . "The glass is not clean" "sklo nie je čisté"
skcard . "The water is not new" "voda nie je nová"
skcard . "The town is not green" "mesto nie je zelené"
skcard . "The eye is not bad" "oko nie je zlé"
skcard . "The foot is not green" "noha nie je zelená"
skcard . "The palm is not small" "dlaň nie je malá"
skcard . "The tree is not large" "strom nie je veľký"
skcard . "The palm is not green" "dlaň nie je zelená"
skcard . "The street is not new" "ulica nie je nová"
skcard . "The palm is not good" "dlaň nie je dobrá"
skcard . "The village is not bad" "dedina nie je zlá"
skcard . "The shoulder is not good" "rameno nie je dobré"
skcard . "The man is not small" "muž nie je malý"
skcard . "The glass is not small" "sklo nie je malé"
skcard . "The lady is not new" "pani nie je nová"
skcard . "The picture is not nice" "obraz nie je pekný"
skcard . "The man is not green" "muž nie je zelený"
skcard . "The lady is not good" "pani nie je dobrá"
skcard . "The garden is not small" "záhrada nie je malá"
skcard . "The foot is not tall" "noha nie je vysoká"
skcard . "The child is not new" "dieťa nie je nové"
skcard . "The village is not small" "dedina nie je malá"
skcard . "The forest is not green" "les nie je zelený"
skcard . "The forehead is not large" "čelo nie je veľké"
skcard . "The house is not clean" "dom nie je čistý"
skcard . "The town is not nice" "mesto nie je pekné"
skcard . "The water is not nice" "voda nie je pekná"
skcard . "The forehead is not nice" "čelo nie je pekné"
skcard . "The evening is not nice" "večer nie je pekný"
skcard . "The wall is not small" "stena nie je malá"
skcard . "The horse is not good" "kôň nie je dobrý"
skcard . "The foot is not good" "noha nie je dobrá"
skcard . "The head is not small" "hlava nie je malá"
skcard . "The shoulder is not large" "rameno nie je veľké"
skcard . "The book is not green" "kniha nie je zelená"
skcard . "The horse is not bad" "kôň nie je zlý"
skcard . "The hand is not tall" "ruka nie je vysoká"
skcard . "The school is not large" "škola nie je veľká"
skcard . "The boy is not nice" "chlapec nie je pekný"
skcard . "The man is not good" "muž nie je dobrý"
skcard . "The morning is not green" "ráno nie je zelené"
skcard . "The man is not tall" "muž nie je vysoký"
skcard . "The classroom is not tall" "trieda nie je vysoká"
skcard . "The water is not large" "voda nie je veľká"
skcard . "The head is not large" "hlava nie je veľká"
skcard . "The finger is not new" "prst nie je nový"
skcard . "The man is not new" "muž nie je nový"
skcard . "The shoulder is not green" "rameno nie je zelené"

exit
skcard . "The milk is green" "mlieko je zelené"
skcard . "The milk is bad" "mlieko je zlé"
skcard . "The milk is clean" "mlieko je čisté"
skcard . "The milk is good" "mlieko je dobré"
skcard . "The milk is nice" "mlieko je pekné"
skcard . "The milk is large" "mlieko je veľké"
skcard . "The milk is tall" "mlieko je vysoké"
skcard . "The milk is new" "mlieko je nové"
skcard . "The milk is small" "mlieko je malé"
skcard . "The meadow is nice" "lúka je pekná"
skcard . "The meadow is small" "lúka je malá"
skcard . "The meadow is green" "lúka je zelená"
skcard . "The meadow is tall" "lúka je vysoká"
skcard . "The meadow is clean" "lúka je čistá"
skcard . "The meadow is new" "lúka je nová"
skcard . "The meadow is bad" "lúka je zlá"
skcard . "The meadow is good" "lúka je dobrá"
skcard . "The meadow is large" "lúka je veľká"
skcard . "The shoulder is small" "rameno je malé"
skcard . "The picture is green" "obraz je zelený"
skcard . "The picture is clean" "obraz je čistý"
skcard . "The eye is tall" "oko je vysoké"
skcard . "The morning is good" "ráno je dobré"
skcard . "The book is good" "kniha je dobrá"
skcard . "The village is green" "dedina je zelená"
skcard . "The horse is clean" "kôň je čistý"
skcard . "The classroom is good" "trieda je dobrá"
skcard . "The classroom is large" "trieda je veľká"
skcard . "The evening is green" "večer je zelený"
skcard . "The water is bad" "voda je zlá"
skcard . "The glass is new" "sklo je nové"
skcard . "The gentleman is new" "pán je nový"
skcard . "The foot is large" "noha je veľká"
skcard . "The shoulder is nice" "rameno je pekné"
skcard . "The tree is clean" "strom je čistý"
skcard . "The morning is new" "ráno je nové"
skcard . "The head is green" "hlava je zelená"
skcard . "The village is new" "dedina je nová"
skcard . "The tree is good" "strom je dobrý"
skcard . "The horse is green" "kôň je zelený"
skcard . "The eye is green" "oko je zelené"
skcard . "The day is tall" "deň je vysoký"
skcard . "The garden is large" "záhrada je veľká"
skcard . "The book is nice" "kniha je pekná"
skcard . "The child is tall" "dieťa je vysoké"
skcard . "The water is good" "voda je dobrá"
skcard . "The school is tall" "škola je vysoká"
skcard . "The eye is small" "oko je malé"
skcard . "The wall is good" "stena je dobrá"
skcard . "The boy is tall" "chlapec je vysoký"
skcard . "The gentleman is good" "pán je dobrý"
skcard . "The forehead is small" "čelo je malé"
skcard . "The village is clean" "dedina je čistá"
skcard . "The eye is clean" "oko je čisté"
skcard . "The finger is green" "prst je zelený"
skcard . "The face is small" "tvár je malá"
skcard . "The street is tall" "ulica je vysoká"
skcard . "The day is small" "deň je malý"
skcard . "The water is small" "voda je malá"
skcard . "The palm is nice" "dlaň je pekná"
skcard . "The palm is bad" "dlaň je zlá"
skcard . "The foot is bad" "noha je zlá"
skcard . "The face is green" "tvár je zelená"
skcard . "The hand is clean" "ruka je čistá"
skcard . "The evening is small" "večer je malý"
skcard . "The school is green" "škola je zelená"
skcard . "The horse is nice" "kôň je pekný"
skcard . "The forest is good" "les je dobrý"
skcard . "The man is nice" "muž je pekný"
skcard . "The finger is tall" "prst je vysoký"
skcard . "The house is large" "dom je veľký"
skcard . "The school is good" "škola je dobrá"
skcard . "The boy is green" "chlapec je zelený"
skcard . "The tree is tall" "strom je vysoký"
skcard . "The tree is green" "strom je zelený"
skcard . "The tree is new" "strom je nový"
skcard . "The tree is bad" "strom je zlý"
skcard . "The garden is new" "záhrada je nová"
skcard . "The forehead is clean" "čelo je čisté"
skcard . "The eye is new" "oko je nové"
skcard . "The finger is bad" "prst je zlý"
skcard . "The head is good" "hlava je dobrá"
skcard . "The hand is nice" "ruka je pekná"
skcard . "The evening is good" "večer je dobrý"
skcard . "The town is good" "mesto je dobré"
skcard . "The town is bad" "mesto je zlé"
skcard . "The glass is tall" "sklo je vysoké"
skcard . "The gentleman is clean" "pán je čistý"
skcard . "The day is green" "deň je zelený"
skcard . "The child is small" "dieťa je malé"
skcard . "The town is clean" "mesto je čisté"
skcard . "The town is small" "mesto je malé"
skcard . "The house is nice" "dom je pekný"
skcard . "The gentleman is small" "pán je malý"
skcard . "The picture is bad" "obraz je zlý"
skcard . "The glass is nice" "sklo je pekné"
skcard . "The village is large" "dedina je veľká"
skcard . "The glass is green" "sklo je zelené"
skcard . "The finger is clean" "prst je čistý"
skcard . "The lady is nice" "pani je pekná"
skcard . "The gentleman is nice" "pán je pekný"
skcard . "The day is bad" "deň je zlý"
skcard . "The head is bad" "hlava je zlá"
skcard . "The child is green" "dieťa je zelené"
skcard . "The child is bad" "dieťa je zlé"
skcard . "The shoulder is tall" "rameno je vysoké"
skcard . "The village is good" "dedina je dobrá"
skcard . "The child is clean" "dieťa je čisté"
skcard . "The child is nice" "dieťa je pekné"
skcard . "The head is tall" "hlava je vysoká"
skcard . "The horse is large" "kôň je veľký"
skcard . "The street is nice" "ulica je pekná"
skcard . "The tree is small" "strom je malý"
skcard . "The head is nice" "hlava je pekná"
skcard . "The garden is clean" "záhrada je čistá"
skcard . "The picture is new" "obraz je nový"
skcard . "The hand is small" "ruka je malá"
skcard . "The hand is good" "ruka je dobrá"
skcard . "The morning is large" "ráno je veľké"
skcard . "The morning is bad" "ráno je zlé"
skcard . "The foot is new" "noha je nová"
skcard . "The hand is bad" "ruka je zlá"
skcard . "The morning is nice" "ráno je pekné"
skcard . "The hand is large" "ruka je veľká"
skcard . "The eye is good" "oko je dobré"
skcard . "The lady is clean" "pani je čistá"
skcard . "The face is bad" "tvár je zlá"
skcard . "The wall is new" "stena je nová"
skcard . "The house is good" "dom je dobrý"
skcard . "The tree is nice" "strom je pekný"
skcard . "The water is tall" "voda je vysoká"
skcard . "The picture is good" "obraz je dobrý"
skcard . "The horse is small" "kôň je malý"
skcard . "The street is green" "ulica je zelená"
skcard . "The school is clean" "škola je čistá"
skcard . "The street is bad" "ulica je zlá"
skcard . "The forest is tall" "les je vysoký"
skcard . "The horse is new" "kôň je nový"
skcard . "The head is new" "hlava je nová"
skcard . "The house is tall" "dom je vysoký"
skcard . "The forehead is tall" "čelo je vysoké"
skcard . "The boy is small" "chlapec je malý"
skcard . "The forehead is new" "čelo je nové"
skcard . "The gentleman is green" "pán je zelený"
skcard . "The classroom is new" "trieda je nová"
skcard . "The street is good" "ulica je dobrá"
skcard . "The shoulder is new" "rameno je nové"
skcard . "The classroom is bad" "trieda je zlá"
skcard . "The forest is small" "les je malý"
skcard . "The school is bad" "škola je zlá"
skcard . "The boy is bad" "chlapec je zlý"
skcard . "The wall is tall" "stena je vysoká"
skcard . "The school is new" "škola je nová"
skcard . "The forehead is green" "čelo je zelené"
skcard . "The classroom is clean" "trieda je čistá"
skcard . "The water is clean" "voda je čistá"
skcard . "The palm is tall" "dlaň je vysoká"
skcard . "The morning is clean" "ráno je čisté"
skcard . "The boy is large" "chlapec je veľký"
skcard . "The morning is small" "ráno je malé"
skcard . "The evening is bad" "večer je zlý"
skcard . "The village is nice" "dedina je pekná"
skcard . "The face is new" "tvár je nová"
skcard . "The house is green" "dom je zelený"
skcard . "The book is tall" "kniha je vysoká"
skcard . "The garden is bad" "záhrada je zlá"
skcard . "The morning is tall" "ráno je vysoké"
skcard . "The day is nice" "deň je pekný"
skcard . "The head is clean" "hlava je čistá"
skcard . "The town is new" "mesto je nové"
skcard . "The evening is clean" "večer je čistý"
skcard . "The picture is small" "obraz je malý"
skcard . "The evening is new" "večer je nový"
skcard . "The horse is tall" "kôň je vysoký"
skcard . "The finger is large" "prst je veľký"
skcard . "The street is large" "ulica je veľká"
skcard . "The child is good" "dieťa je dobré"
skcard . "The book is small" "kniha je malá"
skcard . "The book is bad" "kniha je zlá"
skcard . "The garden is good" "záhrada je dobrá"
skcard . "The forest is new" "les je nový"
skcard . "The gentleman is tall" "pán je vysoký"
skcard . "The forest is nice" "les je pekný"
skcard . "The picture is tall" "obraz je vysoký"
skcard . "The boy is clean" "chlapec je čistý"
skcard . "The evening is large" "večer je veľký"
skcard . "The hand is new" "ruka je nová"
skcard . "The classroom is small" "trieda je malá"
skcard . "The lady is tall" "pani je vysoká"
skcard . "The lady is green" "pani je zelená"
skcard . "The street is clean" "ulica je čistá"
skcard . "The gentleman is bad" "pán je zlý"
skcard . "The lady is small" "pani je malá"
skcard . "The forest is large" "les je veľký"
skcard . "The wall is clean" "stena je čistá"
skcard . "The wall is bad" "stena je zlá"
skcard . "The forehead is good" "čelo je dobré"
skcard . "The lady is bad" "pani je zlá"
skcard . "The foot is small" "noha je malá"
skcard . "The forest is clean" "les je čistý"
skcard . "The palm is clean" "dlaň je čistá"
skcard . "The foot is clean" "noha je čistá"
skcard . "The school is nice" "škola je pekná"
skcard . "The water is green" "voda je zelená"
skcard . "The day is good" "deň je dobrý"
skcard . "The village is tall" "dedina je vysoká"
skcard . "The finger is good" "prst je dobrý"
skcard . "The foot is nice" "noha je pekná"
skcard . "The gentleman is large" "pán je veľký"
skcard . "The day is large" "deň je veľký"
skcard . "The child is large" "dieťa je veľké"
skcard . "The palm is large" "dlaň je veľká"
skcard . "The shoulder is bad" "rameno je zlé"
skcard . "The wall is green" "stena je zelená"
skcard . "The eye is large" "oko je veľké"
skcard . "The forest is bad" "les je zlý"
skcard . "The boy is new" "chlapec je nový"
skcard . "The street is small" "ulica je malá"
skcard . "The palm is new" "dlaň je nová"
skcard . "The house is bad" "dom je zlý"
skcard . "The house is small" "dom je malý"
skcard . "The garden is tall" "záhrada je vysoká"
skcard . "The man is bad" "muž je zlý"
skcard . "The garden is green" "záhrada je zelená"
skcard . "The man is large" "muž je veľký"
skcard . "The day is new" "deň je nový"
skcard . "The face is good" "tvár je dobrá"
skcard . "The boy is good" "chlapec je dobrý"
skcard . "The classroom is green" "trieda je zelená"
skcard . "The glass is bad" "sklo je zlé"
skcard . "The lady is large" "pani je veľká"
skcard . "The hand is green" "ruka je zelená"
skcard . "The face is tall" "tvár je vysoká"
skcard . "The glass is good" "sklo je dobré"
skcard . "The finger is small" "prst je malý"
skcard . "The school is small" "škola je malá"
skcard . "The book is new" "kniha je nová"
skcard . "The classroom is nice" "trieda je pekná"
skcard . "The garden is nice" "záhrada je pekná"
skcard . "The glass is large" "sklo je veľké"
skcard . "The shoulder is clean" "rameno je čisté"
skcard . "The wall is nice" "stena je pekná"
skcard . "The evening is tall" "večer je vysoký"
skcard . "The face is nice" "tvár je pekná"
skcard . "The face is large" "tvár je veľká"
skcard . "The picture is large" "obraz je veľký"
skcard . "The eye is nice" "oko je pekné"
skcard . "The forehead is bad" "čelo je zlé"
skcard . "The day is clean" "deň je čistý"
skcard . "The face is clean" "tvár je čistá"
skcard . "The finger is nice" "prst je pekný"
skcard . "The man is clean" "muž je čistý"
skcard . "The town is tall" "mesto je vysoké"
skcard . "The book is clean" "kniha je čistá"
skcard . "The town is large" "mesto je veľké"
skcard . "The wall is large" "stena je veľká"
skcard . "The book is large" "kniha je veľká"
skcard . "The house is new" "dom je nový"
skcard . "The glass is clean" "sklo je čisté"
skcard . "The water is new" "voda je nová"
skcard . "The town is green" "mesto je zelené"
skcard . "The eye is bad" "oko je zlé"
skcard . "The foot is green" "noha je zelená"
skcard . "The palm is small" "dlaň je malá"
skcard . "The tree is large" "strom je veľký"
skcard . "The palm is green" "dlaň je zelená"
skcard . "The street is new" "ulica je nová"
skcard . "The palm is good" "dlaň je dobrá"
skcard . "The village is bad" "dedina je zlá"
skcard . "The shoulder is good" "rameno je dobré"
skcard . "The man is small" "muž je malý"
skcard . "The glass is small" "sklo je malé"
skcard . "The lady is new" "pani je nová"
skcard . "The picture is nice" "obraz je pekný"
skcard . "The man is green" "muž je zelený"
skcard . "The lady is good" "pani je dobrá"
skcard . "The garden is small" "záhrada je malá"
skcard . "The foot is tall" "noha je vysoká"
skcard . "The child is new" "dieťa je nové"
skcard . "The village is small" "dedina je malá"
skcard . "The forest is green" "les je zelený"
skcard . "The forehead is large" "čelo je veľké"
skcard . "The house is clean" "dom je čistý"
skcard . "The town is nice" "mesto je pekné"
skcard . "The water is nice" "voda je pekná"
skcard . "The forehead is nice" "čelo je pekné"
skcard . "The evening is nice" "večer je pekný"
skcard . "The wall is small" "stena je malá"
skcard . "The horse is good" "kôň je dobrý"
skcard . "The foot is good" "noha je dobrá"
skcard . "The head is small" "hlava je malá"
skcard . "The shoulder is large" "rameno je veľké"
skcard . "The book is green" "kniha je zelená"
skcard . "The horse is bad" "kôň je zlý"
skcard . "The hand is tall" "ruka je vysoká"
skcard . "The school is large" "škola je veľká"
skcard . "The boy is nice" "chlapec je pekný"
skcard . "The man is good" "muž je dobrý"
skcard . "The morning is green" "ráno je zelené"
skcard . "The man is tall" "muž je vysoký"
skcard . "The classroom is tall" "trieda je vysoká"
skcard . "The water is large" "voda je veľká"
skcard . "The head is large" "hlava je veľká"
skcard . "The finger is new" "prst je nový"
skcard . "The man is new" "muž je nový"
skcard . "The shoulder is green" "rameno je zelené"
