# skcard . "here is a last garden" "tu je posledná záhrada"
# skcard . "I have good vehicles" "ja mám dobré vozy"
# skcard . "here are good trees" "tu sú dobré stromy"
# skcard . "here are tall shops" "tu sú vysoké obchody"
# skcard . "I have a tall shop" "ja mám vysoký obchod"
# skcard . "I have tall flowers" "ja mám vysoké kvety"
# skcard . "here are which buildings?" "tu sú ktoré stavby"
# skcard . "here is some evening" "tu je nejaký večer"
# skcard . "here are new buildings" "tu sú nové stavby"
# skcard . "I have some men" "ja mám nejakých mužov"
# skcard . "here are main trees" "tu sú hlavné stromy"
# skcard . "I have a good fence" "ja mám dobrý plot"
# skcard . "here are last towns" "tu sú posledné mestá"
# skcard . "I have a main wall" "ja mám hlavnú stenu"
# skcard . "I have which cars?" "ja mám ktoré autá"
# skcard . "I have a good class" "ja mám dobrú triedu"
# skcard . "here is a new vehicle" "tu je nový voz"
# skcard . "I have fine riverbanks" "ja mám pekné brehy"
# skcard . "I have a simple classes" "ja mám jednoduché triedy"
# skcard . "I have a right station" "ja mám pravú stanicu"
# skcard . "here is a main fence" "tu je hlavný plot"
# skcard . "I have wide heads" "ja mám široké hlavy"
# skcard . "I have some heads" "ja mám nejaké hlavy"
# skcard . "here are some buildings" "tu sú nejaké stavby"
# skcard . "here are tall buildings" "tu sú vysoké stavby"
# skcard . "here are good streets" "tu sú dobré ulice"
# skcard . "here are new feet" "tu sú nové nohy"
# skcard . "I have low books" "ja mám nízke knihy"
# skcard . "here is some man" "tu je nejaký muž"
# skcard . "I have fine questions" "ja mám pekné otázky"
# skcard . "I have some books" "ja mám nejaké knihy"
# skcard . "I have a right tree" "ja mám pravý strom"
# skcard . "here is a simple yard" "tu je jednoduchý dvor"
# skcard . "here is a last home" "tu je posledný dom"
# skcard . "here are tall cars" "tu sú vysoké autá"
# skcard . "here is such a fence" "tu je taký plot"
# skcard . "I have some villages" "ja mám nejaké dediny"
# skcard . "I have a tall book" "ja mám vysokú knihu"
# skcard . "I have some fences" "ja mám nejaké ploty"
# skcard . "I have a tall wall" "ja mám vysokú stenu"
# skcard . "here are main prices" "tu sú hlavné ceny"
# skcard . "I have last streets" "ja mám posledné ulice"
# skcard . "I have a main vehicle" "ja mám hlavný voz"
# skcard . "I have main heads" "ja mám hlavné hlavy"
# skcard . "I have which vehicle?" "ja mám ktorý voz"
# skcard . "here are good flowers" "tu sú dobré kvety"
# skcard . "I have such a head" "ja mám takú hlavu"
# skcard . "here is which riverbank?" "tu je ktorý breh"
# skcard . "I have such men" "ja mám takých mužov"
# skcard . "I have a wide building" "ja mám širokú stavbu"
# skcard . "I have a good picture" "ja mám dobrý obraz"
# skcard . "here are last fingers" "tu sú posledné prsty"
# skcard . "I have a tall flower" "ja mám vysoký kvet"
# skcard . "I have right shops" "ja mám pravé obchody"
# skcard . "here is which shop?" "tu je ktorý obchod"
# skcard . "I have low meadows" "ja mám nízke lúky"
# skcard . "I have a main thing" "ja mám hlavnú vec"
# skcard . "here are low prices" "tu sú nízke ceny"
# skcard . "I have some minutes" "ja mám nejaké minúty"
# skcard . "here are such prices" "tu sú také ceny"
# skcard . "I have a fine river" "ja mám peknú rieku"
# skcard . "I have some picture" "ja mám nejaký obraz"
# skcard . "I have right pictures" "ja mám pravé obrazy"
# skcard . "I have a wide shop" "ja mám široký obchod"
# skcard . "here is a last street" "tu je posledná ulica"
# skcard . "I have wide vehicles" "ja mám široké vozy"
# skcard . "here is a simple tree" "tu je jednoduchý strom"
# skcard . "here is which fence?" "tu je ktorý plot"
# skcard . "here is some thing" "tu je nejaká vec"
# skcard . "I have last meadows" "ja mám posledné lúky"
# skcard . "here is a low yard" "tu je nízky dvor"
# skcard . "I have main meadows" "ja mám hlavné lúky"
# skcard . "I have a tall river" "ja mám vysokú rieku"
# skcard . "here are some trees" "tu sú nejaké stromy"
# skcard . "I have simple yards" "ja mám jednoduché dvory"
# skcard . "here is a wide riverbank" "tu je široký breh"
# skcard . "I have new gardens" "ja mám nové záhrady"
# skcard . "here is a low town" "tu je nízke mesto"
# skcard . "here are which flowers?" "tu sú ktoré kvety"
# skcard . "I have new fences" "ja mám nové ploty"
# skcard . "here is a tall finger" "tu je vysoký prst"
# skcard . "I have which yard?" "ja mám ktorý dvor"
# skcard . "here are such schools" "tu sú také školy"
# skcard . "here are good books" "tu sú dobré knihy"
# skcard . "I have a low fence" "ja mám nízky plot"
# skcard . "here are such rivers" "tu sú také rieky"
# skcard . "here is a simple town" "tu je jednoduché mesto"
# skcard . "I have such stations" "ja mám také stanice"
# skcard . "I have new towns" "ja mám nové mestá"
# skcard . "I have main towns" "ja mám hlavné mestá"
# skcard . "here is a tall foot" "tu je vysoká noha"
# skcard . "here is a good flower" "tu je dobrý kvet"
# skcard . "I have which school?" "ja mám ktorú školu"
# skcard . "here is a wide school" "tu je široká škola"
# skcard . "I have some riverbanks" "ja mám nejaké brehy"
# skcard . "I have a simple head" "ja mám jednoduchú hlavu"
# skcard . "I have good villages" "ja mám dobré dediny"
# skcard . "here is such a garden" "tu je taká záhrada"
# skcard . "here is a simple evening" "tu je jednoduchý večer"
# skcard . "here are simple riverbanks" "tu sú jednoduché brehy"
# skcard . "I have a good thing" "ja mám dobrú vec"
# skcard . "I have some station" "ja mám nejakú stanicu"
# skcard . "I have which towns?" "ja mám ktoré mestá"
# skcard . "here is a right book" "tu je pravá kniha"
# skcard . "here are right heads" "tu sú pravé hlavy"
# skcard . "I have which gardens?" "ja mám ktoré záhrady"
# skcard . "here is a last head" "tu je posledná hlava"
# skcard . "I have some street" "ja mám nejakú ulicu"
# skcard . "I have which riverbanks?" "ja mám ktoré brehy"
# skcard . "I have wide towns" "ja mám široké mestá"
# skcard . "here are last trees" "tu sú posledné stromy"
# skcard . "I have last homes" "ja mám posledné domy"
# skcard . "I have right villages" "ja mám pravé dediny"
# skcard . "here are low rivers" "tu sú nízke rieky"
# skcard . "I have simple prices" "ja mám jednoduché ceny"
# skcard . "I have some trees" "ja mám nejaké stromy"
# skcard . "I have a simple wall" "ja mám jednoduchú stenu"
# skcard . "here is which station?" "tu je ktorá stanica"
# skcard . "here are such meadows" "tu sú také lúky"
# skcard . "I have a wide meadow" "ja mám širokú lúku"
# skcard . "here is a new foot" "tu je nová noha"
# skcard . "here is a right wall" "tu je pravá stena"
# skcard . "here are right stations" "tu sú pravé stanice"
# skcard . "I have a new minute" "ja mám novú minútu"
# skcard . "here are wide yards" "tu sú široké dvory"
# skcard . "here is a new head" "tu je nová hlava"
# skcard . "here is a fine shop" "tu je pekný obchod"
# skcard . "I have a last picture" "ja mám posledný obraz"
# skcard . "here are low hands" "tu sú nízke ruky"
# skcard . "I have new forests" "ja mám nové lesy"
# skcard . "here are which stations?" "tu sú ktoré stanice"
# skcard . "here is a last station" "tu je posledná stanica"
# skcard . "I have a fine evening" "ja mám pekný večer"
# skcard . "I have low feet" "ja mám nízke nohy"
# skcard . "I have good shops" "ja mám dobré obchody"
# skcard . "here are good things" "tu sú dobré veci"
# skcard . "I have a tall car" "ja mám vysoké auto"
# skcard . "I have a last shop" "ja mám posledný obchod"
# skcard . "here is some car" "tu je nejaké auto"
# skcard . "I have such meadows" "ja mám také lúky"
# skcard . "I have wide schools" "ja mám široké školy"
# skcard . "here are new prices" "tu sú nové ceny"
# skcard . "here is a tall vehicle" "tu je vysoký voz"
# skcard . "I have main yards" "ja mám hlavné dvory"
# skcard . "here are good homes" "tu sú dobré domy"
# skcard . "I have new homes" "ja mám nové domy"
# skcard . "here are last gardens" "tu sú posledné záhrady"
# skcard . "here is a tall question" "tu je vysoká otázka"
# skcard . "I have tall forests" "ja mám vysoké lesy"
# skcard . "here are good vehicles" "tu sú dobré vozy"
# skcard . "here is a new picture" "tu je nový obraz"
# skcard . "I have a low picture" "ja mám nízky obraz"
# skcard . "here are low fences" "tu sú nízke ploty"
# skcard . "I have a main foot" "ja mám hlavnú nohu"
# skcard . "I have tall pictures" "ja mám vysoké obrazy"
# skcard . "I have a low man" "ja mám nízkeho muža"
# skcard . "I have a good meadow" "ja mám dobrú lúku"
# skcard . "I have good rivers" "ja mám dobré rieky"
# skcard . "I have such a hand" "ja mám takú ruku"
# skcard . "here are tall flowers" "tu sú vysoké kvety"
# skcard . "here are such homes" "tu sú také domy"
# skcard . "here is some building" "tu je nejaká stavba"
# skcard . "here are wide schools" "tu sú široké školy"
# skcard . "here are simple men" "tu sú jednoduchí muži"
# skcard . "I have low men" "ja mám nízkych mužov"
# skcard . "here is a main hand" "tu je hlavná ruka"
# skcard . "I have some shops" "ja mám nejaké obchody"
# skcard . "here are main shops" "tu sú hlavné obchody"
# skcard . "I have a right evening" "ja mám pravý večer"
# skcard . "I have a simple thing" "ja mám jednoduchú vec"
# skcard . "I have such a minute" "ja mám takú minútu"
# skcard . "I have some minute" "ja mám nejakú minútu"
# skcard . "here is a new flower" "tu je nový kvet"
# skcard . "I have a low river" "ja mám nízku rieku"
# skcard . "I have wide rivers" "ja mám široké rieky"
# skcard . "here is a simple riverbank" "tu je jednoduchý breh"
# skcard . "I have good minutes" "ja mám dobré minúty"
# skcard . "here is such a picture" "tu je taký obraz"
# skcard . "I have good streets" "ja mám dobré ulice"
# skcard . "I have low wallss" "ja mám nízke steny"
# skcard . "I have a fine hand" "ja mám peknú ruku"
# skcard . "here are low fingers" "tu sú nízke prsty"
# skcard . "I have a main finger" "ja mám hlavný prst"
# skcard . "here is a new yard" "tu je nový dvor"
# skcard . "I have main books" "ja mám hlavné knihy"
# skcard . "here are simple wallss" "tu sú jednoduché steny"
# skcard . "here are low men" "tu sú nízki muži"
# skcard . "here are good stations" "tu sú dobré stanice"
# skcard . "I have new cars" "ja mám nové autá"
# skcard . "I have a wide man" "ja mám širokého muža"
# skcard . "I have low heads" "ja mám nízke hlavy"
# skcard . "here is a main flower" "tu je hlavný kvet"
# skcard . "I have a main garden" "ja mám hlavnú záhradu"
# skcard . "I have last pictures" "ja mám posledné obrazy"
# skcard . "here are new flowers" "tu sú nové kvety"
# skcard . "I have a wide car" "ja mám široké auto"
# skcard . "here is a tall home" "tu je vysoký dom"
# skcard . "here is such a tree" "tu je taký strom"
# skcard . "here are main flowers" "tu sú hlavné kvety"
# skcard . "here is a fine book" "tu je pekná kniha"
# skcard . "I have right trees" "ja mám pravé stromy"
# skcard . "here is which town?" "tu je ktoré mesto"
# skcard . "I have a good yard" "ja mám dobrý dvor"
# skcard . "here is a wide price" "tu je široká cena"
# skcard . "I have a right price" "ja mám pravú cenu"
# skcard . "I have a right thing" "ja mám pravú vec"
# skcard . "I have simple men" "ja mám jednoduchých mužov"
# skcard . "here is a right vehicle" "tu je pravý voz"
# skcard . "here are some streets" "tu sú nejaké ulice"
# skcard . "here are tall things" "tu sú vysoké veci"
# skcard . "I have a tall village" "ja mám vysokú dedinu"
# skcard . "here is a low picture" "tu je nízky obraz"
# skcard . "here is such a flower" "tu je taký kvet"
# skcard . "I have some stations" "ja mám nejaké stanice"
# skcard . "I have tall minutes" "ja mám vysoké minúty"
# skcard . "here are some minutes" "tu sú nejaké minúty"
# skcard . "I have such a yard" "ja mám taký dvor"
# skcard . "I have wide things" "ja mám široké veci"
# skcard . "here is a low river" "tu je nízka rieka"
# skcard . "here is some minute" "tu je nejaká minúta"
# skcard . "here are main fences" "tu sú hlavné ploty"
# skcard . "I have a right river" "ja mám pravú rieku"
# skcard . "here is a low forest" "tu je nízky les"
# skcard . "here is a low tree" "tu je nízky strom"
# skcard . "I have a tall meadow" "ja mám vysokú lúku"
# skcard . "I have a wide evening" "ja mám široký večer"
# skcard . "I have a simple hand" "ja mám jednoduchú ruku"
# skcard . "here is a new car" "tu je nové auto"
# skcard . "here are last meadows" "tu sú posledné lúky"
# skcard . "here is a good price" "tu je dobrá cena"
# skcard . "here are last hands" "tu sú posledné ruky"
# skcard . "I have some things" "ja mám nejaké veci"
# skcard . "I have a main forest" "ja mám hlavný les"
# skcard . "I have a wide head" "ja mám širokú hlavu"
# skcard . "I have main streets" "ja mám hlavné ulice"
# skcard . "here are low riverbanks" "tu sú nízke brehy"
# skcard . "here is a good minute" "tu je dobrá minúta"
# skcard . "I have a low flower" "ja mám nízky kvet"
# skcard . "here are such fingers" "tu sú také prsty"
# skcard . "I have a right hand" "ja mám pravú ruku"
# skcard . "I have a new school" "ja mám novú školu"
# skcard . "here are wide minutes" "tu sú široké minúty"
# skcard . "here is a wide head" "tu je široká hlava"
# skcard . "here is a good picture" "tu je dobrý obraz"
# skcard . "here is which evening?" "tu je ktorý večer"
# skcard . "here are last men" "tu sú poslední muži"
# skcard . "here are wide flowers" "tu sú široké kvety"
# skcard . "here are simple vehicles" "tu sú jednoduché vozy"
# skcard . "here is some garden" "tu je nejaká záhrada"
# skcard . "here are fine villages" "tu sú pekné dediny"
# skcard . "I have tall streets" "ja mám vysoké ulice"
# skcard . "I have a low school" "ja mám nízku školu"
# skcard . "here are some fingers" "tu sú nejaké prsty"
# skcard . "I have a wide finger" "ja mám široký prst"
# skcard . "I have right meadows" "ja mám pravé lúky"
# skcard . "here are some hands" "tu sú nejaké ruky"
# skcard . "here are main fingers" "tu sú hlavné prsty"
# skcard . "here are some things" "tu sú nejaké veci"
# skcard . "here are right cars" "tu sú pravé autá"
# skcard . "here are which forests?" "tu sú ktoré lesy"
# skcard . "here is a low garden" "tu je nízka záhrada"
# skcard . "here are simple schools" "tu sú jednoduché školy"
# skcard . "I have some village" "ja mám nejakú dedinu"
# skcard . "here are last cars" "tu sú posledné autá"
# skcard . "I have low hands" "ja mám nízke ruky"
# skcard . "I have such a picture" "ja mám taký obraz"
# skcard . "I have such a book" "ja mám takú knihu"
# skcard . "here are right wallss" "tu sú pravé steny"
# skcard . "here is a tall flower" "tu je vysoký kvet"
# skcard . "here is a good evening" "tu je dobrý večer"
# skcard . "here is a new building" "tu je nová stavba"
# skcard . "here are right streets" "tu sú pravé ulice"
# skcard . "here is which head?" "tu je ktorá hlava"
# skcard . "I have such forests" "ja mám také lesy"
# skcard . "I have which home?" "ja mám ktorý dom"
# skcard . "here is a right meadow" "tu je pravá lúka"
# skcard . "I have a good head" "ja mám dobrú hlavu"
# skcard . "I have a last classes" "ja mám posledné triedy"
# skcard . "I have a fine street" "ja mám peknú ulicu"
# skcard . "I have which stations?" "ja mám ktoré stanice"
# skcard . "I have a wide tree" "ja mám široký strom"
# skcard . "I have fine villages" "ja mám pekné dediny"
# skcard . "here is which school?" "tu je ktorá škola"
# skcard . "I have main flowers" "ja mám hlavné kvety"
# skcard . "here are fine men" "tu sú pekní muži"
# skcard . "I have some homes" "ja mám nejaké domy"
# skcard . "I have a tall classes" "ja mám vysoké triedy"
# skcard . "I have such wallss" "ja mám také steny"
# skcard . "here is some river" "tu je nejaká rieka"
# skcard . "I have tall schools" "ja mám vysoké školy"
# skcard . "I have a tall garden" "ja mám vysokú záhradu"
# skcard . "here are good wallss" "tu sú dobré steny"
# skcard . "I have a new foot" "ja mám novú nohu"
# skcard . "I have last fingers" "ja mám posledné prsty"
# skcard . "here is a low head" "tu je nízka hlava"
# skcard . "here is a last town" "tu je posledné mesto"
# skcard . "here are last rivers" "tu sú posledné rieky"
# skcard . "I have last towns" "ja mám posledné mestá"
# skcard . "here is some flower" "tu je nejaký kvet"
# skcard . "here are main buildings" "tu sú hlavné stavby"
# skcard . "here are wide evenings" "tu sú široké večery"
# skcard . "I have a last wall" "ja mám poslednú stenu"
# skcard . "here is a good shop" "tu je dobrý obchod"
# skcard . "I have a fine station" "ja mám peknú stanicu"
# skcard . "here are some fences" "tu sú nejaké ploty"
# skcard . "I have a good garden" "ja mám dobrú záhradu"
# skcard . "I have a fine riverbank" "ja mám pekný breh"
# skcard . "here are some pictures" "tu sú nejaké obrazy"
# skcard . "here are right flowers" "tu sú pravé kvety"
# skcard . "here is a good street" "tu je dobrá ulica"
# skcard . "here is a new garden" "tu je nová záhrada"
# skcard . "I have a new wall" "ja mám novú stenu"
# skcard . "I have fine prices" "ja mám pekné ceny"
# skcard . "I have fine forests" "ja mám pekné lesy"
# skcard . "here are main things" "tu sú hlavné veci"
# skcard . "I have which tree?" "ja mám ktorý strom"
# skcard . "here are low classes" "tu sú nízke triedy"
# skcard . "here are fine gardens" "tu sú pekné záhrady"
# skcard . "I have a right man" "ja mám pravého muža"
# skcard . "here is a last forest" "tu je posledný les"
# skcard . "I have which flowers?" "ja mám ktoré kvety"
# skcard . "here are last flowers" "tu sú posledné kvety"
# skcard . "here is a wide fence" "tu je široký plot"
# skcard . "here is such a minute" "tu je taká minúta"
# skcard . "I have a low head" "ja mám nízku hlavu"
# skcard . "here is a wide village" "tu je široká dedina"
# skcard . "I have a right home" "ja mám pravý dom"
# skcard . "I have good things" "ja mám dobré veci"
# skcard . "here are wide homes" "tu sú široké domy"
# skcard . "here is a last fence" "tu je posledný plot"
# skcard . "I have some book" "ja mám nejakú knihu"
# skcard . "I have good questions" "ja mám dobré otázky"
# skcard . "here are fine cars" "tu sú pekné autá"
# skcard . "I have some feet" "ja mám nejaké nohy"
# skcard . "I have new flowers" "ja mám nové kvety"
# skcard . "here are wide rivers" "tu sú široké rieky"
# skcard . "I have some schools" "ja mám nejaké školy"
# skcard . "I have low questions" "ja mám nízke otázky"
# skcard . "here are good heads" "tu sú dobré hlavy"
# skcard . "here are which rivers?" "tu sú ktoré rieky"
# skcard . "I have a good price" "ja mám dobrú cenu"
# skcard . "here is a wide vehicle" "tu je široký voz"
# skcard . "I have a right riverbank" "ja mám pravý breh"
# skcard . "I have new prices" "ja mám nové ceny"
# skcard . "here are tall trees" "tu sú vysoké stromy"
# skcard . "I have a tall man" "ja mám vysokého muža"
# skcard . "here are main evenings" "tu sú hlavné večery"
# skcard . "here is a wide yard" "tu je široký dvor"
# skcard . "I have a wide village" "ja mám širokú dedinu"
# skcard . "I have such a man" "ja mám takého muža"
# skcard . "I have a good river" "ja mám dobrú rieku"
# skcard . "I have wide feet" "ja mám široké nohy"
# skcard . "here is some shop" "tu je nejaký obchod"
# skcard . "here is a right station" "tu je pravá stanica"
# skcard . "I have right gardens" "ja mám pravé záhrady"
# skcard . "I have a tall picture" "ja mám vysoký obraz"
# skcard . "here is a good village" "tu je dobrá dedina"
# skcard . "I have fine pictures" "ja mám pekné obrazy"
# skcard . "I have such buildings" "ja mám také stavby"
# skcard . "here are simple homes" "tu sú jednoduché domy"
# skcard . "I have a last riverbank" "ja mám posledný breh"
# skcard . "I have such a village" "ja mám takú dedinu"
# skcard . "here are tall homes" "tu sú vysoké domy"
# skcard . "I have right homes" "ja mám pravé domy"
# skcard . "here is such a meadow" "tu je taká lúka"
# skcard . "here are main stations" "tu sú hlavné stanice"
# skcard . "I have a tall forest" "ja mám vysoký les"
# skcard . "here is a good vehicle" "tu je dobrý voz"
# skcard . "I have which building?" "ja mám ktorú stavbu"
# skcard . "here are new schools" "tu sú nové školy"
# skcard . "here is some price" "tu je nejaká cena"
# skcard . "here is a new wall" "tu je nová stena"
# skcard . "I have a new flower" "ja mám nový kvet"
# skcard . "here are which minutes?" "tu sú ktoré minúty"
# skcard . "I have right vehicles" "ja mám pravé vozy"
# skcard . "I have main riverbanks" "ja mám hlavné brehy"
# skcard . "I have a good street" "ja mám dobrú ulicu"
# skcard . "I have such yards" "ja mám také dvory"
# skcard . "here is a new finger" "tu je nový prst"
# skcard . "here are which wallss?" "tu sú ktoré steny"
# skcard . "I have which men?" "ja mám ktorých mužov"
# skcard . "I have a low station" "ja mám nízku stanicu"
# skcard . "here are tall villages" "tu sú vysoké dediny"
# skcard . "here is which wall?" "tu je ktorá stena"
# skcard . "here are last stations" "tu sú posledné stanice"
# skcard . "here are simple gardens" "tu sú jednoduché záhrady"
# skcard . "here are last questions" "tu sú posledné otázky"
# skcard . "here is a new man" "tu je nový muž"
# skcard . "here is a fine hand" "tu je pekná ruka"
# skcard . "here is a main question" "tu je hlavná otázka"
# skcard . "I have good books" "ja mám dobré knihy"
# skcard . "here are wide villages" "tu sú široké dediny"
# skcard . "I have a wide garden" "ja mám širokú záhradu"
# skcard . "I have a main flower" "ja mám hlavný kvet"
# skcard . "here are simple towns" "tu sú jednoduché mestá"
# skcard . "I have a simple fence" "ja mám jednoduchý plot"
# skcard . "here are wide cars" "tu sú široké autá"
# skcard . "here are tall forests" "tu sú vysoké lesy"
# skcard . "here is a wide finger" "tu je široký prst"
# skcard . "I have good gardens" "ja mám dobré záhrady"
# skcard . "here are main men" "tu sú hlavní muži"
# skcard . "here are new gardens" "tu sú nové záhrady"
# skcard . "I have a fine meadow" "ja mám peknú lúku"
# skcard . "I have a fine building" "ja mám peknú stavbu"
# skcard . "here are tall heads" "tu sú vysoké hlavy"
# skcard . "I have a tall evening" "ja mám vysoký večer"
# skcard . "I have fine gardens" "ja mám pekné záhrady"
# skcard . "here is a fine question" "tu je pekná otázka"
# skcard . "here is a wide car" "tu je široké auto"
# skcard . "I have a right car" "ja mám pravé auto"
# skcard . "here are new yards" "tu sú nové dvory"
# skcard . "here are good buildings" "tu sú dobré stavby"
# skcard . "I have a new tree" "ja mám nový strom"
# skcard . "I have some building" "ja mám nejakú stavbu"
# skcard . "here is a last hand" "tu je posledná ruka"
# skcard . "here is a simple river" "tu je jednoduchá rieka"
# skcard . "here are low forests" "tu sú nízke lesy"
# skcard . "here are low cars" "tu sú nízke autá"
# skcard . "I have a main hand" "ja mám hlavnú ruku"
# skcard . "here is such a foot" "tu je taká noha"
# skcard . "I have wide buildings" "ja mám široké stavby"
# skcard . "here is a main head" "tu je hlavná hlava"
# skcard . "I have a good forest" "ja mám dobrý les"
# skcard . "I have a good book" "ja mám dobrú knihu"
# skcard . "I have simple questions" "ja mám jednoduché otázky"
# skcard . "here are good rivers" "tu sú dobré rieky"
# skcard . "I have a fine classes" "ja mám pekné triedy"
# skcard . "here is a fine price" "tu je pekná cena"
# skcard . "I have tall buildings" "ja mám vysoké stavby"
# skcard . "I have main forests" "ja mám hlavné lesy"
# skcard . "I have fine hands" "ja mám pekné ruky"
# skcard . "here is a last river" "tu je posledná rieka"
# skcard . "here are simple evenings" "tu sú jednoduché večery"
# skcard . "I have a low meadow" "ja mám nízku lúku"
# skcard . "I have a good riverbank" "ja mám dobrý breh"
# skcard . "I have a fine flower" "ja mám pekný kvet"
# skcard . "here is a good school" "tu je dobrá škola"
# skcard . "I have fine schools" "ja mám pekné školy"
# skcard . "I have a last class" "ja mám poslednú triedu"
# skcard . "I have a some class" "ja mám nejakú triedu"
# skcard . "I have such trees" "ja mám také stromy"
# skcard . "here are fine shops" "tu sú pekné obchody"
# skcard . "here are low evenings" "tu sú nízke večery"
# skcard . "here is a main building" "tu je hlavná stavba"
# skcard . "here is which building?" "tu je ktorá stavba"
# skcard . "here are wide feet" "tu sú široké nohy"
# skcard . "here is a good station" "tu je dobrá stanica"
# skcard . "here is a right village" "tu je pravá dedina"
# skcard . "here are good feet" "tu sú dobré nohy"
# skcard . "I have a right garden" "ja mám pravú záhradu"
# skcard . "I have such shops" "ja mám také obchody"
# skcard . "I have right buildings" "ja mám pravé stavby"
# skcard . "here are new cars" "tu sú nové autá"
# skcard . "here is a low evening" "tu je nízky večer"
# skcard . "here are new trees" "tu sú nové stromy"
# skcard . "here is a last meadow" "tu je posledná lúka"
# skcard . "here is a wide station" "tu je široká stanica"
# skcard . "I have which questions?" "ja mám ktoré otázky"
# skcard . "I have such a riverbank" "ja mám taký breh"
# skcard . "here are last things" "tu sú posledné veci"
# skcard . "here is a simple price" "tu je jednoduchá cena"
# skcard . "here are main homes" "tu sú hlavné domy"
# skcard . "here are fine pictures" "tu sú pekné obrazy"
# skcard . "here are fine books" "tu sú pekné knihy"
# skcard . "here is some vehicle" "tu je nejaký voz"
# skcard . "here is a wide garden" "tu je široká záhrada"
# skcard . "here is a right garden" "tu je pravá záhrada"
# skcard . "I have simple towns" "ja mám jednoduché mestá"
# skcard . "I have last minutes" "ja mám posledné minúty"
# skcard . "I have a new garden" "ja mám novú záhradu"
# skcard . "I have fine stations" "ja mám pekné stanice"
# skcard . "I have a new river" "ja mám novú rieku"
# skcard . "I have such rivers" "ja mám také rieky"
# skcard . "I have a simple village" "ja mám jednoduchú dedinu"
# skcard . "I have a new man" "ja mám nového muža"
# skcard . "here are fine homes" "tu sú pekné domy"
# skcard . "here are simple stations" "tu sú jednoduché stanice"
# skcard . "I have a new yard" "ja mám nový dvor"
# skcard . "here is a right tree" "tu je pravý strom"
skcard . "I have such a class" "ja mám takú triedu"
# skcard . "I have simple riverbanks" "ja mám jednoduché brehy"
# skcard . "I have a simple school" "ja mám jednoduchú školu"
# skcard . "here are new classes" "tu sú nové triedy"
# skcard . "I have simple cars" "ja mám jednoduché autá"
# skcard . "I have a simple yard" "ja mám jednoduchý dvor"
# skcard . "I have good homes" "ja mám dobré domy"
# skcard . "I have a main minute" "ja mám hlavnú minútu"
# skcard . "here is a fine man" "tu je pekný muž"
# skcard . "I have a last hand" "ja mám poslednú ruku"
# skcard . "here are which hands?" "tu sú ktoré ruky"
# skcard . "I have last heads" "ja mám posledné hlavy"
# skcard . "here is a good head" "tu je dobrá hlava"
# skcard . "here are tall riverbanks" "tu sú vysoké brehy"
# skcard . "I have good meadows" "ja mám dobré lúky"
# skcard . "I have wide fingers" "ja mám široké prsty"
# skcard . "I have a main price" "ja mám hlavnú cenu"
# skcard . "I have a low thing" "ja mám nízku vec"
# skcard . "here are fine heads" "tu sú pekné hlavy"
# skcard . "here is a main price" "tu je hlavná cena"
# skcard . "I have fine evenings" "ja mám pekné večery"
# skcard . "here is a right minute" "tu je pravá minúta"
# skcard . "I have a right school" "ja mám pravú školu"
# skcard . "here is a right man" "tu je pravý muž"
# skcard . "I have low trees" "ja mám nízke stromy"
# skcard . "I have last flowers" "ja mám posledné kvety"
# skcard . "here is a tall meadow" "tu je vysoká lúka"
# skcard . "I have some evening" "ja mám nejaký večer"
# skcard . "here are last feet" "tu sú posledné nohy"
# skcard . "I have tall fingers" "ja mám vysoké prsty"
# skcard . "here are fine things" "tu sú pekné veci"
# skcard . "here are right schools" "tu sú pravé školy"
# skcard . "here are some prices" "tu sú nejaké ceny"
# skcard . "I have some finger" "ja mám nejaký prst"
# skcard . "I have a tall head" "ja mám vysokú hlavu"
# skcard . "here are wide shops" "tu sú široké obchody"
# skcard . "I have a good minute" "ja mám dobrú minútu"
# skcard . "here is a simple hand" "tu je jednoduchá ruka"
# skcard . "I have simple shops" "ja mám jednoduché obchody"
# skcard . "I have new rivers" "ja mám nové rieky"
# skcard . "here are fine evenings" "tu sú pekné večery"
# skcard . "I have a good building" "ja mám dobrú stavbu"
# skcard . "here are good yards" "tu sú dobré dvory"
# skcard . "I have which books?" "ja mám ktoré knihy"
# skcard . "I have last gardens" "ja mám posledné záhrady"
# skcard . "I have low gardens" "ja mám nízke záhrady"
# skcard . "here are simple classes" "tu sú jednoduché triedy"
# skcard . "I have some wall" "ja mám nejakú stenu"
# skcard . "here is a tall yard" "tu je vysoký dvor"
# skcard . "here is a simple finger" "tu je jednoduchý prst"
# skcard . "here are wide questions" "tu sú široké otázky"
# skcard . "here is a fine tree" "tu je pekný strom"
# skcard . "here is which garden?" "tu je ktorá záhrada"
# skcard . "here is a last flower" "tu je posledný kvet"
# skcard . "here are simple yards" "tu sú jednoduché dvory"
# skcard . "I have a tall tree" "ja mám vysoký strom"
# skcard . "here is such a home" "tu je taký dom"
# skcard . "here are wide stations" "tu sú široké stanice"
# skcard . "I have a new village" "ja mám novú dedinu"
# skcard . "here is a low meadow" "tu je nízka lúka"
# skcard . "I have a wide foot" "ja mám širokú nohu"
# skcard . "here are which fences?" "tu sú ktoré ploty"
# skcard . "I have a new vehicle" "ja mám nový voz"
# skcard . "I have a last school" "ja mám poslednú školu"
# skcard . "here are simple streets" "tu sú jednoduché ulice"
# skcard . "here is a fine meadow" "tu je pekná lúka"
# skcard . "I have a good classes" "ja mám dobré triedy"
# skcard . "here is some meadow" "tu je nejaká lúka"
# skcard . "I have simple heads" "ja mám jednoduché hlavy"
# skcard . "I have a simple foot" "ja mám jednoduchú nohu"
# skcard . "I have some prices" "ja mám nejaké ceny"
# skcard . "here is a fine flower" "tu je pekný kvet"
# skcard . "here are tall classes" "tu sú vysoké triedy"
# skcard . "I have a simple meadow" "ja mám jednoduchú lúku"
# skcard . "here is a simple school" "tu je jednoduchá škola"
# skcard . "I have a new price" "ja mám novú cenu"
# skcard . "here are low schools" "tu sú nízke školy"
# skcard . "I have a wide minute" "ja mám širokú minútu"
# skcard . "here are last shops" "tu sú posledné obchody"
# skcard . "I have wide prices" "ja mám široké ceny"
# skcard . "here are main villages" "tu sú hlavné dediny"
# skcard . "I have a main home" "ja mám hlavný dom"
# skcard . "here is such a price" "tu je taká cena"
# skcard . "I have last trees" "ja mám posledné stromy"
# skcard . "I have a last book" "ja mám poslednú knihu"
# skcard . "I have fine yards" "ja mám pekné dvory"
# skcard . "here is a wide river" "tu je široká rieka"
# skcard . "I have a main head" "ja mám hlavnú hlavu"
# skcard . "here is a new meadow" "tu je nová lúka"
# skcard . "I have a last car" "ja mám posledné auto"
# skcard . "I have some hands" "ja mám nejaké ruky"
# skcard . "I have a low class" "ja mám nízku triedu"
# skcard . "here is a main picture" "tu je hlavný obraz"
# skcard . "here are which riverbanks?" "tu sú ktoré brehy"
# skcard . "I have such pictures" "ja mám také obrazy"
# skcard . "I have wide fences" "ja mám široké ploty"
# skcard . "I have which minutes?" "ja mám ktoré minúty"
# skcard . "here are fine hands" "tu sú pekné ruky"
# skcard . "here are main meadows" "tu sú hlavné lúky"
# skcard . "I have such a fence" "ja mám taký plot"
# skcard . "I have a simple evening" "ja mám jednoduchý večer"
# skcard . "here are some shops" "tu sú nejaké obchody"
# skcard . "I have a simple river" "ja mám jednoduchú rieku"
# skcard . "I have tall things" "ja mám vysoké veci"
# skcard . "I have wide questions" "ja mám široké otázky"
# skcard . "here are right vehicles" "tu sú pravé vozy"
# skcard . "here is some forest" "tu je nejaký les"
# skcard . "I have last riverbanks" "ja mám posledné brehy"
# skcard . "here is a last building" "tu je posledná stavba"
# skcard . "here is a new class" "tu je nová trieda"
# skcard . "I have such a car" "ja mám také auto"
# skcard . "I have a good question" "ja mám dobrú otázku"
# skcard . "here is such a station" "tu je taká stanica"
# skcard . "here is a tall thing" "tu je vysoká vec"
# skcard . "here is a wide tree" "tu je široký strom"
# skcard . "I have a fine thing" "ja mám peknú vec"
# skcard . "here are fine towns" "tu sú pekné mestá"
# skcard . "I have a tall fence" "ja mám vysoký plot"
# skcard . "I have a fine tree" "ja mám pekný strom"
# skcard . "here is a good foot" "tu je dobrá noha"
# skcard . "here is a good town" "tu je dobré mesto"
# skcard . "I have a new evening" "ja mám nový večer"
# skcard . "I have such a street" "ja mám takú ulicu"
# skcard . "I have a last station" "ja mám poslednú stanicu"
# skcard . "I have low fingers" "ja mám nízke prsty"
# skcard . "here are good towns" "tu sú dobré mestá"
# skcard . "I have good yards" "ja mám dobré dvory"
# skcard . "I have such a meadow" "ja mám takú lúku"
# skcard . "I have which hand?" "ja mám ktorú ruku"
# skcard . "here are simple books" "tu sú jednoduché knihy"
# skcard . "I have such a river" "ja mám takú rieku"
# skcard . "here are last evenings" "tu sú posledné večery"
# skcard . "here is a wide minute" "tu je široká minúta"
# skcard . "I have a low home" "ja mám nízky dom"
# skcard . "I have last vehicles" "ja mám posledné vozy"
# skcard . "here are which homes?" "tu sú ktoré domy"
# skcard . "I have low flowers" "ja mám nízke kvety"
# skcard . "here are wide forests" "tu sú široké lesy"
# skcard . "here is such a yard" "tu je taký dvor"
# skcard . "I have simple minutes" "ja mám jednoduché minúty"
# skcard . "I have a last town" "ja mám posledné mesto"
# skcard . "here is a new forest" "tu je nový les"
# skcard . "I have such heads" "ja mám také hlavy"
# skcard . "here are which shops?" "tu sú ktoré obchody"
# skcard . "here is a good meadow" "tu je dobrá lúka"
# skcard . "I have such books" "ja mám také knihy"
# skcard . "I have some foot" "ja mám nejakú nohu"
# skcard . "I have a simple building" "ja mám jednoduchú stavbu"
# skcard . "I have such schools" "ja mám také školy"
# skcard . "I have a main picture" "ja mám hlavný obraz"
# skcard . "here are fine rivers" "tu sú pekné rieky"
# skcard . "here is which picture?" "tu je ktorý obraz"
# skcard . "I have some shop" "ja mám nejaký obchod"
# skcard . "I have which rivers?" "ja mám ktoré rieky"
# skcard . "here are good evenings" "tu sú dobré večery"
# skcard . "I have a low price" "ja mám nízku cenu"
# skcard . "I have a low shop" "ja mám nízky obchod"
# skcard . "here are new heads" "tu sú nové hlavy"
# skcard . "here is a fine river" "tu je pekná rieka"
# skcard . "here are tall men" "tu sú vysokí muži"
# skcard . "I have a main tree" "ja mám hlavný strom"
# skcard . "here are right shops" "tu sú pravé obchody"
# skcard . "I have good forests" "ja mám dobré lesy"
# skcard . "here are right homes" "tu sú pravé domy"
# skcard . "I have a new finger" "ja mám nový prst"
# skcard . "here is a low home" "tu je nízky dom"
# skcard . "here is a simple question" "tu je jednoduchá otázka"
# skcard . "I have new wallss" "ja mám nové steny"
# skcard . "here are last yards" "tu sú posledné dvory"
# skcard . "I have a right head" "ja mám pravú hlavu"
# skcard . "here are simple villages" "tu sú jednoduché dediny"
# skcard . "I have tall fences" "ja mám vysoké ploty"
# skcard . "here is a wide shop" "tu je široký obchod"
# skcard . "I have some home" "ja mám nejaký dom"
# skcard . "here is a main yard" "tu je hlavný dvor"
# skcard . "here is a main home" "tu je hlavný dom"
# skcard . "here are some meadows" "tu sú nejaké lúky"
# skcard . "I have such fingers" "ja mám také prsty"
# skcard . "here is a last picture" "tu je posledný obraz"
# skcard . "I have a last yard" "ja mám posledný dvor"
# skcard . "I have which station?" "ja mám ktorú stanicu"
# skcard . "I have such fences" "ja mám také ploty"
# skcard . "I have last questions" "ja mám posledné otázky"
# skcard . "I have a wide forest" "ja mám široký les"
# skcard . "here are such villages" "tu sú také dediny"
# skcard . "here are low heads" "tu sú nízke hlavy"
# skcard . "here is a low car" "tu je nízke auto"
# skcard . "I have such evenings" "ja mám také večery"
# skcard . "I have which vehicles?" "ja mám ktoré vozy"
# skcard . "I have good flowers" "ja mám dobré kvety"
# skcard . "I have some meadows" "ja mám nejaké lúky"
# skcard . "here is such a thing" "tu je taká vec"
# skcard . "I have last wallss" "ja mám posledné steny"
# skcard . "here are some wallss" "tu sú nejaké steny"
# skcard . "here are new shops" "tu sú nové obchody"
# skcard . "here is a last yard" "tu je posledný dvor"
# skcard . "I have a low tree" "ja mám nízky strom"
# skcard . "here is a right fence" "tu je pravý plot"
# skcard . "I have tall cars" "ja mám vysoké autá"
# skcard . "here is a fine home" "tu je pekný dom"
# skcard . "here is a wide foot" "tu je široká noha"
# skcard . "here are low vehicles" "tu sú nízke vozy"
# skcard . "I have a low wall" "ja mám nízku stenu"
# skcard . "I have a simple tree" "ja mám jednoduchý strom"
# skcard . "I have new books" "ja mám nové knihy"
# skcard . "I have which schools?" "ja mám ktoré školy"
# skcard . "I have a right question" "ja mám pravú otázku"
# skcard . "I have simple buildings" "ja mám jednoduché stavby"
# skcard . "here are low books" "tu sú nízke knihy"
# skcard . "here are some cars" "tu sú nejaké autá"
# skcard . "I have a low riverbank" "ja mám nízky breh"
# skcard . "I have fine fences" "ja mám pekné ploty"
# skcard . "here are tall prices" "tu sú vysoké ceny"
# skcard . "here are right towns" "tu sú pravé mestá"
# skcard . "here are last homes" "tu sú posledné domy"
# skcard . "I have good fences" "ja mám dobré ploty"
# skcard . "here are tall questions" "tu sú vysoké otázky"
# skcard . "here is a tall tree" "tu je vysoký strom"
# skcard . "here is a fine vehicle" "tu je pekný voz"
# skcard . "I have last yards" "ja mám posledné dvory"
# skcard . "I have which town?" "ja mám ktoré mesto"
# skcard . "here is a tall shop" "tu je vysoký obchod"
# skcard . "here are fine yards" "tu sú pekné dvory"
# skcard . "I have a main question" "ja mám hlavnú otázku"
# skcard . "here are some flowers" "tu sú nejaké kvety"
# skcard . "I have low fences" "ja mám nízke ploty"
# skcard . "I have wide shops" "ja mám široké obchody"
# skcard . "here are wide riverbanks" "tu sú široké brehy"
# skcard . "here are right forests" "tu sú pravé lesy"
# skcard . "I have fine wallss" "ja mám pekné steny"
# skcard . "I have new feet" "ja mám nové nohy"
# skcard . "I have such gardens" "ja mám také záhrady"
# skcard . "here is a right picture" "tu je pravý obraz"
# skcard . "I have a wide price" "ja mám širokú cenu"
# skcard . "I have a fine forest" "ja mám pekný les"
# skcard . "here is some yard" "tu je nejaký dvor"
# skcard . "I have which yards?" "ja mám ktoré dvory"
# skcard . "I have some flowers" "ja mám nejaké kvety"
# skcard . "I have a wide street" "ja mám širokú ulicu"
# skcard . "I have a last meadow" "ja mám poslednú lúku"
# skcard . "here are right classes" "tu sú pravé triedy"
# skcard . "here are wide buildings" "tu sú široké stavby"
# skcard . "here are which things?" "tu sú ktoré veci"
# skcard . "here is a low fence" "tu je nízky plot"
# skcard . "here is a tall fence" "tu je vysoký plot"
# skcard . "here are tall books" "tu sú vysoké knihy"
# skcard . "I have a wide hand" "ja mám širokú ruku"
# skcard . "I have which villages?" "ja mám ktoré dediny"
# skcard . "here are main riverbanks" "tu sú hlavné brehy"
# skcard . "I have a wide class" "ja mám širokú triedu"
# skcard . "here is a last car" "tu je posledné auto"
# skcard . "I have right fingers" "ja mám pravé prsty"
# skcard . "here are such flowers" "tu sú také kvety"
# skcard . "here is which question?" "tu je ktorá otázka"
# skcard . "here is some hand" "tu je nejaká ruka"
# skcard . "I have low shops" "ja mám nízke obchody"
# skcard . "I have a last price" "ja mám poslednú cenu"
# skcard . "here are fine schools" "tu sú pekné školy"
# skcard . "I have such a evening" "ja mám taký večer"
# skcard . "here is a main car" "tu je hlavné auto"
# skcard . "I have some gardens" "ja mám nejaké záhrady"
# skcard . "I have a main station" "ja mám hlavnú stanicu"
# skcard . "I have a tall foot" "ja mám vysokú nohu"
# skcard . "here are new evenings" "tu sú nové večery"
# skcard . "I have a simple car" "ja mám jednoduché auto"
# skcard . "here is a main school" "tu je hlavná škola"
# skcard . "here are such men" "tu sú takí muži"
# skcard . "here is a last foot" "tu je posledná noha"
# skcard . "here are some rivers" "tu sú nejaké rieky"
# skcard . "I have a good town" "ja mám dobré mesto"
# skcard . "I have simple streets" "ja mám jednoduché ulice"
# skcard . "here is a tall head" "tu je vysoká hlava"
skcard . "here are tall meadows" "tu sú vysoké lúky"
# skcard . "I have low schools" "ja mám nízke školy"
# skcard . "I have a new shop" "ja mám nový obchod"
# skcard . "I have a last tree" "ja mám posledný strom"
# skcard . "I have a fine class" "ja mám peknú triedu"
# skcard . "I have right men" "ja mám pravých mužov"
# skcard . "here is such a village" "tu je taká dedina"
# skcard . "I have a last fence" "ja mám posledný plot"
# skcard . "here is a new book" "tu je nová kniha"
# skcard . "I have such riverbanks" "ja mám také brehy"
# skcard . "here are tall feet" "tu sú vysoké nohy"
# skcard . "here are good classes" "tu sú dobré triedy"
# skcard . "I have a tall finger" "ja mám vysoký prst"
# skcard . "I have a right yard" "ja mám pravý dvor"
# skcard . "I have a wide river" "ja mám širokú rieku"
# skcard . "here are good prices" "tu sú dobré ceny"
# skcard . "I have wide books" "ja mám široké knihy"
# skcard . "here is a right finger" "tu je pravý prst"
# skcard . "I have a main shop" "ja mám hlavný obchod"
# skcard . "I have low evenings" "ja mám nízke večery"
# skcard . "I have some man" "ja mám nejakého muža"
# skcard . "here is such a vehicle" "tu je taký voz"
# skcard . "here are wide hands" "tu sú široké ruky"
# skcard . "here are tall pictures" "tu sú vysoké obrazy"
# skcard . "I have which street?" "ja mám ktorú ulicu"
# skcard . "I have right streets" "ja mám pravé ulice"
# skcard . "here are wide fences" "tu sú široké ploty"
# skcard . "I have a last thing" "ja mám poslednú vec"
# skcard . "I have last villages" "ja mám posledné dediny"
# skcard . "here are tall streets" "tu sú vysoké ulice"
# skcard . "here is such a building" "tu je taká stavba"
# skcard . "I have such a school" "ja mám takú školu"
# skcard . "I have a main school" "ja mám hlavnú školu"
skcard . "I have wide meadows" "ja mám široké lúky"
# skcard . "here are which heads?" "tu sú ktoré hlavy"
# skcard . "I have a wide riverbank" "ja mám široký breh"
# skcard . "here is a right hand" "tu je pravá ruka"
# skcard . "here are some feet" "tu sú nejaké nohy"
# skcard . "here are low questions" "tu sú nízke otázky"
# skcard . "I have a last man" "ja mám posledného muža"
# skcard . "I have last prices" "ja mám posledné ceny"
# skcard . "I have a fine head" "ja mám peknú hlavu"
# skcard . "I have such a flower" "ja mám taký kvet"
# skcard . "here are right yards" "tu sú pravé dvory"
# skcard . "here is a low wall" "tu je nízka stena"
# skcard . "I have a right vehicle" "ja mám pravý voz"
# skcard . "here are right men" "tu sú praví muži"
# skcard . "I have a fine book" "ja mám peknú knihu"
# skcard . "here are main streets" "tu sú hlavné ulice"
# skcard . "I have last forests" "ja mám posledné lesy"
# skcard . "here is a good riverbank" "tu je dobrý breh"
# skcard . "here are last classes" "tu sú posledné triedy"
# skcard . "I have a last finger" "ja mám posledný prst"
# skcard . "here is a tall price" "tu je vysoká cena"
# skcard . "I have a simple minute" "ja mám jednoduchú minútu"
# skcard . "here is a main garden" "tu je hlavná záhrada"
# skcard . "I have new buildings" "ja mám nové stavby"
# skcard . "I have a last vehicle" "ja mám posledný voz"
# skcard . "I have wide evenings" "ja mám široké večery"
# skcard . "here is which meadow?" "tu je ktorá lúka"
# skcard . "here is a new river" "tu je nová rieka"
# skcard . "here are low gardens" "tu sú nízke záhrady"
# skcard . "here are main forests" "tu sú hlavné lesy"
# skcard . "here are fine forests" "tu sú pekné lesy"
# skcard . "here are good schools" "tu sú dobré školy"
# skcard . "here is a wide meadow" "tu je široká lúka"
# skcard . "I have low things" "ja mám nízke veci"
# skcard . "I have good pictures" "ja mám dobré obrazy"
# skcard . "here are main hands" "tu sú hlavné ruky"
# skcard . "here are which books?" "tu sú ktoré knihy"
# skcard . "here are right things" "tu sú pravé veci"
# skcard . "I have low pictures" "ja mám nízke obrazy"
# skcard . "I have a wide book" "ja mám širokú knihu"
# skcard . "here are new forests" "tu sú nové lesy"
# skcard . "here are new books" "tu sú nové knihy"
# skcard . "here is which hand?" "tu je ktorá ruka"
# skcard . "here are wide books" "tu sú široké knihy"
# skcard . "here are main feet" "tu sú hlavné nohy"
# skcard . "here is a last evening" "tu je posledný večer"
# skcard . "I have a fine shop" "ja mám pekný obchod"
# skcard . "I have new vehicles" "ja mám nové vozy"
# skcard . "I have such a foot" "ja mám takú nohu"
# skcard . "I have a last minute" "ja mám poslednú minútu"
# skcard . "here are new minutes" "tu sú nové minúty"
# skcard . "here are wide wallss" "tu sú široké steny"
# skcard . "I have fine towns" "ja mám pekné mestá"
# skcard . "here is which flower?" "tu je ktorý kvet"
# skcard . "I have some question" "ja mám nejakú otázku"
# skcard . "I have a tall street" "ja mám vysokú ulicu"
# skcard . "I have a last question" "ja mám poslednú otázku"
# skcard . "I have a fine yard" "ja mám pekný dvor"
# skcard . "I have good heads" "ja mám dobré hlavy"
# skcard . "I have a low book" "ja mám nízku knihu"
# skcard . "here is a low school" "tu je nízka škola"
# skcard . "I have simple rivers" "ja mám jednoduché rieky"
# skcard . "here are which towns?" "tu sú ktoré mestá"
# skcard . "here are fine fences" "tu sú pekné ploty"
# skcard . "I have which evening?" "ja mám ktorý večer"
# skcard . "I have such a question" "ja mám takú otázku"
# skcard . "I have tall wallss" "ja mám vysoké steny"
# skcard . "I have some school" "ja mám nejakú školu"
# skcard . "here are fine feet" "tu sú pekné nohy"
# skcard . "here are such shops" "tu sú také obchody"
# skcard . "here are simple rivers" "tu sú jednoduché rieky"
# skcard . "I have some fingers" "ja mám nejaké prsty"
# skcard . "here are some villages" "tu sú nejaké dediny"
# skcard . "here are low yards" "tu sú nízke dvory"
# skcard . "here is such a river" "tu je taká rieka"
# skcard . "I have new yards" "ja mám nové dvory"
# skcard . "here is such a class" "tu je taká trieda"
# skcard . "here are right prices" "tu sú pravé ceny"
# skcard . "here is some wall" "tu je nejaká stena"
# skcard . "here are which evenings?" "tu sú ktoré večery"
# skcard . "I have such a finger" "ja mám taký prst"
# skcard . "I have a new home" "ja mám nový dom"
# skcard . "here is a fine foot" "tu je pekná noha"
# skcard . "here is a right town" "tu je pravé mesto"
# skcard . "here is a main finger" "tu je hlavný prst"
# skcard . "I have a tall class" "ja mám vysokú triedu"
# skcard . "here are some classes" "tu sú nejaké triedy"
# skcard . "here are wide men" "tu sú širokí muži"
# skcard . "here is some station" "tu je nejaká stanica"
# skcard . "I have right cars" "ja mám pravé autá"
# skcard . "here is a simple man" "tu je jednoduchý muž"
# skcard . "here is a tall man" "tu je vysoký muž"
# skcard . "I have good evenings" "ja mám dobré večery"
# skcard . "I have a right street" "ja mám pravú ulicu"
# skcard . "I have wide flowers" "ja mám široké kvety"
# skcard . "I have which things?" "ja mám ktoré veci"
# skcard . "here are last fences" "tu sú posledné ploty"
# skcard . "I have such towns" "ja mám také mestá"
# skcard . "here are some stations" "tu sú nejaké stanice"
# skcard . "I have which village?" "ja mám ktorú dedinu"
# skcard . "I have some wallss" "ja mám nejaké steny"
# skcard . "I have a tall building" "ja mám vysokú stavbu"
# skcard . "I have a low hand" "ja mám nízku ruku"
# skcard . "here are such minutes" "tu sú také minúty"
# skcard . "here is a main tree" "tu je hlavný strom"
# skcard . "I have some pictures" "ja mám nejaké obrazy"
# skcard . "I have tall vehicles" "ja mám vysoké vozy"
# skcard . "here are new things" "tu sú nové veci"
# skcard . "I have which fence?" "ja mám ktorý plot"
# skcard . "here are such questions" "tu sú také otázky"
# skcard . "I have main shops" "ja mám hlavné obchody"
# skcard . "I have which finger?" "ja mám ktorý prst"
# skcard . "here is which thing?" "tu je ktorá vec"
# skcard . "here is a simple picture" "tu je jednoduchý obraz"
# skcard . "I have a fine car" "ja mám pekné auto"
# skcard . "here are main rivers" "tu sú hlavné rieky"
# skcard . "here are right fences" "tu sú pravé ploty"
# skcard . "I have some yard" "ja mám nejaký dvor"
# skcard . "I have simple villages" "ja mám jednoduché dediny"
# skcard . "here are last forests" "tu sú posledné lesy"
# skcard . "I have such a building" "ja mám takú stavbu"
# skcard . "I have main things" "ja mám hlavné veci"
# skcard . "I have a right book" "ja mám pravú knihu"
# skcard . "I have fine men" "ja mám pekných mužov"
# skcard . "I have a simple shop" "ja mám jednoduchý obchod"
# skcard . "here is a fine riverbank" "tu je pekný breh"
# skcard . "here are some towns" "tu sú nejaké mestá"
# skcard . "here is which home?" "tu je ktorý dom"
# skcard . "here are fine buildings" "tu sú pekné stavby"
# skcard . "I have simple flowers" "ja mám jednoduché kvety"
# skcard . "here is such a book" "tu je taká kniha"
# skcard . "I have main feet" "ja mám hlavné nohy"
# skcard . "I have simple wallss" "ja mám jednoduché steny"
# skcard . "here are good men" "tu sú dobrí muži"
# skcard . "I have right books" "ja mám pravé knihy"
# skcard . "here is a main foot" "tu je hlavná noha"
# skcard . "I have good buildings" "ja mám dobré stavby"
# skcard . "I have a new station" "ja mám novú stanicu"
# skcard . "here are such books" "tu sú také knihy"
# skcard . "here are main heads" "tu sú hlavné hlavy"
# skcard . "here is a low street" "tu je nízka ulica"
# skcard . "here are which schools?" "tu sú ktoré školy"
# skcard . "here is a last tree" "tu je posledný strom"
# skcard . "here is a good thing" "tu je dobrá vec"
# skcard . "here are last buildings" "tu sú posledné stavby"
# skcard . "I have a simple picture" "ja mám jednoduchý obraz"
# skcard . "here is a last riverbank" "tu je posledný breh"
# skcard . "I have a new classes" "ja mám nové triedy"
# skcard . "I have a tall thing" "ja mám vysokú vec"
# skcard . "here are new towns" "tu sú nové mestá"
# skcard . "I have some towns" "ja mám nejaké mestá"
# skcard . "I have new riverbanks" "ja mám nové brehy"
# skcard . "I have last buildings" "ja mám posledné stavby"
# skcard . "here are last riverbanks" "tu sú posledné brehy"
# skcard . "here is such a hand" "tu je taká ruka"
# skcard . "here is a wide flower" "tu je široký kvet"
# skcard . "here is such a evening" "tu je taký večer"
# skcard . "I have a tall home" "ja mám vysoký dom"
# skcard . "here is a low price" "tu je nízka cena"
# skcard . "I have which meadow?" "ja mám ktorú lúku"
# skcard . "I have fine shops" "ja mám pekné obchody"
# skcard . "I have some vehicles" "ja mám nejaké vozy"
# skcard . "I have such a tree" "ja mám taký strom"
# skcard . "here are such feet" "tu sú také nohy"
# skcard . "I have such villages" "ja mám také dediny"
# skcard . "here are good cars" "tu sú dobré autá"
# skcard . "here is some question" "tu je nejaká otázka"
# skcard . "I have a right flower" "ja mám pravý kvet"
skcard . "here are new meadows" "tu sú nové lúky"
# skcard . "here are good villages" "tu sú dobré dediny"
# skcard . "here is a good fence" "tu je dobrý plot"
# skcard . "here are fine trees" "tu sú pekné stromy"
# skcard . "I have tall hands" "ja mám vysoké ruky"
# skcard . "here is a last school" "tu je posledná škola"
# skcard . "here are which feet?" "tu sú ktoré nohy"
# skcard . "I have simple evenings" "ja mám jednoduché večery"
# skcard . "here is some school" "tu je nejaká škola"
# skcard . "here are wide heads" "tu sú široké hlavy"
# skcard . "here is such a school" "tu je taká škola"
# skcard . "I have fine homes" "ja mám pekné domy"
# skcard . "here are simple cars" "tu sú jednoduché autá"
# skcard . "I have some head" "ja mám nejakú hlavu"
# skcard . "here is a tall hand" "tu je vysoká ruka"
# skcard . "here are simple hands" "tu sú jednoduché ruky"
# skcard . "here is such a car" "tu je také auto"
# skcard . "I have wide men" "ja mám širokých mužov"
# skcard . "I have right towns" "ja mám pravé mestá"
# skcard . "I have a right finger" "ja mám pravý prst"
# skcard . "here is a main vehicle" "tu je hlavný voz"
# skcard . "here are simple feet" "tu sú jednoduché nohy"
# skcard . "here is a main river" "tu je hlavná rieka"
# skcard . "here are low villages" "tu sú nízke dediny"
# skcard . "here are some homes" "tu sú nejaké domy"
# skcard . "here are low stations" "tu sú nízke stanice"
# skcard . "I have a right shop" "ja mám pravý obchod"
# skcard . "I have a simple class" "ja mám jednoduchú triedu"
# skcard . "I have a fine town" "ja mám pekné mesto"
# skcard . "I have a good shop" "ja mám dobrý obchod"
# skcard . "I have main fences" "ja mám hlavné ploty"
# skcard . "here is a tall school" "tu je vysoká škola"
# skcard . "here is a wide street" "tu je široká ulica"
# skcard . "here is a right flower" "tu je pravý kvet"
# skcard . "I have which buildings?" "ja mám ktoré stavby"
# skcard . "here is a fine station" "tu je pekná stanica"
# skcard . "here is a good finger" "tu je dobrý prst"
# skcard . "here is which minute?" "tu je ktorá minúta"
# skcard . "here is a fine school" "tu je pekná škola"
# skcard . "I have simple feet" "ja mám jednoduché nohy"
# skcard . "here are new men" "tu sú noví muži"
# skcard . "here are new hands" "tu sú nové ruky"
# skcard . "I have a last garden" "ja mám poslednú záhradu"
# skcard . "I have tall questions" "ja mám vysoké otázky"
# skcard . "I have a wide station" "ja mám širokú stanicu"
# skcard . "here is a main class" "tu je hlavná trieda"
# skcard . "I have some thing" "ja mám nejakú vec"
# skcard . "here is a main street" "tu je hlavná ulica"
# skcard . "here is a good tree" "tu je dobrý strom"
# skcard . "I have a fine fence" "ja mám pekný plot"
# skcard . "I have a simple street" "ja mám jednoduchú ulicu"
# skcard . "here is a tall picture" "tu je vysoký obraz"
# skcard . "here is which book?" "tu je ktorá kniha"
# skcard . "here is such a shop" "tu je taký obchod"
# skcard . "I have some vehicle" "ja mám nejaký voz"
# skcard . "I have wide yards" "ja mám široké dvory"
# skcard . "I have a main car" "ja mám hlavné auto"
# skcard . "here is such a forest" "tu je taký les"
# skcard . "I have a new book" "ja mám novú knihu"
# skcard . "here is which tree?" "tu je ktorý strom"
# skcard . "here are such vehicles" "tu sú také vozy"
# skcard . "I have main vehicles" "ja mám hlavné vozy"
# skcard . "I have a tall question" "ja mám vysokú otázku"
# skcard . "here is some tree" "tu je nejaký strom"
# skcard . "I have last cars" "ja mám posledné autá"
# skcard . "here are right minutes" "tu sú pravé minúty"
# skcard . "I have which prices?" "ja mám ktoré ceny"
# skcard . "here are such things" "tu sú také veci"
# skcard . "I have such a price" "ja mám takú cenu"
# skcard . "here are fine riverbanks" "tu sú pekné brehy"
# skcard . "I have a tall town" "ja mám vysoké mesto"
# skcard . "here is which car?" "tu je ktoré auto"
# skcard . "I have some garden" "ja mám nejakú záhradu"
# skcard . "here are such streets" "tu sú také ulice"
# skcard . "I have a good evening" "ja mám dobrý večer"
# skcard . "I have last shops" "ja mám posledné obchody"
# skcard . "here are tall schools" "tu sú vysoké školy"
# skcard . "here are simple pictures" "tu sú jednoduché obrazy"
# skcard . "here are low flowers" "tu sú nízke kvety"
# skcard . "here is a simple head" "tu je jednoduchá hlava"
# skcard . "here is a simple station" "tu je jednoduchá stanica"
# skcard . "here are wide towns" "tu sú široké mestá"
# skcard . "I have tall heads" "ja mám vysoké hlavy"
# skcard . "here are simple questions" "tu sú jednoduché otázky"
# skcard . "here is a low finger" "tu je nízky prst"
# skcard . "here are which streets?" "tu sú ktoré ulice"
# skcard . "I have a new picture" "ja mám nový obraz"
# skcard . "I have simple schools" "ja mám jednoduché školy"
# skcard . "I have good trees" "ja mám dobré stromy"
# skcard . "here are right hands" "tu sú pravé ruky"
# skcard . "I have such hands" "ja mám také ruky"
# skcard . "I have last evenings" "ja mám posledné večery"
# skcard . "here are which pictures?" "tu sú ktoré obrazy"
# skcard . "I have a fine finger" "ja mám pekný prst"
# skcard . "I have such things" "ja mám také veci"
# skcard . "here are fine prices" "tu sú pekné ceny"
# skcard . "I have a good tree" "ja mám dobrý strom"
# skcard . "I have a right fence" "ja mám pravý plot"
# skcard . "here is some picture" "tu je nejaký obraz"
# skcard . "here is which village?" "tu je ktorá dedina"
# skcard . "here are new pictures" "tu sú nové obrazy"
# skcard . "I have which wall?" "ja mám ktorú stenu"
# skcard . "here is a fine head" "tu je pekná hlava"
# skcard . "here is a tall riverbank" "tu je vysoký breh"
# skcard . "here is a simple meadow" "tu je jednoduchá lúka"
# skcard . "here are such hands" "tu sú také ruky"
# skcard . "here are right villages" "tu sú pravé dediny"
# skcard . "I have low villages" "ja mám nízke dediny"
# skcard . "I have which head?" "ja mám ktorú hlavu"
# skcard . "I have last stations" "ja mám posledné stanice"
# skcard . "here are main yards" "tu sú hlavné dvory"
# skcard . "I have new schools" "ja mám nové školy"
# skcard . "here are such heads" "tu sú také hlavy"
# skcard . "here are good questions" "tu sú dobré otázky"
# skcard . "I have new trees" "ja mám nové stromy"
# skcard . "here are last heads" "tu sú posledné hlavy"
# skcard . "here are some men" "tu sú nejakí muži"
# skcard . "I have tall shops" "ja mám vysoké obchody"
# skcard . "I have good towns" "ja mám dobré mestá"
# skcard . "I have a fine school" "ja mám peknú školu"
# skcard . "here is a simple forest" "tu je jednoduchý les"
# skcard . "I have some questions" "ja mám nejaké otázky"
# skcard . "here is a right forest" "tu je pravý les"
# skcard . "I have a last river" "ja mám poslednú rieku"
# skcard . "here are tall rivers" "tu sú vysoké rieky"
# skcard . "here is a wide forest" "tu je široký les"
# skcard . "here is a fine village" "tu je pekná dedina"
# skcard . "here is a fine thing" "tu je pekná vec"
# skcard . "here are some schools" "tu sú nejaké školy"
# skcard . "here is a low riverbank" "tu je nízky breh"
# skcard . "I have low riverbanks" "ja mám nízke brehy"
# skcard . "I have a simple riverbank" "ja mám jednoduchý breh"
# skcard . "here is a wide book" "tu je široká kniha"
# skcard . "here is a fine forest" "tu je pekný les"
# skcard . "I have low streets" "ja mám nízke ulice"
# skcard . "here is a main evening" "tu je hlavný večer"
# skcard . "here is a good book" "tu je dobrá kniha"
# skcard . "here are tall minutes" "tu sú vysoké minúty"
# skcard . "here are such fences" "tu sú také ploty"
# skcard . "here is a simple minute" "tu je jednoduchá minúta"
# skcard . "here are last minutes" "tu sú posledné minúty"
skcard . "here are simple meadows" "tu sú jednoduché lúky"
# skcard . "here is a fine town" "tu je pekné mesto"
# skcard . "here is a right question" "tu je pravá otázka"
# skcard . "here are right feet" "tu sú pravé nohy"
# skcard . "here is a low man" "tu je nízky muž"
# skcard . "I have last books" "ja mám posledné knihy"
# skcard . "here is a main meadow" "tu je hlavná lúka"
# skcard . "here is a wide hand" "tu je široká ruka"
# skcard . "here are new rivers" "tu sú nové rieky"
# skcard . "I have a right foot" "ja mám pravú nohu"
# skcard . "I have a main man" "ja mám hlavného muža"
# skcard . "I have simple gardens" "ja mám jednoduché záhrady"
# skcard . "here is a simple building" "tu je jednoduchá stavba"
# skcard . "I have a main evening" "ja mám hlavný večer"
# skcard . "here are wide pictures" "tu sú široké obrazy"
# skcard . "here is a tall town" "tu je vysoké mesto"
# skcard . "I have good stations" "ja mám dobré stanice"
# skcard . "here is a last man" "tu je posledný muž"
# skcard . "here are main schools" "tu sú hlavné školy"
# skcard . "here is a new thing" "tu je nová vec"
# skcard . "I have such cars" "ja mám také autá"
# skcard . "here is some riverbank" "tu je nejaký breh"
# skcard . "here is a right yard" "tu je pravý dvor"
# skcard . "here is a fine evening" "tu je pekný večer"
# skcard . "I have last schools" "ja mám posledné školy"
# skcard . "I have which wallss?" "ja mám ktoré steny"
# skcard . "here are low trees" "tu sú nízke stromy"
# skcard . "I have a simple finger" "ja mám jednoduchý prst"
# skcard . "I have some rivers" "ja mám nejaké rieky"
# skcard . "I have wide forests" "ja mám široké lesy"
# skcard . "I have a main building" "ja mám hlavnú stavbu"
# skcard . "I have good prices" "ja mám dobré ceny"
# skcard . "I have which evenings?" "ja mám ktoré večery"
# skcard . "I have some hand" "ja mám nejakú ruku"
# skcard . "here are main minutes" "tu sú hlavné minúty"
# skcard . "here is a good man" "tu je dobrý muž"
# skcard . "I have right riverbanks" "ja mám pravé brehy"
# skcard . "here is a new price" "tu je nová cena"
# skcard . "here is a right evening" "tu je pravý večer"
# skcard . "here are which fingers?" "tu sú ktoré prsty"
# skcard . "I have right fences" "ja mám pravé ploty"
# skcard . "here are simple flowers" "tu sú jednoduché kvety"
# skcard . "here are main books" "tu sú hlavné knihy"
# skcard . "here is a new question" "tu je nová otázka"
# skcard . "here are right trees" "tu sú pravé stromy"
# skcard . "I have some fence" "ja mám nejaký plot"
# skcard . "I have which minute?" "ja mám ktorú minútu"
# skcard . "here is a right class" "tu je pravá trieda"
# skcard . "here is a last vehicle" "tu je posledný voz"
# skcard . "I have such streets" "ja mám také ulice"
# skcard . "here are fine classes" "tu sú pekné triedy"
# skcard . "I have such prices" "ja mám také ceny"
# skcard . "here are which yards?" "tu sú ktoré dvory"
# skcard . "here are low minutes" "tu sú nízke minúty"
# skcard . "here are good forests" "tu sú dobré lesy"
# skcard . "I have fine books" "ja mám pekné knihy"
# skcard . "here are right rivers" "tu sú pravé rieky"
# skcard . "here is a fine car" "tu je pekné auto"
# skcard . "here are main pictures" "tu sú hlavné obrazy"
# skcard . "here is a new tree" "tu je nový strom"
# skcard . "here is a new minute" "tu je nová minúta"
# skcard . "I have which car?" "ja mám ktoré auto"
# skcard . "I have wide gardens" "ja mám široké záhrady"
# skcard . "here is a main book" "tu je hlavná kniha"
# skcard . "here is a tall car" "tu je vysoké auto"
# skcard . "here is a right price" "tu je pravá cena"
# skcard . "here is a last village" "tu je posledná dedina"
# skcard . "I have which foot?" "ja mám ktorú nohu"
# skcard . "I have which hands?" "ja mám ktoré ruky"
# skcard . "I have a low town" "ja mám nízke mesto"
# skcard . "I have a tall station" "ja mám vysokú stanicu"
# skcard . "I have a low building" "ja mám nízku stavbu"
# skcard . "here are wide gardens" "tu sú široké záhrady"
# skcard . "here is a wide thing" "tu je široká vec"
# skcard . "I have main homes" "ja mám hlavné domy"
# skcard . "I have wide streets" "ja mám široké ulice"
# skcard . "here is some village" "tu je nejaká dedina"
# skcard . "here is a new street" "tu je nová ulica"
# skcard . "here is some foot" "tu je nejaká noha"
# skcard . "here are which men?" "tu sú ktorí muži"
# skcard . "I have tall rivers" "ja mám vysoké rieky"
# skcard . "I have which man?" "ja mám ktorého muža"
# skcard . "I have tall prices" "ja mám vysoké ceny"
# skcard . "here is a wide evening" "tu je široký večer"
# skcard . "here is a new shop" "tu je nový obchod"
# skcard . "here is a last wall" "tu je posledná stena"
# skcard . "here are simple prices" "tu sú jednoduché ceny"
# skcard . "I have new heads" "ja mám nové hlavy"
# skcard . "I have a wide school" "ja mám širokú školu"
# skcard . "here are new fingers" "tu sú nové prsty"
# skcard . "here are such gardens" "tu sú také záhrady"
# skcard . "I have a right forest" "ja mám pravý les"
# skcard . "here is such a town" "tu je také mesto"
# skcard . "here is a last question" "tu je posledná otázka"
# skcard . "here are good riverbanks" "tu sú dobré brehy"
# skcard . "here are right pictures" "tu sú pravé obrazy"
# skcard . "here is a low hand" "tu je nízka ruka"
# skcard . "I have a right town" "ja mám pravé mesto"
# skcard . "I have new shops" "ja mám nové obchody"
# skcard . "here is some finger" "tu je nejaký prst"
# skcard . "I have a fine picture" "ja mám pekný obraz"
# skcard . "here are tall wallss" "tu sú vysoké steny"
# skcard . "I have some flower" "ja mám nejaký kvet"
# skcard . "here is some home" "tu je nejaký dom"
# skcard . "here are main vehicles" "tu sú hlavné vozy"
# skcard . "I have new minutes" "ja mám nové minúty"
# skcard . "I have a new town" "ja mám nové mesto"
# skcard . "here is a last price" "tu je posledná cena"
# skcard . "I have main trees" "ja mám hlavné stromy"
# skcard . "I have a new hand" "ja mám novú ruku"
# skcard . "I have fine rivers" "ja mám pekné rieky"
# skcard . "here is a right school" "tu je pravá škola"
# skcard . "here is a tall wall" "tu je vysoká stena"
# skcard . "here is which street?" "tu je ktorá ulica"
# skcard . "I have right forests" "ja mám pravé lesy"
# skcard . "I have some river" "ja mám nejakú rieku"
# skcard . "here is a tall garden" "tu je vysoká záhrada"
# skcard . "here are wide vehicles" "tu sú široké vozy"
# skcard . "I have some meadow" "ja mám nejakú lúku"
# skcard . "here is a low thing" "tu je nízka vec"
# skcard . "here is some class" "tu je nejaká trieda"
# skcard . "here is which man?" "tu je ktorý muž"
# skcard . "here is a fine finger" "tu je pekný prst"
# skcard . "I have a simple garden" "ja mám jednoduchú záhradu"
# skcard . "here are some evenings" "tu sú nejaké večery"
# skcard . "here are good fingers" "tu sú dobré prsty"
# skcard . "here is some fence" "tu je nejaký plot"
# skcard . "I have a simple man" "ja mám jednoduchého muža"
# skcard . "I have such questions" "ja mám také otázky"
# skcard . "I have new men" "ja mám nových mužov"
# skcard . "I have a main class" "ja mám hlavnú triedu"
# skcard . "I have a new fence" "ja mám nový plot"
# skcard . "here is a tall class" "tu je vysoká trieda"
# skcard . "here is a main town" "tu je hlavné mesto"
# skcard . "I have main schools" "ja mám hlavné školy"
# skcard . "here is a main village" "tu je hlavná dedina"
# skcard . "I have a good finger" "ja mám dobrý prst"
# skcard . "I have which river?" "ja mám ktorú rieku"
# skcard . "here are last prices" "tu sú posledné ceny"
# skcard . "here is a low building" "tu je nízka stavba"
# skcard . "I have tall books" "ja mám vysoké knihy"
# skcard . "here are good minutes" "tu sú dobré minúty"
# skcard . "here is a tall street" "tu je vysoká ulica"
# skcard . "I have a last head" "ja mám poslednú hlavu"
# skcard . "here is a good car" "tu je dobré auto"
# skcard . "here are some yards" "tu sú nejaké dvory"
# skcard . "here is a tall station" "tu je vysoká stanica"
skcard . "here are right meadows" "tu sú pravé lúky"
# skcard . "here are wide things" "tu sú široké veci"
# skcard . "I have a wide thing" "ja mám širokú vec"
# skcard . "here are new villages" "tu sú nové dediny"
# skcard . "here is which vehicle?" "tu je ktorý voz"
# skcard . "I have a wide yard" "ja mám široký dvor"
# skcard . "I have which price?" "ja mám ktorú cenu"
# skcard . "here is a fine garden" "tu je pekná záhrada"
# skcard . "I have right prices" "ja mám pravé ceny"
# skcard . "I have which book?" "ja mám ktorú knihu"
# skcard . "here are last vehicles" "tu sú posledné vozy"
# skcard . "here is which river?" "tu je ktorá rieka"
# skcard . "I have which question?" "ja mám ktorú otázku"
# skcard . "I have some buildings" "ja mám nejaké stavby"
# skcard . "I have right evenings" "ja mám pravé večery"
# skcard . "here is such a head" "tu je taká hlava"
# skcard . "here are good fences" "tu sú dobré ploty"
skcard . "here are fine meadows" "tu sú pekné lúky"
# skcard . "I have a wide vehicle" "ja mám široký voz"
# skcard . "here are new stations" "tu sú nové stanice"
# skcard . "I have main buildings" "ja mám hlavné stavby"
# skcard . "I have which riverbank?" "ja mám ktorý breh"
# skcard . "I have which trees?" "ja mám ktoré stromy"
# skcard . "I have right rivers" "ja mám pravé rieky"
# skcard . "I have simple forests" "ja mám jednoduché lesy"
# skcard . "here is some street" "tu je nejaká ulica"
# skcard . "I have new streets" "ja mám nové ulice"
# skcard . "here is a low station" "tu je nízka stanica"
# skcard . "I have simple things" "ja mám jednoduché veci"
# skcard . "here are good shops" "tu sú dobré obchody"
# skcard . "I have such flowers" "ja mám také kvety"
# skcard . "I have a wide wall" "ja mám širokú stenu"
# skcard . "here is a new evening" "tu je nový večer"
# skcard . "here are some questions" "tu sú nejaké otázky"
# skcard . "here is a good forest" "tu je dobrý les"
# skcard . "I have a low vehicle" "ja mám nízky voz"
# skcard . "here is a tall river" "tu je vysoká rieka"
# skcard . "here is some town" "tu je nejaké mesto"
# skcard . "I have main wallss" "ja mám hlavné steny"
# skcard . "here are some forests" "tu sú nejaké lesy"
# skcard . "I have good feet" "ja mám dobré nohy"
# skcard . "I have a wide home" "ja mám široký dom"
# skcard . "here are simple forests" "tu sú jednoduché lesy"
# skcard . "here is a wide town" "tu je široké mesto"
# skcard . "I have a tall school" "ja mám vysokú školu"
# skcard . "I have a new question" "ja mám novú otázku"
# skcard . "here are right evenings" "tu sú pravé večery"
# skcard . "I have a simple forest" "ja mám jednoduchý les"
# skcard . "here are low homes" "tu sú nízke domy"
# skcard . "I have a right classes" "ja mám pravé triedy"
# skcard . "here are last books" "tu sú posledné knihy"
# skcard . "here are which villages?" "tu sú ktoré dediny"
# skcard . "here is such a question" "tu je taká otázka"
# skcard . "I have new fingers" "ja mám nové prsty"
# skcard . "I have a last building" "ja mám poslednú stavbu"
# skcard . "here are simple fingers" "tu sú jednoduché prsty"
# skcard . "I have some riverbank" "ja mám nejaký breh"
# skcard . "I have a main street" "ja mám hlavnú ulicu"
# skcard . "here is a wide home" "tu je široký dom"
# skcard . "here is which price?" "tu je ktorá cena"
# skcard . "I have a good hand" "ja mám dobrú ruku"
# skcard . "here is which foot?" "tu je ktorá noha"
# skcard . "I have wide stations" "ja mám široké stanice"
# skcard . "I have right hands" "ja mám pravé ruky"
# skcard . "here are tall yards" "tu sú vysoké dvory"
# skcard . "here is a low class" "tu je nízka trieda"
# skcard . "I have new villages" "ja mám nové dediny"
# skcard . "here are main questions" "tu sú hlavné otázky"
# skcard . "here are last pictures" "tu sú posledné obrazy"
# skcard . "I have main minutes" "ja mám hlavné minúty"
# skcard . "here is a last minute" "tu je posledná minúta"
# skcard . "here is a main thing" "tu je hlavná vec"
# skcard . "I have which pictures?" "ja mám ktoré obrazy"
# skcard . "I have main villages" "ja mám hlavné dediny"
# skcard . "I have a simple question" "ja mám jednoduchú otázku"
# skcard . "I have a last street" "ja mám poslednú ulicu"
# skcard . "I have main fingers" "ja mám hlavné prsty"
# skcard . "I have fine fingers" "ja mám pekné prsty"
skcard . "I have fine meadows" "ja mám pekné lúky"
# skcard . "here are new homes" "tu sú nové domy"
# skcard . "I have some streets" "ja mám nejaké ulice"
# skcard . "I have a low yard" "ja mám nízky dvor"
# skcard . "here is such a man" "tu je taký muž"
# skcard . "I have wide homes" "ja mám široké domy"
# skcard . "here are new riverbanks" "tu sú nové brehy"
# skcard . "I have a main river" "ja mám hlavnú rieku"
# skcard . "here are simple things" "tu sú jednoduché veci"
# skcard . "here is a good question" "tu je dobrá otázka"
# skcard . "I have such feet" "ja mám také nohy"
# skcard . "here is a right car" "tu je pravé auto"
# skcard . "here are low feet" "tu sú nízke nohy"
# skcard . "I have a simple town" "ja mám jednoduché mesto"
# skcard . "I have new questions" "ja mám nové otázky"
# skcard . "I have a wide flower" "ja mám široký kvet"
# skcard . "here are last wallss" "tu sú posledné steny"
# skcard . "I have good hands" "ja mám dobré ruky"
# skcard . "here are good hands" "tu sú dobré ruky"
# skcard . "I have a low forest" "ja mám nízky les"
# skcard . "I have a new class" "ja mám novú triedu"
# skcard . "here is which forest?" "tu je ktorý les"
# skcard . "I have which shops?" "ja mám ktoré obchody"
# skcard . "here are fine fingers" "tu sú pekné prsty"
# skcard . "I have a new building" "ja mám novú stavbu"
# skcard . "I have a wide town" "ja mám široké mesto"
# skcard . "here are right books" "tu sú pravé knihy"
# skcard . "I have a good car" "ja mám dobré auto"
# skcard . "here is such a finger" "tu je taký prst"
# skcard . "here is a right thing" "tu je pravá vec"
# skcard . "I have simple fingers" "ja mám jednoduché prsty"
# skcard . "I have wide minutes" "ja mám široké minúty"
# skcard . "here is a good building" "tu je dobrá stavba"
# skcard . "I have simple books" "ja mám jednoduché knihy"
# skcard . "I have good fingers" "ja mám dobré prsty"
# skcard . "I have tall evenings" "ja mám vysoké večery"
# skcard . "here are new vehicles" "tu sú nové vozy"
# skcard . "I have which feet?" "ja mám ktoré nohy"
# skcard . "here is a simple shop" "tu je jednoduchý obchod"
# skcard . "here is a good garden" "tu je dobrá záhrada"
# skcard . "here are simple fences" "tu sú jednoduché ploty"
# skcard . "here is a main minute" "tu je hlavná minúta"
# skcard . "I have such a town" "ja mám také mesto"
# skcard . "I have low prices" "ja mám nízke ceny"
# skcard . "here are such wallss" "tu sú také steny"
# skcard . "here is a new station" "tu je nová stanica"
# skcard . "I have a main book" "ja mám hlavnú knihu"
# skcard . "here is a last thing" "tu je posledná vec"
# skcard . "I have a good man" "ja mám dobrého muža"
# skcard . "I have simple stations" "ja mám jednoduché stanice"
# skcard . "here are some heads" "tu sú nejaké hlavy"
# skcard . "here are fine flowers" "tu sú pekné kvety"
# skcard . "here is a low vehicle" "tu je nízky voz"
# skcard . "I have such a forest" "ja mám taký les"
# skcard . "here is a simple flower" "tu je jednoduchý kvet"
# skcard . "here is a simple fence" "tu je jednoduchý plot"
# skcard . "here are wide classes" "tu sú široké triedy"
# skcard . "I have last fences" "ja mám posledné ploty"
# skcard . "here is a new hand" "tu je nová ruka"
# skcard . "here is a last book" "tu je posledná kniha"
# skcard . "here are simple buildings" "tu sú jednoduché stavby"
# skcard . "here are low buildings" "tu sú nízke stavby"
# skcard . "here is such a riverbank" "tu je taký breh"
# skcard . "I have fine heads" "ja mám pekné hlavy"
# skcard . "I have main questions" "ja mám hlavné otázky"
# skcard . "I have a good flower" "ja mám dobrý kvet"
# skcard . "here are good gardens" "tu sú dobré záhrady"
# skcard . "I have wide wallss" "ja mám široké steny"
# skcard . "here are some gardens" "tu sú nejaké záhrady"
# skcard . "here are such evenings" "tu sú také večery"
# skcard . "here is a good home" "tu je dobrý dom"
# skcard . "here are tall hands" "tu sú vysoké ruky"
# skcard . "I have a new forest" "ja mám nový les"
# skcard . "here are low wallss" "tu sú nízke steny"
# skcard . "I have a fine foot" "ja mám peknú nohu"
# skcard . "here are new fences" "tu sú nové ploty"
# skcard . "I have main men" "ja mám hlavných mužov"
# skcard . "I have simple trees" "ja mám jednoduché stromy"
# skcard . "here are some vehicles" "tu sú nejaké vozy"
# skcard . "I have a fine garden" "ja mám peknú záhradu"
# skcard . "I have wide villages" "ja mám široké dediny"
# skcard . "here is a right riverbank" "tu je pravý breh"
# skcard . "I have a fine question" "ja mám peknú otázku"
# skcard . "I have a wide picture" "ja mám široký obraz"
# skcard . "here are main classes" "tu sú hlavné triedy"
# skcard . "here are main towns" "tu sú hlavné mestá"
# skcard . "I have main pictures" "ja mám hlavné obrazy"
# skcard . "I have right wallss" "ja mám pravé steny"
# skcard . "here are wide trees" "tu sú široké stromy"
# skcard . "here are new questions" "tu sú nové otázky"
# skcard . "I have a last forest" "ja mám posledný les"
# skcard . "I have which homes?" "ja mám ktoré domy"
# skcard . "I have new hands" "ja mám nové ruky"
# skcard . "I have a low street" "ja mám nízku ulicu"
# skcard . "I have which fingers?" "ja mám ktoré prsty"
# skcard . "I have good schools" "ja mám dobré školy"
skcard . "I have which meadow?" "ja mám ktoré lúky"
# skcard . "I have which garden?" "ja mám ktorú záhradu"
# skcard . "here is a fine fence" "tu je pekný plot"
# skcard . "I have right schools" "ja mám pravé školy"
# skcard . "here are which cars?" "tu sú ktoré autá"
# skcard . "I have wide trees" "ja mám široké stromy"
# skcard . "I have right minutes" "ja mám pravé minúty"
# skcard . "I have wide riverbanks" "ja mám široké brehy"
# skcard . "I have main rivers" "ja mám hlavné rieky"
# skcard . "I have last hands" "ja mám posledné ruky"
# skcard . "here are which questions?" "tu sú ktoré otázky"
# skcard . "I have a new car" "ja mám nové auto"
# skcard . "I have some price" "ja mám nejakú cenu"
# skcard . "here are last streets" "tu sú posledné ulice"
# skcard . "here is a low flower" "tu je nízky kvet"
# skcard . "I have fine flowers" "ja mám pekné kvety"
# skcard . "I have right stations" "ja mám pravé stanice"
# skcard . "I have a main classes" "ja mám hlavné triedy"
skcard . "I have simple meadows" "ja mám jednoduché lúky"
# skcard . "here is a simple home" "tu je jednoduchý dom"
# skcard . "here is a right street" "tu je pravá ulica"
# skcard . "here are tall gardens" "tu sú vysoké záhrady"
# skcard . "I have which thing?" "ja mám ktorú vec"
# skcard . "I have tall feet" "ja mám vysoké nohy"
# skcard . "here are such buildings" "tu sú také stavby"
# skcard . "I have a simple home" "ja mám jednoduchý dom"
# skcard . "here are simple heads" "tu sú jednoduché hlavy"
# skcard . "here are main wallss" "tu sú hlavné steny"
# skcard . "here is a new riverbank" "tu je nový breh"
# skcard . "I have fine feet" "ja mám pekné nohy"
# skcard . "here are low towns" "tu sú nízke mestá"
# skcard . "I have a fine minute" "ja mám peknú minútu"
skcard . "I have tall meadows" "ja mám vysoké lúky"
# skcard . "I have a tall hand" "ja mám vysokú ruku"
# skcard . "I have a low car" "ja mám nízke auto"
# skcard . "I have low vehicles" "ja mám nízke vozy"
# skcard . "here are last schools" "tu sú posledné školy"
# skcard . "I have main evenings" "ja mám hlavné večery"
# skcard . "I have a low minute" "ja mám nízku minútu"
# skcard . "I have some tree" "ja mám nejaký strom"
# skcard . "I have such minutes" "ja mám také minúty"
skcard . "I have new meadows" "ja mám nové lúky"
# skcard . "here is a main shop" "tu je hlavný obchod"
# skcard . "here is a new town" "tu je nové mesto"
# skcard . "I have tall homes" "ja mám vysoké domy"
# skcard . "I have low stations" "ja mám nízke stanice"
# skcard . "I have a low village" "ja mám nízku dedinu"
# skcard . "I have a simple price" "ja mám jednoduchú cenu"
# skcard . "here is a simple street" "tu je jednoduchá ulica"
# skcard . "here is a right foot" "tu je pravá noha"
# skcard . "here is a main man" "tu je hlavný muž"
# skcard . "here is a simple wall" "tu je jednoduchá stena"
# skcard . "I have main hands" "ja mám hlavné ruky"
# skcard . "I have tall riverbanks" "ja mám vysoké brehy"
# skcard . "I have a good station" "ja mám dobrú stanicu"
# skcard . "I have a main fence" "ja mám hlavný plot"
# skcard . "I have such a thing" "ja mám takú vec"
# skcard . "I have simple vehicles" "ja mám jednoduché vozy"
# skcard . "I have tall men" "ja mám vysokých mužov"
# skcard . "I have a tall yard" "ja mám vysoký dvor"
# skcard . "here are tall stations" "tu sú vysoké stanice"
# skcard . "here is a simple vehicle" "tu je jednoduchý voz"
# skcard . "here is a fine wall" "tu je pekná stena"
# skcard . "I have tall villages" "ja mám vysoké dediny"
# skcard . "here are right buildings" "tu sú pravé stavby"
# skcard . "I have a main meadow" "ja mám hlavnú lúku"
# skcard . "here is a good class" "tu je dobrá trieda"
# skcard . "I have low towns" "ja mám nízke mestá"
# skcard . "I have such a garden" "ja mám takú záhradu"
# skcard . "I have a fine home" "ja mám pekný dom"
# skcard . "I have good wallss" "ja mám dobré steny"
# skcard . "here are right riverbanks" "tu sú pravé brehy"
# skcard . "here are tall fingers" "tu sú vysoké prsty"
# skcard . "here are some riverbanks" "tu sú nejaké brehy"
# skcard . "I have a last evening" "ja mám posledný večer"
# skcard . "I have some town" "ja mám nejaké mesto"
# skcard . "I have a simple flower" "ja mám jednoduchý kvet"
# skcard . "I have good riverbanks" "ja mám dobré brehy"
# skcard . "here is a fine picture" "tu je pekný obraz"
# skcard . "here are main cars" "tu sú hlavné autá"
# skcard . "I have a low garden" "ja mám nízku záhradu"
skcard . "I have such classes" "ja mám také triedy"
# skcard . "I have which picture?" "ja mám ktorý obraz"
# skcard . "I have main gardens" "ja mám hlavné záhrady"
# skcard . "here are simple minutes" "tu sú jednoduché minúty"
# skcard . "here are such stations" "tu sú také stanice"
# skcard . "I have tall yards" "ja mám vysoké dvory"
# skcard . "I have such vehicles" "ja mám také vozy"
# skcard . "I have a new meadow" "ja mám novú lúku"
# skcard . "here is a last class" "tu je posledná trieda"
# skcard . "I have a right picture" "ja mám pravý obraz"
# skcard . "I have tall towns" "ja mám vysoké mestá"
# skcard . "I have good cars" "ja mám dobré autá"
# skcard . "I have wide hands" "ja mám široké ruky"
# skcard . "here is a simple car" "tu je jednoduché auto"
# skcard . "I have some yards" "ja mám nejaké dvory"
# skcard . "I have fine vehicles" "ja mám pekné vozy"
# skcard . "here are simple shops" "tu sú jednoduché obchody"
# skcard . "here is a right head" "tu je pravá hlava"
# skcard . "I have some evenings" "ja mám nejaké večery"
# skcard . "I have such a wall" "ja mám takú stenu"
# skcard . "here is a tall village" "tu je vysoká dedina"
# skcard . "here is a main wall" "tu je hlavná stena"
# skcard . "I have a good home" "ja mám dobrý dom"
# skcard . "here are low streets" "tu sú nízke ulice"
# skcard . "I have which streets?" "ja mám ktoré ulice"
# skcard . "here is a good yard" "tu je dobrý dvor"
# skcard . "here is a fine minute" "tu je pekná minúta"
# skcard . "here are such yards" "tu sú také dvory"
# skcard . "here is a simple garden" "tu je jednoduchá záhrada"
# skcard . "I have a tall price" "ja mám vysokú cenu"
# skcard . "here is a low minute" "tu je nízka minúta"
skcard . "here are wide meadows" "tu sú široké lúky"
skcard . "here are good meadows" "tu sú dobré lúky"
# skcard . "I have a new head" "ja mám novú hlavu"
# skcard . "here are simple trees" "tu sú jednoduché stromy"
# skcard . "I have a some classes" "ja mám nejaké triedy"
# skcard . "I have a new riverbank" "ja mám nový breh"
# skcard . "here are which prices?" "tu sú ktoré ceny"
# skcard . "I have a tall riverbank" "ja mám vysoký breh"
# skcard . "here is a fine street" "tu je pekná ulica"
# skcard . "I have a fine vehicle" "ja mám pekný voz"
# skcard . "I have a new street" "ja mám novú ulicu"
# skcard . "I have new evenings" "ja mám nové večery"
# skcard . "here are tall vehicles" "tu sú vysoké vozy"
skcard . "here are which meadows?" "tu sú ktoré lúky"
# skcard . "here is a wide question" "tu je široká otázka"
# skcard . "I have a right minute" "ja mám pravú minútu"
# skcard . "I have right questions" "ja mám pravé otázky"
# skcard . "I have a good wall" "ja mám dobrú stenu"
# skcard . "here is a simple class" "tu je jednoduchá trieda"
# skcard . "I have last feet" "ja mám posledné nohy"
# skcard . "here are such cars" "tu sú také autá"
# skcard . "here is such a street" "tu je taká ulica"
# skcard . "here is a wide picture" "tu je široký obraz"
# skcard . "here is which yard?" "tu je ktorý dvor"
# skcard . "I have a right building" "ja mám pravú stavbu"
# skcard . "here is a low question" "tu je nízka otázka"
# skcard . "here is some book" "tu je nejaká kniha"
# skcard . "I have last men" "ja mám posledných mužov"
# skcard . "here is such a wall" "tu je taká stena"
# skcard . "here is a tall building" "tu je vysoká stavba"
# skcard . "I have a wide fence" "ja mám široký plot"
# skcard . "I have a fine man" "ja mám pekného muža"
# skcard . "I have a tall minute" "ja mám vysokú minútu"
# skcard . "here are such forests" "tu sú také lesy"
# skcard . "here is a new home" "tu je nový dom"
# skcard . "I have a good school" "ja mám dobrú školu"
# skcard . "here are such classes" "tu sú také triedy"
# skcard . "here are fine streets" "tu sú pekné ulice"
# skcard . "here is a new fence" "tu je nový plot"
# skcard . "I have low homes" "ja mám nízke domy"
# skcard . "here are fine minutes" "tu sú pekné minúty"
# skcard . "here are which gardens?" "tu sú ktoré záhrady"
# skcard . "I have some forest" "ja mám nejaký les"
# skcard . "I have a simple book" "ja mám jednoduchú knihu"
# skcard . "I have a fine wall" "ja mám peknú stenu"
# skcard . "here are some books" "tu sú nejaké knihy"
# skcard . "here is a low shop" "tu je nízky obchod"
# skcard . "here are last villages" "tu sú posledné dediny"
# skcard . "I have such a vehicle" "ja mám taký voz"
# skcard . "here is some head" "tu je nejaká hlava"
# skcard . "I have some car" "ja mám nejaké auto"
# skcard . "I have new stations" "ja mám nové stanice"
# skcard . "I have right things" "ja mám pravé veci"
# skcard . "I have low yards" "ja mám nízke dvory"
# skcard . "here are such towns" "tu sú také mestá"
# skcard . "here is a tall minute" "tu je vysoká minúta"
# skcard . "here is a tall forest" "tu je vysoký les"
# skcard . "I have a wide classes" "ja mám široké triedy"
# skcard . "here are such trees" "tu sú také stromy"
# skcard . "I have a simple vehicle" "ja mám jednoduchý voz"
# skcard . "here is a last shop" "tu je posledný obchod"
# skcard . "here are wide fingers" "tu sú široké prsty"
# skcard . "here is a last finger" "tu je posledný prst"
# skcard . "here is a simple thing" "tu je jednoduchá vec"
# skcard . "here are such pictures" "tu sú také obrazy"
# skcard . "here is a fine building" "tu je pekná stavba"
# skcard . "I have last things" "ja mám posledné veci"
# skcard . "I have right feet" "ja mám pravé nohy"
# skcard . "here are low things" "tu sú nízke veci"
# skcard . "here are which vehicles?" "tu sú ktoré vozy"
# skcard . "I have fine buildings" "ja mám pekné stavby"
# skcard . "I have low minutes" "ja mám nízke minúty"
# skcard . "here is a simple book" "tu je jednoduchá kniha"
# skcard . "I have fine trees" "ja mám pekné stromy"
# skcard . "here is which finger?" "tu je ktorý prst"
# skcard . "I have main stations" "ja mám hlavné stanice"
# skcard . "here are right fingers" "tu sú pravé prsty"
# skcard . "here are tall towns" "tu sú vysoké mestá"
# skcard . "I have a low classes" "ja mám nízke triedy"
# skcard . "here are wide prices" "tu sú široké ceny"
# skcard . "I have fine minutes" "ja mám pekné minúty"
# skcard . "here is a simple village" "tu je jednoduchá dedina"
# skcard . "I have a right village" "ja mám pravú dedinu"
# skcard . "here is a new school" "tu je nová škola"
# skcard . "here are tall evenings" "tu sú vysoké večery"
# skcard . "here are main gardens" "tu sú hlavné záhrady"
# skcard . "I have such a station" "ja mám takú stanicu"
# skcard . "here is a main forest" "tu je hlavný les"
# skcard . "I have a main town" "ja mám hlavné mesto"
# skcard . "here is a right building" "tu je pravá stavba"
# skcard . "here is a low village" "tu je nízka dedina"
# skcard . "here is a fine yard" "tu je pekný dvor"
# skcard . "I have some cars" "ja mám nejaké autá"
# skcard . "I have a low question" "ja mám nízku otázku"
# skcard . "I have a last village" "ja mám poslednú dedinu"
# skcard . "I have a last foot" "ja mám poslednú nohu"
# skcard . "I have a right meadow" "ja mám pravú lúku"
# skcard . "I have a right class" "ja mám pravú triedu"
# skcard . "I have simple hands" "ja mám jednoduché ruky"
# skcard . "I have a simple station" "ja mám jednoduchú stanicu"
# skcard . "I have a main village" "ja mám hlavnú dedinu"
# skcard . "here are right gardens" "tu sú pravé záhrady"
# skcard . "here is a wide man" "tu je široký muž"
# skcard . "here are good pictures" "tu sú dobré obrazy"
# skcard . "I have a fine price" "ja mám peknú cenu"
# skcard . "I have a good vehicle" "ja mám dobrý voz"
# skcard . "I have such a home" "ja mám taký dom"
# skcard . "I have tall trees" "ja mám vysoké stromy"
# skcard . "I have a right wall" "ja mám pravú stenu"
# skcard . "I have low forests" "ja mám nízke lesy"
# skcard . "I have simple homes" "ja mám jednoduché domy"
# skcard . "I have last rivers" "ja mám posledné rieky"
# skcard . "here is a good wall" "tu je dobrá stena"
# skcard . "I have which fences?" "ja mám ktoré ploty"
# skcard . "here are low shops" "tu sú nízke obchody"
# skcard . "here are fine wallss" "tu sú pekné steny"
# skcard . "here are fine stations" "tu sú pekné stanice"
# skcard . "I have a tall vehicle" "ja mám vysoký voz"
# skcard . "here is a tall book" "tu je vysoká kniha"
# skcard . "here are tall fences" "tu sú vysoké ploty"
# skcard . "I have low cars" "ja mám nízke autá"
# skcard . "I have which forests?" "ja mám ktoré lesy"
# skcard . "I have fine cars" "ja mám pekné autá"
# skcard . "I have low rivers" "ja mám nízke rieky"
# skcard . "I have a low finger" "ja mám nízky prst"
# skcard . "I have a last home" "ja mám posledný dom"
# skcard . "here is a tall evening" "tu je vysoký večer"
# skcard . "here are fine vehicles" "tu sú pekné vozy"
# skcard . "I have a last flower" "ja mám posledný kvet"
# skcard . "here is a wide class" "tu je široká trieda"
# skcard . "I have right yards" "ja mám pravé dvory"
# skcard . "here are right questions" "tu sú pravé otázky"
# skcard . "I have which forest?" "ja mám ktorý les"
# skcard . "I have fine things" "ja mám pekné veci"
# skcard . "I have tall stations" "ja mám vysoké stanice"
# skcard . "here is a right shop" "tu je pravý obchod"
# skcard . "here is a good river" "tu je dobrá rieka"
# skcard . "I have a main yard" "ja mám hlavný dvor"
# skcard . "here is a main station" "tu je hlavná stanica"
# skcard . "here is a good hand" "tu je dobrá ruka"
# skcard . "I have low buildings" "ja mám nízke stavby"
# skcard . "here is a right river" "tu je pravá rieka"
# skcard . "I have such homes" "ja mám také domy"
# skcard . "I have a good village" "ja mám dobrú dedinu"
# skcard . "I have wide pictures" "ja mám široké obrazy"
# skcard . "here are new streets" "tu sú nové ulice"
# skcard . "here is a wide building" "tu je široká stavba"
# skcard . "here are which trees?" "tu sú ktoré stromy"
# skcard . "here is a wide wall" "tu je široká stena"
# skcard . "I have new pictures" "ja mám nové obrazy"
# skcard . "I have which flower?" "ja mám ktorý kvet"
# skcard . "I have tall gardens" "ja mám vysoké záhrady"
# skcard . "I have a fine village" "ja mám peknú dedinu"
# skcard . "here are fine questions" "tu sú pekné otázky"
# skcard . "here is a low book" "tu je nízka kniha"
# skcard . "here are wide streets" "tu sú široké ulice"
# skcard . "I have a new thing" "ja mám novú vec"
# skcard . "I have right heads" "ja mám pravé hlavy"
# skcard . "I have wide cars" "ja mám široké autá"
# skcard . "I have right flowers" "ja mám pravé kvety"
# skcard . "I have main prices" "ja mám hlavné ceny"
# skcard . "here is a low foot" "tu je nízka noha"
# skcard . "here are low pictures" "tu sú nízke obrazy"
# skcard . "here are such riverbanks" "tu sú také brehy"
# skcard . "I have a low evening" "ja mám nízky večer"
# skcard . "I have main cars" "ja mám hlavné autá"
# skcard . "here are new wallss" "tu sú nové steny"
# skcard . "I have a low foot" "ja mám nízku nohu"
# skcard . "I have which shop?" "ja mám ktorý obchod"
# skcard . "I have good men" "ja mám dobrých mužov"
# skcard . "I have some forests" "ja mám nejaké lesy"
# skcard . "I have a main riverbank" "ja mám hlavný breh"
# skcard . "I have a wide question" "ja mám širokú otázku"
# skcard . "I have a good foot" "ja mám dobrú nohu"
skcard . "here are low meadows" "tu sú nízke lúky"
# skcard . "here is a fine class" "tu je pekná trieda"
# skcard . "I have simple pictures" "ja mám jednoduché obrazy"
# skcard . "here is a simple foot" "tu je jednoduchá noha"
# skcard . "I have fine streets" "ja mám pekné ulice"
# skcard . "I have new things" "ja mám nové veci"
# skcard . "I have simple fences" "ja mám jednoduché ploty"
# skcard . "I have such a shop" "ja mám taký obchod"
# skcard . "here is a right home" "tu je pravý dom"
# skcard . "I have which heads?" "ja mám ktoré hlavy"
# skcard . "here is a new village" "tu je nová dedina"
# skcard . "here is a main riverbank" "tu je hlavný breh"
skcard . "I have a simple gentleman" "ja mám jednoduchého pána"
skcard . "here are right gentlemen" "tu sú praví páni"
skcard . "I have some gentleman" "ja mám nejakého pána"
skcard . "I have which gentleman?" "ja mám ktorého pána"
skcard . "I have a last gentleman" "ja mám posledného pána"
skcard . "here are good gentlemen" "tu sú dobrí páni"
skcard . "I have simple gentlemen" "ja mám jednoduchých pánov"
skcard . "here is a last gentleman" "tu je posledný pán"
skcard . "here are fine gentlemen" "tu sú pekní páni"
skcard . "I have low gentlemen" "ja mám nízkych pánov"
skcard . "I have such a gentleman" "ja mám takého pána"
skcard . "I have wide gentlemen" "ja mám širokých pánov"
skcard . "I have a fine gentleman" "ja mám pekného pána"
skcard . "I have a wide gentleman" "ja mám širokého pána"
skcard . "here is a new gentleman" "tu je nový pán"
skcard . "I have a main gentleman" "ja mám hlavného pána"
skcard . "I have a new gentleman" "ja mám nového pána"
skcard . "here are some gentlemen" "tu sú nejakí páni"
skcard . "here is a main gentleman" "tu je hlavný pán"
skcard . "I have some gentlemen" "ja mám nejakých pánov"
skcard . "here is which gentleman?" "tu je ktorý pán"
skcard . "here are main gentlemen" "tu sú hlavní páni"
skcard . "here is a simple gentleman" "tu je jednoduchý pán"
skcard . "I have last gentlemen" "ja mám posledných pánov"
skcard . "here is a low gentleman" "tu je nízky pán"
skcard . "I have a good gentleman" "ja mám dobrého pána"
skcard . "here are new gentlemen" "tu sú noví páni"
skcard . "I have a low gentleman" "ja mám nízkeho pána"
skcard . "here is a fine gentleman" "tu je pekný pán"
skcard . "here is a good gentleman" "tu je dobrý pán"
skcard . "I have fine gentlemen" "ja mám pekných pánov"
skcard . "here are tall gentlemen" "tu sú vysokí páni"
skcard . "I have right gentlemen" "ja mám pravých pánov"
skcard . "here are such gentlemen" "tu sú takí páni"
skcard . "here is a tall gentleman" "tu je vysoký pán"
skcard . "here is some gentleman" "tu je nejaký pán"
skcard . "I have which gentlemen?" "ja mám ktorých pánov"
skcard . "here is a wide gentleman" "tu je široký pán"
skcard . "here are low gentlemen" "tu sú nízki páni"
skcard . "here are which gentlemen?" "tu sú ktorí páni"
skcard . "here is such a gentleman" "tu je taký pán"
skcard . "here are wide gentlemen" "tu sú širokí páni"
skcard . "here is a right gentleman" "tu je pravý pán"
skcard . "I have such gentlemen" "ja mám takých pánov"
skcard . "here are simple gentlemen" "tu sú jednoduchí páni"
skcard . "I have new gentlemen" "ja mám nových pánov"
skcard . "here are last gentlemen" "tu sú poslední páni"
skcard . "I have good gentlemen" "ja mám dobrých pánov"
skcard . "I have a right gentleman" "ja mám pravého pána"
skcard . "I have main gentlemen" "ja mám hlavných pánov"
skcard . "I have a tall gentleman" "ja mám vysokého pána"
skcard . "I have tall gentlemen" "ja mám vysokých pánov"
skcard . "I have which class?" "ja mám ktorú triedu"
skcard . "here is which class?" "tu je ktorá trieda"
skcard . "I have which classes?" "ja mám ktoré triedy"
skcard . "here are which classes?" "tu sú ktoré triedy"
skcard . "I have simple classes" "ja mám jednoduché triedy"
skcard . "I have last classes" "ja mám posledné triedy"
skcard . "I have tall classes" "ja mám vysoké triedy"
skcard . "I have fine classes" "ja mám pekné triedy"
skcard . "I have good classes" "ja mám dobré triedy"
skcard . "I have new classes" "ja mám nové triedy"
skcard . "I have right classes" "ja mám pravé triedy"
skcard . "I have main classes" "ja mám hlavné triedy"
skcard . "I have some classes" "ja mám nejaké triedy"
skcard . "I have wide classes" "ja mám široké triedy"
skcard . "I have low classes" "ja mám nízke triedy"
