skcard . "y'all know gentlemen" "vy poznáte pány"
skcard . "I am looking for gentlemen" "ja hľadám pány"
skcard . "we don't have any gentlemen" "my nemáme pány"
skcard . "y'all know a gentleman" "vy poznáte pán"
skcard . "you have a gentleman" "ty máš pán"
skcard . "y'all are turning gentlemen" "vy obrátite pány"
skcard . "y'all are turning a gentleman" "vy obrátite pán"
skcard . "he doesn't have any gentlemen" "on nemá pány"
skcard . "they have a gentleman" "oni majú pán"
skcard . "I have gentlemen" "ja mám pány"
skcard . "I see a gentleman" "ja vidím pán"
skcard . "you have gentlemen" "ty máš pány"
skcard . "we don't have a gentleman" "my nemáme pán"
skcard . "he doesn't have a gentleman" "on nemá pán"
skcard . "they have gentlemen" "oni majú pány"
skcard . "I am looking for a gentleman" "ja hľadám pán"
skcard . "I see gentlemen" "ja vidím pány"
skcard . "I have a gentleman" "ja mám pán"
skcard . "I need gentlemen" "ja potrebujem pány"
skcard . "I need a gentleman" "ja potrebujem pán"
skcard . "I am looking for the forest" "ja hľadám les"
skcard . "y'all are turning stations" "vy obrátite stanice"
skcard . "I am looking for flowers" "ja hľadám kvety"
skcard . "we have no car" "my nemáme auto"
skcard . "I am looking for minutes" "ja hľadám minúty"
skcard . "he has no homes" "on nemá domy"
skcard . "I have walls" "ja mám steny"
skcard . "you have prices" "ty máš ceny"
skcard . "they have classrooms" "oni majú triedy"
skcard . "we have no evenings" "my nemáme večery"
skcard . "I see the yards" "ja vidím dvory"
skcard . "y'all know the feet" "vy poznáte nohy"
skcard . "y'all are turning trees" "vy obrátite stromy"
skcard . "you have yards" "ty máš dvory"
skcard . "they have an evening" "oni majú večer"
skcard . "we have no river" "my nemáme rieku"
skcard . "I am looking for the picture" "ja hľadám obraz"
skcard . "we have no forest" "my nemáme les"
skcard . "he has no street" "on nemá ulicu"
skcard . "they have a town" "oni majú mesto"
skcard . "he has no hand" "on nemá ruku"
skcard . "I am looking for the things" "ja hľadám veci"
skcard . "I see the forest" "ja vidím les"
skcard . "I have a classroom" "ja mám triedu"
skcard . "y'all are turning the street" "vy obrátite ulicu"
skcard . "they have the book" "oni majú knihu"
skcard . "I have a garden" "ja mám záhradu"
skcard . "they have a school" "oni majú školu"
skcard . "you have a river" "ty máš rieku"
skcard . "y'all know the picture" "vy poznáte obraz"
skcard . "he has no classroom" "on nemá triedu"
skcard . "he has no tree" "on nemá strom"
skcard . "I have a river" "ja mám rieku"
skcard . "they have a hand" "oni majú ruku"
skcard . "they have a tree" "oni majú strom"
skcard . "you have homes" "ty máš domy"
skcard . "they have trees" "oni majú stromy"
skcard . "he has no meadow" "on nemá lúku"
skcard . "you have evenings" "ty máš večery"
skcard . "y'all know the evenings" "vy poznáte večery"
skcard . "I see the hand" "ja vidím ruku"
skcard . "I see the thing" "ja vidím vec"
skcard . "I have heads" "ja mám hlavy"
skcard . "I have an evening" "ja mám večer"
skcard . "I am looking for the yard" "ja hľadám dvor"
skcard . "you have the fingers" "ty máš prsty"
skcard . "I see the garden" "ja vidím záhradu"
skcard . "y'all know the yards" "vy poznáte dvory"
skcard . "he has no feet" "on nemá nohy"
skcard . "y'all are turning the pictures" "vy obrátite obrazy"
skcard . "y'all know the rivers" "vy poznáte rieky"
skcard . "y'all know the fences" "vy poznáte ploty"
skcard . "they have a head" "oni majú hlavu"
skcard . "y'all are turning the villages" "vy obrátite dediny"
skcard . "y'all know the meadow" "vy poznáte lúku"
skcard . "I have a foot" "ja mám nohu"
skcard . "they have a home" "oni majú dom"
skcard . "he has no trees" "on nemá stromy"
skcard . "I have a minute" "ja mám minútu"
skcard . "you have the things" "ty máš veci"
skcard . "y'all know the hand" "vy poznáte ruku"
skcard . "y'all are turning the meadow" "vy obrátite lúku"
skcard . "y'all are turning the hand" "vy obrátite ruku"
skcard . "I see the minutes" "ja vidím minúty"
skcard . "y'all are turning the forest" "vy obrátite les"
skcard . "he has no streets" "on nemá ulice"
skcard . "we have no hand" "my nemáme ruku"
skcard . "we have no school" "my nemáme školu"
skcard . "I am looking for the car" "ja hľadám auto"
skcard . "he has no school" "on nemá školu"
skcard . "y'all know the town" "vy poznáte mesto"
skcard . "I am looking for trees" "ja hľadám stromy"
skcard . "they have heads" "oni majú hlavy"
skcard . "he has no heads" "on nemá hlavy"
skcard . "he has no minutes" "on nemá minúty"
skcard . "y'all are turning the yard" "vy obrátite dvor"
skcard . "you have a garden" "ty máš záhradu"
skcard . "I am looking for the vehicles" "ja hľadám vozy"
skcard . "we have no yards" "my nemáme dvory"
skcard . "I have the shops" "ja mám obchody"
skcard . "we have no book" "my nemáme knihu"
skcard . "y'all know the foot" "vy poznáte nohu"
skcard . "I see the shop" "ja vidím obchod"
skcard . "you have a street" "ty máš ulicu"
skcard . "we have no forests" "my nemáme lesy"
skcard . "y'all know the stations" "vy poznáte stanice"
skcard . "y'all are turning the river bank" "vy obrátite breh"
skcard . "I have a price" "ja mám cenu"
skcard . "he has no thing" "on nemá vec"
skcard . "y'all are turning the thing" "vy obrátite vec"
skcard . "I have a question" "ja mám otázku"
skcard . "I am looking for the stations" "ja hľadám stanice"
skcard . "I see the finger" "ja vidím prst"
skcard . "I am looking for the river" "ja hľadám rieku"
skcard . "y'all know the prices" "vy poznáte ceny"
skcard . "they have buildings" "oni majú stavby"
skcard . "I have a village" "ja mám dedinu"
skcard . "I am looking for the yards" "ja hľadám dvory"
skcard . "I am looking for the garden" "ja hľadám záhradu"
skcard . "y'all are turning the river banks" "vy obrátite brehy"
skcard . "you have the thing" "ty máš vec"
skcard . "I see the villages" "ja vidím dediny"
skcard . "we have no village" "my nemáme dedinu"
skcard . "they have the vehicles" "oni majú vozy"
skcard . "I have a town" "ja mám mesto"
skcard . "they have rivers" "oni majú rieky"
skcard . "y'all know the gardens" "vy poznáte záhrady"
skcard . "I am looking for the village" "ja hľadám dedinu"
skcard . "I have the towns" "ja mám mestá"
skcard . "y'all know the flowers" "vy poznáte kvety"
skcard . "we have no picture" "my nemáme obraz"
skcard . "y'all are turning the garden" "vy obrátite záhradu"
skcard . "they have a meadow" "oni majú lúku"
skcard . "y'all know the questions" "vy poznáte otázky"
skcard . "you have a classroom" "ty máš triedu"
skcard . "y'all know the forests" "vy poznáte lesy"
skcard . "I have a school" "ja mám školu"
skcard . "I am looking for the gardens" "ja hľadám záhrady"
skcard . "I am looking for the foot" "ja hľadám nohu"
skcard . "I am looking for the meadow" "ja hľadám lúku"
skcard . "I see the town" "ja vidím mesto"
skcard . "I have a yard" "ja mám dvor"
skcard . "they have a garden" "oni majú záhradu"
skcard . "I am looking for a finger" "ja hľadám prst"
skcard . "I see the streets" "ja vidím ulice"
skcard . "y'all know the car" "vy poznáte auto"
skcard . "I see the schools" "ja vidím školy"
skcard . "you have the picture" "ty máš obraz"
skcard . "I am looking for the villages" "ja hľadám dediny"
skcard . "y'all are turning the towns" "vy obrátite mestá"
skcard . "y'all know the building" "vy poznáte stavbu"
skcard . "y'all are turning feet" "vy obrátite nohy"
skcard . "you have a yard" "ty máš dvor"
skcard . "we have no shop" "my nemáme obchod"
skcard . "we have no fingers" "my nemáme prsty"
skcard . "I am looking for a question" "ja hľadám otázku"
skcard . "y'all are turning the prices" "vy obrátite ceny"
skcard . "I have a head" "ja mám hlavu"
skcard . "he has no station" "on nemá stanicu"
skcard . "he has no evening" "on nemá večer"
skcard . "we have no home" "my nemáme dom"
skcard . "y'all know the school" "vy poznáte školu"
skcard . "I see a tree" "ja vidím strom"
skcard . "y'all know the book" "vy poznáte knihu"
skcard . "you have a tree" "ty máš strom"
skcard . "I am looking for the evenings" "ja hľadám večery"
skcard . "they have a class" "oni majú triedu"
skcard . "he has no things" "on nemá veci"
skcard . "he has no gardens" "on nemá záhrady"
skcard . "I have questions" "ja mám otázky"
skcard . "you have a hand" "ty máš ruku"
skcard . "they have the picture" "oni majú obraz"
skcard . "he has no fence" "on nemá plot"
skcard . "you have a shop" "ty máš obchod"
skcard . "he has no stations" "on nemá stanice"
skcard . "I am looking for the pictures" "ja hľadám obrazy"
skcard . "we have no yard" "my nemáme dvor"
skcard . "I am looking for a wall" "ja hľadám stenu"
skcard . "y'all are turning the car" "vy obrátite auto"
skcard . "you have river banks" "ty máš brehy"
skcard . "I am looking for a home" "ja hľadám dom"
skcard . "I see the car" "ja vidím auto"
skcard . "I see the street" "ja vidím ulicu"
skcard . "you have rivers" "ty máš rieky"
skcard . "they have a shop" "oni majú obchod"
skcard . "I am looking for the school" "ja hľadám školu"
skcard . "we have no foot" "my nemáme nohu"
skcard . "I see fingers" "ja vidím prsty"
skcard . "he has no home" "on nemá dom"
skcard . "they have flowers" "oni majú kvety"
skcard . "you have questions" "ty máš otázky"
skcard . "I have a vehicle" "ja mám voz"
skcard . "y'all know the schools" "vy poznáte školy"
skcard . "I have river banks" "ja mám brehy"
skcard . "you have a foot" "ty máš nohu"
skcard . "y'all know the river bank" "vy poznáte breh"
skcard . "I see the stations" "ja vidím stanice"
skcard . "I see the school" "ja vidím školu"
skcard . "I have a meadow" "ja mám lúku"
skcard . "he has no cars" "on nemá autá"
skcard . "they have a river" "oni majú rieku"
skcard . "he has no books" "on nemá knihy"
skcard . "I have a picture" "ja mám obraz"
skcard . "y'all are turning the village" "vy obrátite dedinu"
skcard . "you have flowers" "ty máš kvety"
skcard . "they have minutes" "oni majú minúty"
skcard . "y'all know the cars" "vy poznáte autá"
skcard . "I am looking for a vehicle" "ja hľadám voz"
skcard . "y'all are turning the classrooms" "vy obrátite triedy"
skcard . "I have villages" "ja mám dediny"
skcard . "we have no trees" "my nemáme stromy"
skcard . "we have no river banks" "my nemáme brehy"
skcard . "y'all know the classrooms" "vy poznáte triedy"
skcard . "y'all know the village" "vy poznáte dedinu"
skcard . "we have no hands" "my nemáme ruky"
skcard . "you have streets" "ty máš ulice"
skcard . "you have forests" "ty máš lesy"
skcard . "he has no wall" "on nemá stenu"
skcard . "y'all know the price" "vy poznáte cenu"
skcard . "they have yards" "oni majú dvory"
skcard . "I have a tree" "ja mám strom"
skcard . "I have a thing" "ja mám vec"
skcard . "I see a river" "ja vidím rieku"
skcard . "y'all are turning the book" "vy obrátite knihu"
skcard . "he has no question" "on nemá otázku"
skcard . "we have no flowers" "my nemáme kvety"
skcard . "y'all are turning the homes" "vy obrátite domy"
skcard . "you have vehicles" "ty máš vozy"
skcard . "y'all know the vehicle" "vy poznáte voz"
skcard . "y'all are turning the flower" "vy obrátite kvet"
skcard . "they have a price" "oni majú cenu"
skcard . "I see a station" "ja vidím stanicu"
skcard . "I see the river bank" "ja vidím breh"
skcard . "you have towns" "ty máš mestá"
skcard . "I am looking for homes" "ja hľadám domy"
skcard . "they have stations" "oni majú stanice"
skcard . "I see hands" "ja vidím ruky"
skcard . "I have a shop" "ja mám obchod"
skcard . "he has no car" "on nemá auto"
skcard . "I am looking for fences" "ja hľadám ploty"
skcard . "he has no river" "on nemá rieku"
skcard . "he has no hands" "on nemá ruky"
skcard . "I have stations" "ja mám stanice"
skcard . "I see cars" "ja vidím autá"
skcard . "I have a river bank" "ja mám breh"
skcard . "I am looking for the thing" "ja hľadám vec"
skcard . "I have evenings" "ja mám večery"
skcard . "we have no garden" "my nemáme záhradu"
skcard . "I have a man" "ja mám muža"
skcard . "I have men" "ja mám mužov"
skcard . "I see the head" "ja vidím hlavu"
skcard . "I am looking for the forests" "ja hľadám lesy"
skcard . "I see the classroom" "ja vidím triedu"
skcard . "we have no fence" "my nemáme plot"
skcard . "they have the thing" "oni majú vec"
skcard . "I am looking for a minute" "ja hľadám minútu"
skcard . "I have hands" "ja mám ruky"
skcard . "we have no river bank" "my nemáme breh"
skcard . "I see forests" "ja vidím lesy"
skcard . "we have no flower" "my nemáme kvet"
skcard . "we have no thing" "my nemáme vec"
skcard . "I am looking for a fence" "ja hľadám plot"
skcard . "I am looking for the meadows" "ja hľadám lúky"
skcard . "I have a building" "ja mám stavbu"
skcard . "we have no books" "my nemáme knihy"
skcard . "I have a car" "ja mám auto"
skcard . "you have a wall" "ty máš stenu"
skcard . "y'all are turning the home" "vy obrátite dom"
skcard . "we have no heads" "my nemáme hlavy"
skcard . "I have fingers" "ja mám prsty"
skcard . "y'all are turning the wall" "vy obrátite stenu"
skcard . "I see the shops" "ja vidím obchody"
skcard . "he has no yards" "on nemá dvory"
skcard . "they have fences" "oni majú ploty"
skcard . "I have a flower" "ja mám kvet"
skcard . "you have feet" "ty máš nohy"
skcard . "I see walls" "ja vidím steny"
skcard . "I have flowers" "ja mám kvety"
skcard . "they have feet" "oni majú nohy"
skcard . "I have a station" "ja mám stanicu"
skcard . "they have cars" "oni majú autá"
skcard . "you have a price" "ty máš cenu"
skcard . "y'all are turning the tree" "vy obrátite strom"
skcard . "I am looking for the head" "ja hľadám hlavu"
skcard . "they have a yard" "oni majú dvor"
skcard . "I am looking for questions" "ja hľadám otázky"
skcard . "we have no things" "my nemáme veci"
skcard . "I am looking for the man" "ja hľadám muža"
skcard . "I am looking for men" "ja hľadám mužov"
skcard . "they have the foot" "oni majú nohu"
skcard . "you have hands" "ty máš ruky"
skcard . "y'all know the villages" "vy poznáte dediny"
skcard . "I have the book" "ja mám knihu"
skcard . "y'all are turning the shop" "vy obrátite obchod"
skcard . "you have a meadow" "ty máš lúku"
skcard . "y'all are turning the flowers" "vy obrátite kvety"
skcard . "I see questions" "ja vidím otázky"
skcard . "y'all are turning the price" "vy obrátite cenu"
skcard . "I am looking for the town" "ja hľadám mesto"
skcard . "y'all are turning forests" "vy obrátite lesy"
skcard . "y'all know the river banks" "vy poznáte brehy"
skcard . "I see feet" "ja vidím nohy"
skcard . "I have a home" "ja mám dom"
skcard . "he has no rivers" "on nemá rieky"
skcard . "we don't have a minute" "my nemáme minútu"
skcard . "he has no flower" "on nemá kvet"
skcard . "he has no fences" "on nemá ploty"
skcard . "y'all are turning the man" "vy obrátite muža"
skcard . "y'all are turning the men" "vy obrátite mužov"
skcard . "I see the towns" "ja vidím mestá"
skcard . "we have no evening" "my nemáme večer"
skcard . "I see home" "ja vidím dom"
skcard . "you have buildings" "ty máš stavby"
skcard . "they have a river bank" "oni majú breh"
skcard . "y'all know the vehicles" "vy poznáte vozy"
skcard . "I see a man" "ja vidím muža"
skcard . "I see men" "ja vidím mužov"
skcard . "they have towns" "oni majú mestá"
skcard . "I am looking for the classroom" "ja hľadám triedu"
skcard . "they have a flower" "oni majú kvet"
skcard . "y'all are turning the streets" "vy obrátite ulice"
skcard . "I am looking for the price" "ja hľadám cenu"
skcard . "we have no classroom" "my nemáme triedu"
skcard . "he has no river bank" "on nemá breh"
skcard . "he has no head" "on nemá hlavu"
skcard . "you have a forest" "ty máš les"
skcard . "we have no station" "my nemáme stanicu"
skcard . "I see the price" "ja vidím cenu"
skcard . "y'all are turning the classroom" "vy obrátite triedu"
skcard . "you have a village" "ty máš dedinu"
skcard . "I see rivers" "ja vidím rieky"
skcard . "I see a question" "ja vidím otázku"
skcard . "he has no meadows" "on nemá lúky"
skcard . "we have no tree" "my nemáme strom"
skcard . "y'all know the wall" "vy poznáte stenu"
skcard . "he has no walls" "on nemá steny"
skcard . "I see the buildings" "ja vidím stavby"
skcard . "I have the things" "ja mám veci"
skcard . "y'all know the street" "vy poznáte ulicu"
skcard . "I have a finger" "ja mám prst"
skcard . "y'all know the yard" "vy poznáte dvor"
skcard . "y'all know the minutes" "vy poznáte minúty"
skcard . "we have no gardens" "my nemáme záhrady"
skcard . "y'all are turning the picture" "vy obrátite obraz"
skcard . "you have the classrooms" "ty máš triedy"
skcard . "they have the fingers" "oni majú prsty"
skcard . "I have feet" "ja mám nohy"
skcard . "I am looking for walls" "ja hľadám steny"
skcard . "y'all know the fence" "vy poznáte plot"
skcard . "I see the village" "ja vidím dedinu"
skcard . "y'all are turning the rivers" "vy obrátite rieky"
skcard . "I am looking for the rivers" "ja hľadám rieky"
skcard . "I see a yard" "ja vidím dvor"
skcard . "they have the station" "oni majú stanicu"
skcard . "we have no street" "my nemáme ulicu"
skcard . "I see flowers" "ja vidím kvety"
skcard . "I am looking for the feet" "ja hľadám nohy"
skcard . "y'all are turning a head" "vy obrátite hlavu"
skcard . "I see a minute" "ja vidím minútu"
skcard . "he has no picture" "on nemá obraz"
skcard . "I have the prices" "ja mám ceny"
skcard . "y'all are turning the vehicle" "vy obrátite voz"
skcard . "y'all know the river" "vy poznáte rieku"
skcard . "they have a village" "oni majú dedinu"
skcard . "I am looking for heads" "ja hľadám hlavy"
skcard . "y'all know the pictures" "vy poznáte obrazy"
skcard . "y'all are turning the fences" "vy obrátite ploty"
skcard . "y'all are turning the fence" "vy obrátite plot"
skcard . "I see the fence" "ja vidím plot"
skcard . "I am looking for a tree" "ja hľadám strom"
skcard . "we have no rivers" "my nemáme rieky"
skcard . "he has no foot" "on nemá nohu"
skcard . "I have the cars" "ja mám autá"
skcard . "y'all know the streets" "vy poznáte ulice"
skcard . "I am looking for the prices" "ja hľadám ceny"
skcard . "y'all know the head" "vy poznáte hlavu"
skcard . "they have walls" "oni majú steny"
skcard . "he has no prices" "on nemá ceny"
skcard . "you have an evening" "ty máš večer"
skcard . "y'all know the thing" "vy poznáte vec"
skcard . "he has no town" "on nemá mesto"
skcard . "y'all know the trees" "vy poznáte stromy"
skcard . "y'all know the home" "vy poznáte dom"
skcard . "he has no evenings" "on nemá večery"
skcard . "we have no feet" "my nemáme nohy"
skcard . "y'all know the finger" "vy poznáte prst"
skcard . "he has no yard" "on nemá dvor"
skcard . "y'all know the tree" "vy poznáte strom"
skcard . "I have yards" "ja mám dvory"
skcard . "I see an evening" "ja vidím večer"
skcard . "I am looking for the street" "ja hľadám ulicu"
skcard . "you have a vehicle" "ty máš voz"
skcard . "you have books" "ty máš knihy"
skcard . "I have schools" "ja mám školy"
skcard . "they have the pictures" "oni majú obrazy"
skcard . "we have no meadows" "my nemáme lúky"
skcard . "y'all know towns" "vy poznáte mestá"
skcard . "y'all are turning the buildings" "vy obrátite stavby"
skcard . "they have a minute" "oni majú minútu"
skcard . "you have a finger" "ty máš prst"
skcard . "I am looking for the book" "ja hľadám knihu"
skcard . "I have a hand" "ja mám ruku"
skcard . "you have heads" "ty máš hlavy"
skcard . "you have shops" "ty máš obchody"
skcard . "we have no buildings" "my nemáme stavby"
skcard . "I am looking for an evening" "ja hľadám večer"
skcard . "I am looking for the schools" "ja hľadám školy"
skcard . "y'all know the fingers" "vy poznáte prsty"
skcard . "you have a school" "ty máš školu"
skcard . "y'all are turning the books" "vy obrátite knihy"
skcard . "I am looking for a hand" "ja hľadám ruku"
skcard . "y'all know the walls" "vy poznáte steny"
skcard . "you have a flower" "ty máš kvet"
skcard . "we have no town" "my nemáme mesto"
skcard . "they have a fence" "oni majú plot"
skcard . "I have trees" "ja mám stromy"
skcard . "you have cars" "ty máš autá"
skcard . "you have a fence" "ty máš plot"
skcard . "you have meadows" "ty máš lúky"
skcard . "they have a question" "oni majú otázku"
skcard . "I am looking for the shop" "ja hľadám obchod"
skcard . "I am looking for the cars" "ja hľadám autá"
skcard . "I am looking for the streets" "ja hľadám ulice"
skcard . "I am looking for the buildings" "ja hľadám stavby"
skcard . "we have no shops" "my nemáme obchody"
skcard . "they have a car" "oni majú auto"
skcard . "we have no stations" "my nemáme stanice"
skcard . "y'all are turning a question" "vy obrátite otázku"
skcard . "I am looking for books" "ja hľadám knihy"
skcard . "we have no classrooms" "my nemáme triedy"
skcard . "you have a home" "ty máš dom"
skcard . "I am looking for the towns" "ja hľadám mestá"
skcard . "y'all know the question" "vy poznáte otázku"
skcard . "y'all are turning the station" "vy obrátite stanicu"
skcard . "we have no vehicle" "my nemáme voz"
skcard . "we have no homes" "my nemáme domy"
skcard . "y'all are turning the gardens" "vy obrátite záhrady"
skcard . "they have hands" "oni majú ruky"
skcard . "I have gardens" "ja mám záhrady"
skcard . "I have forests" "ja mám lesy"
skcard . "I see the pictures" "ja vidím obrazy"
skcard . "I see the building" "ja vidím stavbu"
skcard . "they have villages" "oni majú dediny"
skcard . "he has no buildings" "on nemá stavby"
skcard . "y'all are turning heads" "vy obrátite hlavy"
skcard . "you have a question" "ty máš otázku"
skcard . "they have a building" "oni majú stavbu"
skcard . "they have forests" "oni majú lesy"
skcard . "y'all are turning the walls" "vy obrátite steny"
skcard . "I see the books" "ja vidím knihy"
skcard . "y'all are turning the shops" "vy obrátite obchody"
skcard . "y'all know the buildings" "vy poznáte stavby"
skcard . "you have trees" "ty máš stromy"
skcard . "I see a meadow" "ja vidím lúku"
skcard . "they have a forest" "oni majú les"
skcard . "y'all are turning the fingers" "vy obrátite prsty"
skcard . "he has no man" "on nemá muža"
skcard . "he has no men" "on nemá mužov"
skcard . "you have the book" "ty máš knihu"
skcard . "y'all know things" "vy poznáte veci"
skcard . "y'all are turning the cars" "vy obrátite autá"
skcard . "you have gardens" "ty máš záhrady"
skcard . "y'all are turning things" "vy obrátite veci"
skcard . "we have no villages" "my nemáme dediny"
skcard . "they have a wall" "oni majú stenu"
skcard . "we have no man" "my nemáme muža"
skcard . "we have no men" "my nemáme mužov"
skcard . "we have no walls" "my nemáme steny"
skcard . "they have a vehicle" "oni majú voz"
skcard . "I am looking for the river banks" "ja hľadám brehy"
skcard . "you have a man" "ty máš muža"
skcard . "you have men" "ty máš mužov"
skcard . "he has no fingers" "on nemá prsty"
skcard . "I have rivers" "ja mám rieky"
skcard . "y'all know the classroom" "vy poznáte triedu"
skcard . "he has no flowers" "on nemá kvety"
skcard . "I have minutes" "ja mám minúty"
skcard . "he has no vehicles" "on nemá vozy"
skcard . "I am looking for classrooms" "ja hľadám triedy"
skcard . "we have no fences" "my nemáme ploty"
skcard . "I see the foot" "ja vidím nohu"
skcard . "y'all know the heads" "vy poznáte hlavy"
skcard . "we have no minutes" "my nemáme minúty"
skcard . "I see the homes" "ja vidím domy"
skcard . "y'all know the shops" "vy poznáte obchody"
skcard . "you have villages" "ty máš dediny"
skcard . "I see a vehicle" "ja vidím voz"
skcard . "he has no forest" "on nemá les"
skcard . "they have streets" "oni majú ulice"
skcard . "y'all know the flower" "vy poznáte kvet"
skcard . "we have no schools" "my nemáme školy"
skcard . "you have a town" "ty máš mesto"
skcard . "I see the wall" "ja vidím stenu"
skcard . "I am looking for a building" "ja hľadám stavbu"
skcard . "I have homes" "ja mám domy"
skcard . "they have homes" "oni majú domy"
skcard . "he has no village" "on nemá dedinu"
skcard . "we have no pictures" "my nemáme obrazy"
skcard . "they have river banks" "oni majú brehy"
skcard . "y'all are turning the schools" "vy obrátite školy"
skcard . "y'all know the meadows" "vy poznáte lúky"
skcard . "they have shops" "oni majú obchody"
skcard . "y'all know the homes" "vy poznáte domy"
skcard . "I see the evenings" "ja vidím večery"
skcard . "I see the classrooms" "ja vidím triedy"
skcard . "you have walls" "ty máš steny"
skcard . "they have gardens" "oni majú záhrady"
skcard . "he has no finger" "on nemá prst"
skcard . "y'all are turning the minutes" "vy obrátite minúty"
skcard . "he has no shop" "on nemá obchod"
skcard . "we have no question" "my nemáme otázku"
skcard . "you have the pictures" "ty máš obrazy"
skcard . "I have the classrooms" "ja mám triedy"
skcard . "I see fences" "ja vidím ploty"
skcard . "he has no garden" "on nemá záhradu"
skcard . "we have no finger" "my nemáme prst"
skcard . "y'all know the forest" "vy poznáte les"
skcard . "I have the books" "ja mám knihy"
skcard . "I have the pictures" "ja mám obrazy"
skcard . "y'all are turning the school" "vy obrátite školu"
skcard . "y'all know the books" "vy poznáte knihy"
skcard . "I see gardens" "ja vidím záhrady"
skcard . "they have books" "oni majú knihy"
skcard . "they have things" "oni majú veci"
skcard . "you have a river bank" "ty máš breh"
skcard . "I have meadows" "ja mám lúky"
skcard . "you have a minute" "ty máš minútu"
skcard . "you have a head" "ty máš hlavu"
skcard . "y'all are turning the evenings" "vy obrátite večery"
skcard . "they have the street" "oni majú ulicu"
skcard . "I am looking for the river bank" "ja hľadám breh"
skcard . "they have the prices" "oni majú ceny"
skcard . "he has no towns" "on nemá mestá"
skcard . "we have no streets" "my nemáme ulice"
skcard . "we have no prices" "my nemáme ceny"
skcard . "he has no book" "on nemá knihu"
skcard . "they have questions" "oni majú otázky"
skcard . "y'all are turning the building" "vy obrátite stavbu"
skcard . "y'all are turning the vehicles" "vy obrátite vozy"
skcard . "you have schools" "ty máš školy"
skcard . "I have a wall" "ja mám stenu"
skcard . "we have no towns" "my nemáme mestá"
skcard . "I see the vehicles" "ja vidím vozy"
skcard . "I have streets" "ja mám ulice"
skcard . "I see the heads" "ja vidím hlavy"
skcard . "they have meadows" "oni majú lúky"
skcard . "I have a forest" "ja mám les"
skcard . "they have the finger" "oni majú prst"
skcard . "I see trees" "ja vidím stromy"
skcard . "we have no price" "my nemáme cenu"
skcard . "he has no building" "on nemá stavbu"
skcard . "he has no forests" "on nemá lesy"
skcard . "y'all are turning the foot" "vy obrátite nohu"
skcard . "he has no shops" "on nemá obchody"
skcard . "you have a building" "ty máš stavbu"
skcard . "we have no vehicles" "my nemáme vozy"
skcard . "y'all are turning the yards" "vy obrátite dvory"
skcard . "I see the prices" "ja vidím ceny"
skcard . "I am looking for shops" "ja hľadám obchody"
skcard . "I am looking for the flower" "ja hľadám kvet"
skcard . "I have a fence" "ja mám plot"
skcard . "he has no price" "on nemá cenu"
skcard . "y'all are turning the hands" "vy obrátite ruky"
skcard . "they have the man" "oni majú muža"
skcard . "they have the men" "oni majú muovž"
skcard . "y'all are turning the meadows" "vy obrátite lúky"
skcard . "I am looking for the station" "ja hľadám stanicu"
skcard . "we have no meadow" "my nemáme lúku"
skcard . "you have minutes" "ty máš minúty"
skcard . "we have no questions" "my nemáme otázky"
skcard . "you have a car" "ty máš auto"
skcard . "you have stations" "ty máš stanice"
skcard . "they have schools" "oni majú školy"
skcard . "y'all know the man" "vy poznáte muža"
skcard . "y'all know the men" "vy poznáte mužov"
skcard . "we have no building" "my nemáme stavbu"
skcard . "I have a street" "ja mám ulicu"
skcard . "we have no head" "my nemáme hlavu"
skcard . "we have no wall" "my nemáme stenu"
skcard . "I am looking for the fingers" "ja hľadám prsty"
skcard . "he has no schools" "on nemá školy"
skcard . "y'all know the station" "vy poznáte stanicu"
skcard . "y'all know the hands" "vy poznáte ruky"
skcard . "y'all are turning the river" "vy obrátite rieku"
skcard . "I see the things" "ja vidím veci"
skcard . "he has no minute" "on nemá minútu"
skcard . "I have the vehicles" "ja mám vozy"
skcard . "I see the meadows" "ja vidím lúky"
skcard . "I am looking for hands" "ja hľadám ruky"
skcard . "y'all are turning the minute" "vy obrátite minútu"
skcard . "we have no cars" "my nemáme autá"
skcard . "y'all know the minute" "vy poznáte minútu"
skcard . "y'all know the evening" "vy poznáte večer"
skcard . "y'all are turning the town" "vy obrátite mesto"
skcard . "I have buildings" "ja mám stavby"
skcard . "I see the book" "ja vidím knihu"
skcard . "I have fences" "ja mám ploty"
skcard . "you have fences" "ty máš ploty"
skcard . "he has no questions" "on nemá otázky"
skcard . "y'all are turning a finger" "vy obrátite prst"
skcard . "he has no classrooms" "on nemá triedy"
skcard . "y'all know the garden" "vy poznáte záhradu"
skcard . "he has no pictures" "on nemá obrazy"
skcard . "he has no river banks" "on nemá brehy"
skcard . "he has no villages" "on nemá dediny"
skcard . "I see the river banks" "ja vidím brehy"
skcard . "y'all know the shop" "vy poznáte obchod"
skcard . "y'all are turning the questions" "vy obrátite otázky"
skcard . "they have evenings" "oni majú večery"
skcard . "I see a flower" "ja vidím kvet"
skcard . "y'all are turning the evening" "vy obrátite večer"
skcard . "I see the picture" "ja vidím obraz"
skcard . "you have a station" "ty máš stanicu"
skcard . "he has no vehicle" "on nemá voz"
skcard . "I need a book" "ja potrebujem knihu"
skcard . "I need vehicles" "ja potrebujem vozy"
skcard . "I need a home" "ja potrebujem dom"
skcard . "I need a wall" "ja potrebujem stenu"
skcard . "I need a classroom" "ja potrebujem triedu"
skcard . "I need a shop" "ja potrebujem obchod"
skcard . "I need a hand" "ja potrebujem ruku"
skcard . "I need questions" "ja potrebujem otázky"
skcard . "I need yards" "ja potrebujem dvory"
skcard . "I need the man" "ja potrebujem muža"
skcard . "I need a head" "ja potrebujem hlavu"
skcard . "I need minutes" "ja potrebujem minúty"
skcard . "I need streets" "ja potrebujem ulice"
skcard . "I need books" "ja potrebujem knihy"
skcard . "I need pictures" "ja potrebujem obrazy"
skcard . "I need a minute" "ja potrebujem minútu"
skcard . "I need the picture" "ja potrebujem obraz"
skcard . "I need a forest" "ja potrebujem les"
skcard . "I need flowers" "ja potrebujem kvety"
skcard . "I need walls" "ja potrebujem steny"
skcard . "I need feet" "ja potrebujem nohy"
skcard . "I need fingers" "ja potrebujem prsty"
skcard . "I need gardens" "ja potrebujem záhrady"
skcard . "I need an evening" "ja potrebujem večer"
skcard . "I need a meadow" "ja potrebujem lúku"
skcard . "I need the thing" "ja potrebujem vec"
skcard . "I need classrooms" "ja potrebujem triedy"
skcard . "I need prices" "ja potrebujem ceny"
skcard . "I need a car" "ja potrebujem auto"
skcard . "I need towns" "ja potrebujem mestá"
skcard . "I need evenings" "ja potrebujem večery"
skcard . "I need shops" "ja potrebujem obchody"
skcard . "I need homes" "ja potrebujem domy"
skcard . "I need a village" "ja potrebujem dedinu"
skcard . "I need trees" "ja potrebujem stromy"
skcard . "I need a town" "ja potrebujem mesto"
skcard . "I need a tree" "ja potrebujem strom"
skcard . "I need forests" "ja potrebujem lesy"
skcard . "I need a garden" "ja potrebujem záhradu"
skcard . "I need hands" "ja potrebujem ruky"
skcard . "I need villages" "ja potrebujem dediny"
skcard . "I need stations" "ja potrebujem stanice"
skcard . "I need a yard" "ja potrebujem dvor"
skcard . "I need buildings" "ja potrebujem stavby"
skcard . "I need a vehicle" "ja potrebujem voz"
skcard . "I need a fence" "ja potrebujem plot"
skcard . "I need a river bank" "ja potrebujem breh"
skcard . "I need a question" "ja potrebujem otázku"
skcard . "I need men" "ja potrebujem mužov"
skcard . "I need things" "ja potrebujem veci"
skcard . "I need a finger" "ja potrebujem prst"
skcard . "I need a school" "ja potrebujem školu"
skcard . "I need a foot" "ja potrebujem nohu"
skcard . "I need fences" "ja potrebujem ploty"
skcard . "I need a station" "ja potrebujem stanicu"
skcard . "I need a flower" "ja potrebujem kvet"
skcard . "I need a price" "ja potrebujem cenu"
skcard . "I need a river" "ja potrebujem rieku"
skcard . "I need a building" "ja potrebujem stavbu"
skcard . "I need cars" "ja potrebujem autá"
skcard . "I need meadows" "ja potrebujem lúky"
skcard . "I need schools" "ja potrebujem školy"
skcard . "I need river banks" "ja potrebujem brehy"
skcard . "I need a street" "ja potrebujem ulicu"
skcard . "I need rivers" "ja potrebujem rieky"
skcard . "I need heads" "ja potrebujem hlavy"
ee
#/bin/sh
skcard . "the fence is here" "plot tu je"
skcard . "the minute is here" "minúta tu je"
skcard . "the gardens are here" "záhrady tu sú"
skcard . "the building is here" "stavba tu je"
skcard . "the forest is here" "les tu je"
skcard . "the river is here" "rieka tu je"
skcard . "the yards are here" "dvory tu sú"
skcard . "the shops are here" "obchody tu sú"
skcard . "the pictures are here" "obrazy tu sú"
skcard . "the shop is here" "obchod tu je"
skcard . "the classrooms are here" "triedy tu sú"
skcard . "the meadows are here" "lúky tu sú"
skcard . "the rivers are here" "rieky tu sú"
skcard . "the gentlemen are here" "pány tu sú"
skcard . "the prices are here" "ceny tu sú"
skcard . "the towns are here" "mestá tu sú"
skcard . "the price is here" "cena tu je"
skcard . "the finger is here" "prst tu je"
skcard . "the heads are here" "hlavy tu sú"
skcard . "the meadow is here" "lúka tu je"
skcard . "the schools are here" "školy tu sú"
skcard . "the forests are here" "lesy tu sú"
skcard . "the wall is here" "stena tu je"
skcard . "the station is here" "stanica tu je"
skcard . "the books are here" "knihy tu sú"
skcard . "the fences are here" "ploty tu sú"
skcard . "the thing is here" "vec tu je"
skcard . "the hands are here" "ruky tu sú"
skcard . "the book is here" "kniha tu je"
skcard . "the flowers are here" "kvety tu sú"
skcard . "the street is here" "ulica tu je"
skcard . "the vehicles are here" "vozy tu sú"
skcard . "the garden is here" "záhrada tu je"
skcard . "the car is here" "auto tu je"
skcard . "the flower is here" "kvet tu je"
skcard . "the river bank is here" "breh tu je"
skcard . "the questions are here" "otázky tu sú"
skcard . "the school is here" "škola tu je"
skcard . "the villages are here" "dediny tu sú"
skcard . "the feet are here" "nohy tu sú"
skcard . "the men are here" "muž tu sú"
skcard . "the village is here" "dedina tu je"
skcard . "the minutes are here" "minúty tu sú"
skcard . "the fingers are here" "prsty tu sú"
skcard . "the cars are here" "autá tu sú"
skcard . "the vehicle is here" "voz tu je"
skcard . "the head is here" "hlava tu je"
skcard . "the evening is here" "večer tu je"
skcard . "the buildings are here" "stavby tu sú"
skcard . "the hand is here" "ruka tu je"
skcard . "the picture is here" "obraz tu je"
skcard . "the evenings are here" "večery tu sú"
skcard . "the stations are here" "stanice tu sú"
skcard . "the things are here" "veci tu sú"
skcard . "the walls are here" "steny tu sú"
skcard . "the home is here" "dom tu je"
skcard . "the yard is here" "dvor tu je"
skcard . "the question is here" "otázka tu je"
skcard . "the tree is here" "strom tu je"
skcard . "the river banks are here" "brehy tu sú"
skcard . "the town is here" "mesto tu je"
skcard . "the streets are here" "ulice tu sú"
skcard . "the classroom is here" "trieda tu je"
skcard . "the homes are here" "domy tu sú"
skcard . "the foot is here" "noha tu je"
skcard . "the gentleman is here" "pán tu je"
skcard . "the man is here" "muž tu je"
skcard . "the trees are here" "stromy tu sú"
