#!/bin/sh
skcard /home/mackler/Downloads/adjective-gender "this brown castle" "ten hnedý hrad"
skcard /home/mackler/Downloads/adjective-gender "this beautiful river" "tá krásna rieka"
skcard /home/mackler/Downloads/adjective-gender "this dirty river" "tá špinavá rieka"
skcard /home/mackler/Downloads/adjective-gender "this blue river" "tá modrá rieka"
skcard /home/mackler/Downloads/adjective-gender "this brown river" "tá hnedá rieka"
skcard /home/mackler/Downloads/adjective-gender "this clean river" "tá čistá rieka"
skcard /home/mackler/Downloads/adjective-gender "this ugly river" "tá škaredá rieka"
skcard /home/mackler/Downloads/adjective-gender "this bad river" "tá zlá rieka"
skcard /home/mackler/Downloads/adjective-gender "this good river" "tá dobrá rieka"
skcard /home/mackler/Downloads/adjective-gender "this young river" "tá mladá rieka"
skcard /home/mackler/Downloads/adjective-gender "this new river" "tá nová rieka"
skcard /home/mackler/Downloads/adjective-gender "this old river" "tá stará rieka"
skcard /home/mackler/Downloads/adjective-gender "this small river" "tá malá rieka"
skcard /home/mackler/Downloads/adjective-gender "this large river" "tá veľká rieka"
skcard /home/mackler/Downloads/adjective-gender "this fine river" "tá pekná rieka"
skcard /home/mackler/Downloads/adjective-gender "this beautiful town square" "to krásne námestie"
skcard /home/mackler/Downloads/adjective-gender "this dirty town square" "to špinavé námestie"
skcard /home/mackler/Downloads/adjective-gender "this blue town square" "to modré námestie"
skcard /home/mackler/Downloads/adjective-gender "this brown town square" "to hnedé námestie"
skcard /home/mackler/Downloads/adjective-gender "this clean town square" "to čisté námestie"
skcard /home/mackler/Downloads/adjective-gender "this ugly town square" "to škaredé námestie"
skcard /home/mackler/Downloads/adjective-gender "this bad town square" "to zlé námestie"
skcard /home/mackler/Downloads/adjective-gender "this good town square" "to dobré námestie"
skcard /home/mackler/Downloads/adjective-gender "this young town square" "to mladé námestie"
skcard /home/mackler/Downloads/adjective-gender "this new town square" "to nové námestie"
skcard /home/mackler/Downloads/adjective-gender "this old town square" "to staré námestie"
skcard /home/mackler/Downloads/adjective-gender "this small town square" "to malé námestie"
skcard /home/mackler/Downloads/adjective-gender "this large town square" "to veľké námestie"
skcard /home/mackler/Downloads/adjective-gender "this fine town square" "to pekné námestie"
skcard /home/mackler/Downloads/adjective-gender "this fine male teacher" "ten pekný učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this fine castle" "ten pekný hrad"
skcard /home/mackler/Downloads/adjective-gender "this fine suitcase" "ten pekný kufor"
skcard /home/mackler/Downloads/adjective-gender "this fine Danube" "ten pekný Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this fine man" "ten pekný muž"
skcard /home/mackler/Downloads/adjective-gender "this fine bull" "ten pekný býk"
skcard /home/mackler/Downloads/adjective-gender "this fine tomcat" "ten pekný kocúr"
skcard /home/mackler/Downloads/adjective-gender "this large castle" "ten veľký hrad"
skcard /home/mackler/Downloads/adjective-gender "this large suitcase" "ten veľký kufor"
skcard /home/mackler/Downloads/adjective-gender "this large Danube" "ten veľký Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this large man" "ten veľký muž"
skcard /home/mackler/Downloads/adjective-gender "this large bull" "ten veľký býk"
skcard /home/mackler/Downloads/adjective-gender "this large tomcat" "ten veľký kocúr"
skcard /home/mackler/Downloads/adjective-gender "this large male teacher" "ten veľký učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this small castle" "ten malý hrad"
skcard /home/mackler/Downloads/adjective-gender "this small suitcase" "ten malý kufor"
skcard /home/mackler/Downloads/adjective-gender "this small Danube" "ten malý Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this small man" "ten malý muž"
skcard /home/mackler/Downloads/adjective-gender "this small bull" "ten malý býk"
skcard /home/mackler/Downloads/adjective-gender "this small tomcat" "ten malý kocúr"
skcard /home/mackler/Downloads/adjective-gender "this small male teacher" "ten malý učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this old castle" "ten starý hrad"
skcard /home/mackler/Downloads/adjective-gender "this old suitcase" "ten starý kufor"
skcard /home/mackler/Downloads/adjective-gender "this old Danube" "ten starý Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this old man" "ten starý muž"
skcard /home/mackler/Downloads/adjective-gender "this old bull" "ten starý býk"
skcard /home/mackler/Downloads/adjective-gender "this old tomcat" "ten starý kocúr"
skcard /home/mackler/Downloads/adjective-gender "this old male teacher" "ten starý učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this new castle" "ten nový hrad"
skcard /home/mackler/Downloads/adjective-gender "this new suitcase" "ten nový kufor"
skcard /home/mackler/Downloads/adjective-gender "this new Danube" "ten nový Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this new man" "ten nový muž"
skcard /home/mackler/Downloads/adjective-gender "this new bull" "ten nový býk"
skcard /home/mackler/Downloads/adjective-gender "this new tomcat" "ten nový kocúr"
skcard /home/mackler/Downloads/adjective-gender "this new male teacher" "ten nový učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this young castle" "ten mladý hrad"
skcard /home/mackler/Downloads/adjective-gender "this young suitcase" "ten mladý kufor"
skcard /home/mackler/Downloads/adjective-gender "this young Danube" "ten mladý Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this young man" "ten mladý muž"
skcard /home/mackler/Downloads/adjective-gender "this young bull" "ten mladý býk"
skcard /home/mackler/Downloads/adjective-gender "this young tomcat" "ten mladý kocúr"
skcard /home/mackler/Downloads/adjective-gender "this young male teacher" "ten mladý učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this good castle" "ten dobrý hrad"
skcard /home/mackler/Downloads/adjective-gender "this good suitcase" "ten dobrý kufor"
skcard /home/mackler/Downloads/adjective-gender "this good Danube" "ten dobrý Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this good man" "ten dobrý muž"
skcard /home/mackler/Downloads/adjective-gender "this good bull" "ten dobrý býk"
skcard /home/mackler/Downloads/adjective-gender "this good tomcat" "ten dobrý kocúr"
skcard /home/mackler/Downloads/adjective-gender "this good male teacher" "ten dobrý učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this bad castle" "ten zlý hrad"
skcard /home/mackler/Downloads/adjective-gender "this bad suitcase" "ten zlý kufor"
skcard /home/mackler/Downloads/adjective-gender "this bad Danube" "ten zlý Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this bad man" "ten zlý muž"
skcard /home/mackler/Downloads/adjective-gender "this bad bull" "ten zlý býk"
skcard /home/mackler/Downloads/adjective-gender "this bad tomcat" "ten zlý kocúr"
skcard /home/mackler/Downloads/adjective-gender "this bad male teacher" "ten zlý učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this ugly castle" "ten škaredý hrad"
skcard /home/mackler/Downloads/adjective-gender "this ugly suitcase" "ten škaredý kufor"
skcard /home/mackler/Downloads/adjective-gender "this ugly Danube" "ten škaredý Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this ugly man" "ten škaredý muž"
skcard /home/mackler/Downloads/adjective-gender "this ugly bull" "ten škaredý býk"
skcard /home/mackler/Downloads/adjective-gender "this ugly tomcat" "ten škaredý kocúr"
skcard /home/mackler/Downloads/adjective-gender "this ugly male teacher" "ten škaredý učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this clean castle" "ten čistý hrad"
skcard /home/mackler/Downloads/adjective-gender "this clean suitcase" "ten čistý kufor"
skcard /home/mackler/Downloads/adjective-gender "this clean Danube" "ten čistý Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this clean man" "ten čistý muž"
skcard /home/mackler/Downloads/adjective-gender "this clean bull" "ten čistý býk"
skcard /home/mackler/Downloads/adjective-gender "this clean tomcat" "ten čistý kocúr"
skcard /home/mackler/Downloads/adjective-gender "this clean male teacher" "ten čistý učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this brown suitcase" "ten hnedý kufor"
skcard /home/mackler/Downloads/adjective-gender "this brown Danube" "ten hnedý Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this brown man" "ten hnedý muž"
skcard /home/mackler/Downloads/adjective-gender "this brown bull" "ten hnedý býk"
skcard /home/mackler/Downloads/adjective-gender "this brown tomcat" "ten hnedý kocúr"
skcard /home/mackler/Downloads/adjective-gender "this brown male teacher" "ten hnedý učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this blue castle" "ten modrý hrad"
skcard /home/mackler/Downloads/adjective-gender "this blue suitcase" "ten modrý kufor"
skcard /home/mackler/Downloads/adjective-gender "this blue Danube" "ten modrý Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this blue man" "ten modrý muž"
skcard /home/mackler/Downloads/adjective-gender "this blue bull" "ten modrý býk"
skcard /home/mackler/Downloads/adjective-gender "this blue tomcat" "ten modrý kocúr"
skcard /home/mackler/Downloads/adjective-gender "this blue male teacher" "ten modrý učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this dirty castle" "ten špinavý hrad"
skcard /home/mackler/Downloads/adjective-gender "this dirty suitcase" "ten špinavý kufor"
skcard /home/mackler/Downloads/adjective-gender "this dirty Danube" "ten špinavý Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this dirty man" "ten špinavý muž"
skcard /home/mackler/Downloads/adjective-gender "this dirty bull" "ten špinavý býk"
skcard /home/mackler/Downloads/adjective-gender "this dirty tomcat" "ten špinavý kocúr"
skcard /home/mackler/Downloads/adjective-gender "this dirty male teacher" "ten špinavý učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this beautiful castle" "ten krásny hrad"
skcard /home/mackler/Downloads/adjective-gender "this beautiful suitcase" "ten krásny kufor"
skcard /home/mackler/Downloads/adjective-gender "this beautiful Danube" "ten krásny Dunaj"
skcard /home/mackler/Downloads/adjective-gender "this beautiful man" "ten krásny muž"
skcard /home/mackler/Downloads/adjective-gender "this beautiful bull" "ten krásny býk"
skcard /home/mackler/Downloads/adjective-gender "this beautiful tomcat" "ten krásny kocúr"
skcard /home/mackler/Downloads/adjective-gender "this beautiful male teacher" "ten krásny učiteľ"
skcard /home/mackler/Downloads/adjective-gender "this fine water" "tá pekná voda"
skcard /home/mackler/Downloads/adjective-gender "this fine joy" "tá pekná radosť"
skcard /home/mackler/Downloads/adjective-gender "this fine woman" "tá pekná žena"
skcard /home/mackler/Downloads/adjective-gender "this fine cow" "tá pekná krava"
skcard /home/mackler/Downloads/adjective-gender "this fine cat" "tá pekná mačka"
skcard /home/mackler/Downloads/adjective-gender "this fine female teacher" "tá pekná učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this fine café" "tá pekná kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this large water" "tá veľká voda"
skcard /home/mackler/Downloads/adjective-gender "this large joy" "tá veľká radosť"
skcard /home/mackler/Downloads/adjective-gender "this large woman" "tá veľká žena"
skcard /home/mackler/Downloads/adjective-gender "this large cow" "tá veľká krava"
skcard /home/mackler/Downloads/adjective-gender "this large cat" "tá veľká mačka"
skcard /home/mackler/Downloads/adjective-gender "this large female teacher" "tá veľká učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this large café" "tá veľká kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this small water" "tá malá voda"
skcard /home/mackler/Downloads/adjective-gender "this small joy" "tá malá radosť"
skcard /home/mackler/Downloads/adjective-gender "this small woman" "tá malá žena"
skcard /home/mackler/Downloads/adjective-gender "this small cow" "tá malá krava"
skcard /home/mackler/Downloads/adjective-gender "this small cat" "tá malá mačka"
skcard /home/mackler/Downloads/adjective-gender "this small female teacher" "tá malá učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this small café" "tá malá kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this old water" "tá stará voda"
skcard /home/mackler/Downloads/adjective-gender "this old joy" "tá stará radosť"
skcard /home/mackler/Downloads/adjective-gender "this old woman" "tá stará žena"
skcard /home/mackler/Downloads/adjective-gender "this old cow" "tá stará krava"
skcard /home/mackler/Downloads/adjective-gender "this old cat" "tá stará mačka"
skcard /home/mackler/Downloads/adjective-gender "this old female teacher" "tá stará učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this old café" "tá stará kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this new water" "tá nová voda"
skcard /home/mackler/Downloads/adjective-gender "this new joy" "tá nová radosť"
skcard /home/mackler/Downloads/adjective-gender "this new woman" "tá nová žena"
skcard /home/mackler/Downloads/adjective-gender "this new cow" "tá nová krava"
skcard /home/mackler/Downloads/adjective-gender "this new cat" "tá nová mačka"
skcard /home/mackler/Downloads/adjective-gender "this new female teacher" "tá nová učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this new café" "tá nová kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this young water" "tá mladá voda"
skcard /home/mackler/Downloads/adjective-gender "this young joy" "tá mladá radosť"
skcard /home/mackler/Downloads/adjective-gender "this young woman" "tá mladá žena"
skcard /home/mackler/Downloads/adjective-gender "this young cow" "tá mladá krava"
skcard /home/mackler/Downloads/adjective-gender "this young cat" "tá mladá mačka"
skcard /home/mackler/Downloads/adjective-gender "this young female teacher" "tá mladá učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this young café" "tá mladá kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this good water" "tá dobrá voda"
skcard /home/mackler/Downloads/adjective-gender "this good joy" "tá dobrá radosť"
skcard /home/mackler/Downloads/adjective-gender "this good woman" "tá dobrá žena"
skcard /home/mackler/Downloads/adjective-gender "this good cow" "tá dobrá krava"
skcard /home/mackler/Downloads/adjective-gender "this good cat" "tá dobrá mačka"
skcard /home/mackler/Downloads/adjective-gender "this good female teacher" "tá dobrá učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this good café" "tá dobrá kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this bad water" "tá zlá voda"
skcard /home/mackler/Downloads/adjective-gender "this bad joy" "tá zlá radosť"
skcard /home/mackler/Downloads/adjective-gender "this bad woman" "tá zlá žena"
skcard /home/mackler/Downloads/adjective-gender "this bad cow" "tá zlá krava"
skcard /home/mackler/Downloads/adjective-gender "this bad cat" "tá zlá mačka"
skcard /home/mackler/Downloads/adjective-gender "this bad female teacher" "tá zlá učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this bad café" "tá zlá kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this ugly water" "tá škaredá voda"
skcard /home/mackler/Downloads/adjective-gender "this ugly joy" "tá škaredá radosť"
skcard /home/mackler/Downloads/adjective-gender "this ugly woman" "tá škaredá žena"
skcard /home/mackler/Downloads/adjective-gender "this ugly cow" "tá škaredá krava"
skcard /home/mackler/Downloads/adjective-gender "this ugly cat" "tá škaredá mačka"
skcard /home/mackler/Downloads/adjective-gender "this ugly female teacher" "tá škaredá učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this ugly café" "tá škaredá kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this clean water" "tá čistá voda"
skcard /home/mackler/Downloads/adjective-gender "this clean joy" "tá čistá radosť"
skcard /home/mackler/Downloads/adjective-gender "this clean woman" "tá čistá žena"
skcard /home/mackler/Downloads/adjective-gender "this clean cow" "tá čistá krava"
skcard /home/mackler/Downloads/adjective-gender "this clean cat" "tá čistá mačka"
skcard /home/mackler/Downloads/adjective-gender "this clean female teacher" "tá čistá učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this clean café" "tá čistá kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this brown water" "tá hnedá voda"
skcard /home/mackler/Downloads/adjective-gender "this brown joy" "tá hnedá radosť"
skcard /home/mackler/Downloads/adjective-gender "this brown woman" "tá hnedá žena"
skcard /home/mackler/Downloads/adjective-gender "this brown cow" "tá hnedá krava"
skcard /home/mackler/Downloads/adjective-gender "this brown cat" "tá hnedá mačka"
skcard /home/mackler/Downloads/adjective-gender "this brown female teacher" "tá hnedá učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this brown café" "tá hnedá kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this blue water" "tá modrá voda"
skcard /home/mackler/Downloads/adjective-gender "this blue joy" "tá modrá radosť"
skcard /home/mackler/Downloads/adjective-gender "this blue woman" "tá modrá žena"
skcard /home/mackler/Downloads/adjective-gender "this blue cow" "tá modrá krava"
skcard /home/mackler/Downloads/adjective-gender "this blue cat" "tá modrá mačka"
skcard /home/mackler/Downloads/adjective-gender "this blue female teacher" "tá modrá učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this blue café" "tá modrá kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this dirty water" "tá špinavá voda"
skcard /home/mackler/Downloads/adjective-gender "this dirty joy" "tá špinavá radosť"
skcard /home/mackler/Downloads/adjective-gender "this dirty woman" "tá špinavá žena"
skcard /home/mackler/Downloads/adjective-gender "this dirty cow" "tá špinavá krava"
skcard /home/mackler/Downloads/adjective-gender "this dirty cat" "tá špinavá mačka"
skcard /home/mackler/Downloads/adjective-gender "this dirty female teacher" "tá špinavá učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this dirty café" "tá špinavá kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this beautiful water" "tá krásna voda"
skcard /home/mackler/Downloads/adjective-gender "this beautiful joy" "tá krásna radosť"
skcard /home/mackler/Downloads/adjective-gender "this beautiful woman" "tá krásna žena"
skcard /home/mackler/Downloads/adjective-gender "this beautiful cow" "tá krásna krava"
skcard /home/mackler/Downloads/adjective-gender "this beautiful cat" "tá krásna mačka"
skcard /home/mackler/Downloads/adjective-gender "this beautiful female teacher" "tá krásna učiteľka"
skcard /home/mackler/Downloads/adjective-gender "this beautiful café" "tá krásna kaviareň"
skcard /home/mackler/Downloads/adjective-gender "this fine town" "to pekné mesto"
skcard /home/mackler/Downloads/adjective-gender "this fine car" "to pekné auto"
skcard /home/mackler/Downloads/adjective-gender "this fine heart" "to pekné srdce"
skcard /home/mackler/Downloads/adjective-gender "this fine kitten" "to pekné mača"
skcard /home/mackler/Downloads/adjective-gender "this fine calf" "to pekné teľa"
skcard /home/mackler/Downloads/adjective-gender "this fine child" "to pekné dieťa"
skcard /home/mackler/Downloads/adjective-gender "this fine girl" "to pekné dievča"
skcard /home/mackler/Downloads/adjective-gender "this large town" "to veľké mesto"
skcard /home/mackler/Downloads/adjective-gender "this large car" "to veľké auto"
skcard /home/mackler/Downloads/adjective-gender "this large heart" "to veľké srdce"
skcard /home/mackler/Downloads/adjective-gender "this large kitten" "to veľké mača"
skcard /home/mackler/Downloads/adjective-gender "this large calf" "to veľké teľa"
skcard /home/mackler/Downloads/adjective-gender "this large child" "to veľké dieťa"
skcard /home/mackler/Downloads/adjective-gender "this large girl" "to veľké dievča"
skcard /home/mackler/Downloads/adjective-gender "this small town" "to malé mesto"
skcard /home/mackler/Downloads/adjective-gender "this small car" "to malé auto"
skcard /home/mackler/Downloads/adjective-gender "this small heart" "to malé srdce"
skcard /home/mackler/Downloads/adjective-gender "this small kitten" "to malé mača"
skcard /home/mackler/Downloads/adjective-gender "this small calf" "to malé teľa"
skcard /home/mackler/Downloads/adjective-gender "this small child" "to malé dieťa"
skcard /home/mackler/Downloads/adjective-gender "this small girl" "to malé dievča"
skcard /home/mackler/Downloads/adjective-gender "this old town" "to staré mesto"
skcard /home/mackler/Downloads/adjective-gender "this old car" "to staré auto"
skcard /home/mackler/Downloads/adjective-gender "this old heart" "to staré srdce"
skcard /home/mackler/Downloads/adjective-gender "this old kitten" "to staré mača"
skcard /home/mackler/Downloads/adjective-gender "this old calf" "to staré teľa"
skcard /home/mackler/Downloads/adjective-gender "this old child" "to staré dieťa"
skcard /home/mackler/Downloads/adjective-gender "this old girl" "to staré dievča"
skcard /home/mackler/Downloads/adjective-gender "this new town" "to nové mesto"
skcard /home/mackler/Downloads/adjective-gender "this new car" "to nové auto"
skcard /home/mackler/Downloads/adjective-gender "this new heart" "to nové srdce"
skcard /home/mackler/Downloads/adjective-gender "this new kitten" "to nové mača"
skcard /home/mackler/Downloads/adjective-gender "this new calf" "to nové teľa"
skcard /home/mackler/Downloads/adjective-gender "this new child" "to nové dieťa"
skcard /home/mackler/Downloads/adjective-gender "this new girl" "to nové dievča"
skcard /home/mackler/Downloads/adjective-gender "this young town" "to mladé mesto"
skcard /home/mackler/Downloads/adjective-gender "this young car" "to mladé auto"
skcard /home/mackler/Downloads/adjective-gender "this young heart" "to mladé srdce"
skcard /home/mackler/Downloads/adjective-gender "this young kitten" "to mladé mača"
skcard /home/mackler/Downloads/adjective-gender "this young calf" "to mladé teľa"
skcard /home/mackler/Downloads/adjective-gender "this young child" "to mladé dieťa"
skcard /home/mackler/Downloads/adjective-gender "this young girl" "to mladé dievča"
skcard /home/mackler/Downloads/adjective-gender "this good town" "to dobré mesto"
skcard /home/mackler/Downloads/adjective-gender "this good car" "to dobré auto"
skcard /home/mackler/Downloads/adjective-gender "this good heart" "to dobré srdce"
skcard /home/mackler/Downloads/adjective-gender "this good kitten" "to dobré mača"
skcard /home/mackler/Downloads/adjective-gender "this good calf" "to dobré teľa"
skcard /home/mackler/Downloads/adjective-gender "this good child" "to dobré dieťa"
skcard /home/mackler/Downloads/adjective-gender "this good girl" "to dobré dievča"
skcard /home/mackler/Downloads/adjective-gender "this bad town" "to zlé mesto"
skcard /home/mackler/Downloads/adjective-gender "this bad car" "to zlé auto"
skcard /home/mackler/Downloads/adjective-gender "this bad heart" "to zlé srdce"
skcard /home/mackler/Downloads/adjective-gender "this bad kitten" "to zlé mača"
skcard /home/mackler/Downloads/adjective-gender "this bad calf" "to zlé teľa"
skcard /home/mackler/Downloads/adjective-gender "this bad child" "to zlé dieťa"
skcard /home/mackler/Downloads/adjective-gender "this bad girl" "to zlé dievča"
skcard /home/mackler/Downloads/adjective-gender "this ugly town" "to škaredé mesto"
skcard /home/mackler/Downloads/adjective-gender "this ugly car" "to škaredé auto"
skcard /home/mackler/Downloads/adjective-gender "this ugly heart" "to škaredé srdce"
skcard /home/mackler/Downloads/adjective-gender "this ugly kitten" "to škaredé mača"
skcard /home/mackler/Downloads/adjective-gender "this ugly calf" "to škaredé teľa"
skcard /home/mackler/Downloads/adjective-gender "this ugly child" "to škaredé dieťa"
skcard /home/mackler/Downloads/adjective-gender "this ugly girl" "to škaredé dievča"
skcard /home/mackler/Downloads/adjective-gender "this clean town" "to čisté mesto"
skcard /home/mackler/Downloads/adjective-gender "this clean car" "to čisté auto"
skcard /home/mackler/Downloads/adjective-gender "this clean heart" "to čisté srdce"
skcard /home/mackler/Downloads/adjective-gender "this clean kitten" "to čisté mača"
skcard /home/mackler/Downloads/adjective-gender "this clean calf" "to čisté teľa"
skcard /home/mackler/Downloads/adjective-gender "this clean child" "to čisté dieťa"
skcard /home/mackler/Downloads/adjective-gender "this clean girl" "to čisté dievča"
skcard /home/mackler/Downloads/adjective-gender "this brown town" "to hnedé mesto"
skcard /home/mackler/Downloads/adjective-gender "this brown car" "to hnedé auto"
skcard /home/mackler/Downloads/adjective-gender "this brown heart" "to hnedé srdce"
skcard /home/mackler/Downloads/adjective-gender "this brown kitten" "to hnedé mača"
skcard /home/mackler/Downloads/adjective-gender "this brown calf" "to hnedé teľa"
skcard /home/mackler/Downloads/adjective-gender "this brown child" "to hnedé dieťa"
skcard /home/mackler/Downloads/adjective-gender "this brown girl" "to hnedé dievča"
skcard /home/mackler/Downloads/adjective-gender "this blue town" "to modré mesto"
skcard /home/mackler/Downloads/adjective-gender "this blue car" "to modré auto"
skcard /home/mackler/Downloads/adjective-gender "this blue heart" "to modré srdce"
skcard /home/mackler/Downloads/adjective-gender "this blue kitten" "to modré mača"
skcard /home/mackler/Downloads/adjective-gender "this blue calf" "to modré teľa"
skcard /home/mackler/Downloads/adjective-gender "this blue child" "to modré dieťa"
skcard /home/mackler/Downloads/adjective-gender "this blue girl" "to modré dievča"
skcard /home/mackler/Downloads/adjective-gender "this dirty town" "to špinavé mesto"
skcard /home/mackler/Downloads/adjective-gender "this dirty car" "to špinavé auto"
skcard /home/mackler/Downloads/adjective-gender "this dirty heart" "to špinavé srdce"
skcard /home/mackler/Downloads/adjective-gender "this dirty kitten" "to špinavé mača"
skcard /home/mackler/Downloads/adjective-gender "this dirty calf" "to špinavé teľa"
skcard /home/mackler/Downloads/adjective-gender "this dirty child" "to špinavé dieťa"
skcard /home/mackler/Downloads/adjective-gender "this dirty girl" "to špinavé dievča"
skcard /home/mackler/Downloads/adjective-gender "this beautiful town" "to krásne mesto"
skcard /home/mackler/Downloads/adjective-gender "this beautiful car" "to krásne auto"
skcard /home/mackler/Downloads/adjective-gender "this beautiful heart" "to krásne srdce"
skcard /home/mackler/Downloads/adjective-gender "this beautiful kitten" "to krásne mača"
skcard /home/mackler/Downloads/adjective-gender "this beautiful calf" "to krásne teľa"
skcard /home/mackler/Downloads/adjective-gender "this beautiful child" "to krásne dieťa"
skcard /home/mackler/Downloads/adjective-gender "this beautiful girl" "to krásne dievča"
